Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
Stopping ray
[31mCould not terminate `[1m/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py[22m[26m` due to (pid=2527733, name='python3')[39m
Did not find any active Ray processes.
Running main3_more_sorries.py
[2024-09-17 19:53:59,386] [WARNING] [real_accelerator.py:162:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2024-09-17 19:53:59,387] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cpu (auto detect)
WARNING 09-17 19:54:01 _custom_ops.py:18] Failed to import from vllm._C with ImportError('libcuda.so.1: cannot open shared object file: No such file or directory')
2024-09-17 19:54:04.902 | INFO     | __main__:main:1507 - Running progressive training
2024-09-17 19:54:04.903 | INFO     | __main__:main:1513 - Configuring LeanDojo...
2024-09-17 19:54:04.907 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/yingzi_ma/lean_project/ReProver
2024-09-17 19:54:04.907 | INFO     | __main__:main:1515 - LeanDojo configured
2024-09-17 19:54:04.907 | INFO     | __main__:main:1520 - Starting the main process
2024-09-17 19:54:04.908 | INFO     | __main__:main:1528 - Loading database from /data/yingzi_ma/lean_project/dynamic_database_PT_single_repo_no_ewc_curriculum_sorries.json
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
Stopping ray
[31mCould not terminate `[1m/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py[22m[26m` due to (pid=2527733, name='python3')[39m
Did not find any active Ray processes.
Running main3_more_sorries.py
[2024-09-17 19:54:50,821] [WARNING] [real_accelerator.py:162:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2024-09-17 19:54:50,822] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cpu (auto detect)
WARNING 09-17 19:54:52 _custom_ops.py:18] Failed to import from vllm._C with ImportError('libcuda.so.1: cannot open shared object file: No such file or directory')
2024-09-17 19:54:55.922 | INFO     | __main__:main:1507 - Running progressive training
2024-09-17 19:54:55.922 | INFO     | __main__:main:1513 - Configuring LeanDojo...
2024-09-17 19:54:55.925 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/yingzi_ma/lean_project/ReProver
2024-09-17 19:54:55.925 | INFO     | __main__:main:1515 - LeanDojo configured
2024-09-17 19:54:55.926 | INFO     | __main__:main:1520 - Starting the main process
2024-09-17 19:54:55.926 | INFO     | __main__:main:1528 - Loading database from /data/yingzi_ma/lean_project/dynamic_database_PT_single_repo_no_ewc_curriculum_sorries.json
2024-09-17 19:55:28.103 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.com/apnelson1/Matroid (commit: 244315752bb0a771f20b676b946130b664d60712)
2024-09-17 19:55:28.103 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/apnelson1/Matroid (commit: 244315752bb0a771f20b676b946130b664d60712)
2024-09-17 19:55:36.743 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.com/NUS-Math-Formalization/coxeter (commit: 96af8aee7943ca8685ed1b00cc83a559ea389a97)
2024-09-17 19:55:36.743 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/NUS-Math-Formalization/coxeter (commit: 96af8aee7943ca8685ed1b00cc83a559ea389a97)
2024-09-17 19:55:43.335 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.com/YaelDillies/LeanAPAP (commit: 951c660a8d7ba8e39f906fdf657674a984effa8b)
2024-09-17 19:55:43.335 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/YaelDillies/LeanAPAP (commit: 951c660a8d7ba8e39f906fdf657674a984effa8b)
2024-09-17 19:55:45.295 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.com/fpvandoorn/carleson (commit: bec7808b907190882fa1fa54ce749af297c6cf37)
2024-09-17 19:55:45.295 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/fpvandoorn/carleson (commit: bec7808b907190882fa1fa54ce749af297c6cf37)
2024-09-17 19:55:52.631 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.com/yangky11/miniF2F-lean4 (commit: 9e445f5435407f014b88b44a98436d50dd7abd00)
2024-09-17 19:55:52.631 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/yangky11/miniF2F-lean4 (commit: 9e445f5435407f014b88b44a98436d50dd7abd00)
2024-09-17 19:56:01.044 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.com/mo271/formal_book (commit: 6fbe8c2985008c0bfb30050750a71b90388ad3a3)
2024-09-17 19:56:01.044 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/mo271/formal_book (commit: 6fbe8c2985008c0bfb30050750a71b90388ad3a3)
2024-09-17 19:56:01.733 | INFO     | __main__:main:1530 - Loaded database from /data/yingzi_ma/lean_project/dynamic_database_PT_single_repo_no_ewc_curriculum_sorries.json
2024-09-17 19:56:01.734 | INFO     | __main__:main:1537 - Found 100 repositories
2024-09-17 19:56:01.735 | INFO     | __main__:main:1540 - Starting curriculum learning
2024-09-17 19:56:01.983 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.12.0-rc1
2024-09-17 19:56:19.974 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0
2024-09-17 19:56:37.285 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.9.0-rc2
2024-09-17 19:56:54.999 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.8.0-rc1
2024-09-17 19:57:12.808 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0-rc2
2024-09-17 19:57:29.816 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0-rc3
2024-09-17 19:57:48.712 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.7.0
2024-09-17 19:58:06.272 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0-rc1
2024-09-17 19:58:23.420 | INFO     | __main__:main:1628 - Processing https://github.com/mckoen/quasicategory
2024-09-17 19:58:23.421 | INFO     | __main__:add_repo_to_database:1194 - Processing https://github.com/mckoen/quasicategory.git
2024-09-17 19:58:23.728 | INFO     | __main__:get_compatible_commit:596 - Latest commit: a34685942321beff3b37adff3f214aa64bf04dde
2024-09-17 19:58:23.728 | INFO     | __main__:get_compatible_commit:599 - Creating LeanGitRepo for https://github.com/mckoen/quasicategory
2024-09-17 19:58:23.729 | INFO     | __main__:get_compatible_commit:601 - Getting config for https://github.com/mckoen/quasicategory.git
2024-09-17 19:58:23.729 | INFO     | __main__:get_compatible_commit:608 - Searching for compatible commit for https://github.com/mckoen/quasicategory.git
2024-09-17 19:58:23.734 | INFO     | __main__:get_compatible_commit:614 - Already in a Git repository
2024-09-17 19:58:23.736 | INFO     | __main__:get_compatible_commit:624 - Fetching commits for https://github.com/mckoen/quasicategory.git
2024-09-17 19:58:25.238 | INFO     | __main__:get_compatible_commit:628 - Fetched commits for https://github.com/mckoen/quasicategory.git
2024-09-17 19:58:25.241 | INFO     | __main__:get_compatible_commit:634 - Getting list of commits for https://github.com/mckoen/quasicategory.git
2024-09-17 19:58:25.274 | INFO     | __main__:get_compatible_commit:639 - Found 13 commits for https://github.com/mckoen/quasicategory.git
2024-09-17 19:58:28.091 | INFO     | __main__:get_compatible_commit:652 - Error in get_compatible_commit: No compatible commit found
2024-09-17 19:58:28.091 | INFO     | __main__:add_repo_to_database:1212 - Failed to find a compatible commit for https://github.com/mckoen/quasicategory.git
2024-09-17 19:58:28.091 | INFO     | __main__:main:1628 - Processing https://github.com/mdnestor/SymbolicDynamics
2024-09-17 19:58:28.091 | INFO     | __main__:add_repo_to_database:1194 - Processing https://github.com/mdnestor/SymbolicDynamics.git
2024-09-17 19:58:28.377 | INFO     | __main__:get_compatible_commit:596 - Latest commit: 72075d53fd1ad31d0db7818502d2cce3189cf90f
2024-09-17 19:58:28.378 | INFO     | __main__:get_compatible_commit:599 - Creating LeanGitRepo for https://github.com/mdnestor/SymbolicDynamics
2024-09-17 19:58:28.378 | INFO     | __main__:get_compatible_commit:601 - Getting config for https://github.com/mdnestor/SymbolicDynamics.git
2024-09-17 19:58:28.378 | INFO     | __main__:get_compatible_commit:608 - Searching for compatible commit for https://github.com/mdnestor/SymbolicDynamics.git
2024-09-17 19:58:28.383 | INFO     | __main__:get_compatible_commit:614 - Already in a Git repository
2024-09-17 19:58:28.386 | INFO     | __main__:get_compatible_commit:624 - Fetching commits for https://github.com/mdnestor/SymbolicDynamics.git
2024-09-17 19:58:30.066 | INFO     | __main__:get_compatible_commit:628 - Fetched commits for https://github.com/mdnestor/SymbolicDynamics.git
2024-09-17 19:58:30.070 | INFO     | __main__:get_compatible_commit:634 - Getting list of commits for https://github.com/mdnestor/SymbolicDynamics.git
2024-09-17 19:58:30.096 | INFO     | __main__:get_compatible_commit:639 - Found 54 commits for https://github.com/mdnestor/SymbolicDynamics.git
2024-09-17 19:58:42.065 | INFO     | __main__:get_compatible_commit:652 - Error in get_compatible_commit: No compatible commit found
2024-09-17 19:58:42.066 | INFO     | __main__:add_repo_to_database:1212 - Failed to find a compatible commit for https://github.com/mdnestor/SymbolicDynamics.git
2024-09-17 19:58:42.066 | INFO     | __main__:main:1628 - Processing https://github.com/Jun2M/Kura
2024-09-17 19:58:42.066 | INFO     | __main__:add_repo_to_database:1194 - Processing https://github.com/Jun2M/Kura.git
2024-09-17 19:58:42.359 | INFO     | __main__:get_compatible_commit:596 - Latest commit: f30b7539c6b4a6c4a7c5d5fb66602900f0367044
2024-09-17 19:58:42.359 | INFO     | __main__:get_compatible_commit:599 - Creating LeanGitRepo for https://github.com/Jun2M/Kura
2024-09-17 19:58:42.359 | INFO     | __main__:get_compatible_commit:601 - Getting config for https://github.com/Jun2M/Kura.git
2024-09-17 19:58:42.359 | INFO     | __main__:get_compatible_commit:608 - Searching for compatible commit for https://github.com/Jun2M/Kura.git
2024-09-17 19:58:42.363 | INFO     | __main__:get_compatible_commit:614 - Already in a Git repository
2024-09-17 19:58:42.365 | INFO     | __main__:get_compatible_commit:624 - Fetching commits for https://github.com/Jun2M/Kura.git
2024-09-17 19:58:43.860 | INFO     | __main__:get_compatible_commit:628 - Fetched commits for https://github.com/Jun2M/Kura.git
2024-09-17 19:58:43.864 | INFO     | __main__:get_compatible_commit:634 - Getting list of commits for https://github.com/Jun2M/Kura.git
2024-09-17 19:58:43.885 | INFO     | __main__:get_compatible_commit:639 - Found 10 commits for https://github.com/Jun2M/Kura.git
2024-09-17 19:58:44.955 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.10.0-rc2
2024-09-17 19:59:02.264 | INFO     | __main__:get_compatible_commit:652 - Error in get_compatible_commit: No compatible commit found
2024-09-17 19:59:02.265 | INFO     | __main__:add_repo_to_database:1212 - Failed to find a compatible commit for https://github.com/Jun2M/Kura.git
2024-09-17 19:59:02.265 | INFO     | __main__:main:1632 - Successfully added 100 repositories to the database
