
[rank0]:[W901 04:10:24.355995885 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_proce
ss_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint h
as always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
(ReProver) yingzi_ma@compute-permanent-node-834:~/lean_project/ReProver$ python distributed_test.py --timeout 30 --num_gpus 4
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python distributed_test.py --timeout 30 --num_gpus 4 ...
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python distributed_test.py --timeout 30 --num_gpus 4 ...
You are using a CUDA device ('NVIDIA A100-SXM4-80GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performa
nce. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

NCCL version 2.20.5+cuda12.4
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

  | Name  | Type   | Params
---------------------------------
0 | layer | Linear | 2
---------------------------------
2         Trainable params
0         Non-trainable params
2         Total params
0.000     Total estimated model params size (MB)
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py:298: The number of training batches (3) is smaller than the logging interval Trainer(log_every_n_steps=50). Set
 a lower value for log_every_n_steps if you want to see logs for the training epoch.
Epoch 0:   0%|
     | 0/3 [00:00<?, ?it/s]Rank 1: Before barrier
rank: 1
world size: 4
Rank 2: Before barrier
rank: 2
world size: 4
Rank 3: Before barrier
rank: 3
world size: 4
Rank 0: Before barrier
rank: 0
world size: 4
Rank 0: Barrier completed successfully in 0.004868 seconds
Rank 1: Barrier completed successfully in 0.017645 seconds
Rank 3: Barrier completed successfully in 0.015301 seconds
Rank 2: Barrier completed successfully in 0.016871 seconds
Rank 0: After barrier
Rank 1: After barrier
Rank 2: After barrier
Rank 3: After barrier
Epoch 0:  67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                               | 2/3 [00:00<
00:00,  9.53it/s, v_num=32]Rank 2: Before barrier epoch end
rank: 2
Rank 1: Before barrier epoch end
world size: 4
rank: 1
world size: 4
Rank 3: Before barrier epoch end
rank: 3
world size: 4
Epoch 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<
00:00, 13.84it/s, v_num=32]Rank 0: Before barrier epoch end
rank: 0
world size: 4
Rank 0: Barrier completed successfully in 0.002434 seconds
Rank 1: Barrier completed successfully in 0.004849 seconds
Rank 2: Barrier completed successfully in 0.004851 seconds
Rank 0: After barrier epoch end
Rank 1: After barrier epoch end
Rank 3: Barrier completed successfully in 0.004854 seconds
Rank 2: After barrier epoch end
Rank 3: After barrier epoch end
`Trainer.fit` stopped: `max_epochs=1` reached.
Epoch 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<
00:00, 10.22it/s, v_num=32]
[rank0]:[W901 04:10:50.894528991 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_proce
ss_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint h
as always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
(ReProver) yingzi_ma@compute-permanent-node-834:~/lean_project/ReProver$ python distributed_test.py --timeout 30 --num_gpus 4
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python distributed_test.py --timeout 30 --num_gpus 4 ...
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python distributed_test.py --timeout 30 --num_gpus 4 ...
You are using a CUDA device ('NVIDIA A100-SXM4-80GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performa
nce. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

NCCL version 2.20.5+cuda12.4
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

  | Name  | Type   | Params
---------------------------------
0 | layer | Linear | 2
---------------------------------
2         Trainable params
0         Non-trainable params
2         Total params
0.000     Total estimated model params size (MB)
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py:298: The number of training batches (3) is smaller than the logging interval Trainer(log_every_n_steps=50). Set
 a lower value for log_every_n_steps if you want to see logs for the training epoch.
Epoch 0:   0%|
     | 0/3 [00:00<?, ?it/s]Rank 2: Before barrier
rank: 2
world size: 4
Rank 3: Before barrier
rank: 3
world size: 4
Rank 1: Before barrier
rank: 1
world size: 4
Rank 0: Before barrier
rank: 0
world size: 4
Rank 1: Barrier completed successfully in 0.010967 seconds
Rank 0: Barrier completed successfully in 0.004873 seconds
Rank 1: After barrier
Rank 3: Barrier completed successfully in 0.069207 seconds
Rank 2: Barrier completed successfully in 0.069424 seconds
Rank 3: After barrier
Rank 2: After barrier
Rank 0: After barrier
Epoch 0:  67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                               | 2/3 [00:00<
00:00,  8.16it/s, v_num=33]Rank 2: Before barrier epoch end
rank: 2
world size: 4
Epoch 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<
00:00, 11.52it/s, v_num=33]Rank 1: Before barrier epoch end
rank: 1
world size: 4
Epoch 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<
00:00, 11.49it/s, v_num=33]Rank 0: Before barrier epoch end
rank: 0
world size: 4
Rank 3: Before barrier epoch end
rank: 3
world size: 4
Rank 0: Barrier completed successfully in 0.002431 seconds
Rank 2: Barrier completed successfully in 0.002430 seconds
Rank 1: Barrier completed successfully in 0.002429 seconds
Rank 0: After barrier epoch end
Rank 2: After barrier epoch end
Rank 1: After barrier epoch end
Rank 3: Barrier completed successfully in 0.001860 seconds
Rank 3: After barrier epoch end
`Trainer.fit` stopped: `max_epochs=1` reached.
Epoch 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<
00:00,  8.79it/s, v_num=33]
[rank0]:[W901 04:11:29.475254294 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_proce
ss_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint h
as always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
(ReProver) yingzi_ma@compute-permanent-node-834:~/lean_project/ReProver$ python distributed_test.py --timeout 30 --num_gpus 4
^CTraceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/distributed_test.py", line 154, in <module>
    import pytorch_lightning as pl
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 27, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 26, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/callbacks/callback.py", line 22, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/utilities/types.py", line 41, in <module>
    from torchmetrics import Metric
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torchmetrics/__init__.py", line 23, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torchmetrics/functional/__init__.py", line 122, in <module>
    from torchmetrics.functional.text._deprecated import _bleu_score as bleu_score
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torchmetrics/functional/text/__init__.py", line 50, in <module>
    from torchmetrics.functional.text.bert import bert_score
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torchmetrics/functional/text/bert.py", line 55, in <module>
    from transformers import AutoModel, AutoTokenizer
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/utils/__init__.py", line 18, in <module>
    from huggingface_hub import get_full_repo_name  # for backward compatibility
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/huggingface_hub/__init__.py", line 520, in __getattr__
    submod = importlib.import_module(submod_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 45, in <module>
    import requests
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/requests/__init__.py", line 151, in <module>
    from . import packages, utils
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/requests/utils.py", line 52, in <module>
    from .cookies import cookiejar_from_dict
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1074, in get_data
KeyboardInterrupt

(ReProver) yingzi_ma@compute-permanent-node-834:~/lean_project/ReProver$ python distributed_test.py --timeout 30 --num_gpus 4
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python distributed_test.py --timeout 30 --num_gpus 4 ...
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python distributed_test.py --timeout 30 --num_gpus 4 ...
You are using a CUDA device ('NVIDIA A100-SXM4-80GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performa
nce. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

NCCL version 2.20.5+cuda12.4
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

  | Name  | Type   | Params
---------------------------------
0 | layer | Linear | 2
---------------------------------
2         Trainable params
0         Non-trainable params
2         Total params
0.000     Total estimated model params size (MB)
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py:298: The number of training batches (3) is smaller than the logging interval Trainer(log_every_n_steps=50). Set
 a lower value for log_every_n_steps if you want to see logs for the training epoch.
Epoch 0:   0%|
     | 0/3 [00:00<?, ?it/s]before barrier
rank: 3
world size: 4
before barrier
rank: 2
world size: 4
before barrier
rank: 1
world size: 4
before barrier
rank: 0
world size: 4
Rank 0: Barrier completed successfully
Rank 3: Barrier completed successfully
Rank 1: Barrier completed successfully
Rank 2: Barrier completed successfully
after barrier
after barrier
after barrier
after barrier
Epoch 0:  67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                               | 2/3 [00:00<
00:00,  9.67it/s, v_num=34]before barrier epoch end
before barrier epoch end
rank: 2
world size: 4
before barrier epoch end
rank: 1
rank: 3
world size: 4
world size: 4
Epoch 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<
00:00, 14.30it/s, v_num=34]before barrier epoch end
rank: 0
world size: 4
Rank 0: Barrier completed successfully
Rank 3: Barrier completed successfully
Rank 2: Barrier completed successfully
after barrier epoch end
after barrier epoch end
after barrier epoch end
Rank 1: Barrier completed successfully
after barrier epoch end
`Trainer.fit` stopped: `max_epochs=1` reached.
Epoch 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<
00:00, 10.46it/s, v_num=34]
[rank0]:[W901 04:12:19.206514239 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_proce
ss_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint h
as always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
(ReProver) yingzi_ma@compute-permanent-node-834:~/lean_project/ReProver$ python distributed_test.py --timeout 2 --num_gpus 4

/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python distributed_test.py --timeout 2 --num_gpus 4 ...
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python distributed_test.py --timeout 2 --num_gpus 4 ...
You are using a CUDA device ('NVIDIA A100-SXM4-80GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performa
nce. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/distributed_test.py", line 254, in <module>
    main(args)
  File "/data/yingzi_ma/lean_project/ReProver/distributed_test.py", line 246, in main
    trainer.fit(model, train_loader)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 943, in _run
    self.strategy.setup_environment()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 154, in setup_environment
    self.setup_distributed()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 203, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/distributed.py", line 291, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 93, in wrapper
    func_return = func(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1361, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 258, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 185, in _create_c10d_store
    return TCPStore(
torch.distributed.DistStoreError: Timed out after 3 seconds waiting for clients. 1/4 clients joined.
(ReProver) yingzi_ma@compute-permanent-node-834:~/lean_project/ReProver$ Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4

Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
[E901 04:12:41.047916190 socket.cpp:957] [c10d] The client socket has timed out after 2s while trying to connect to (127.0.0.1, 33623).
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/distributed_test.py", line 254, in <module>
    main(args)
  File "/data/yingzi_ma/lean_project/ReProver/distributed_test.py", line 246, in main
    trainer.fit(model, train_loader)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 943, in _run
    self.strategy.setup_environment()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 154, in setup_environment
    self.setup_distributed()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 203, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/distributed.py", line 291, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 93, in wrapper
    func_return = func(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1361, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 258, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 185, in _create_c10d_store
    return TCPStore(
torch.distributed.DistNetworkError: The client socket has timed out after 2s while trying to connect to (127.0.0.1, 33623).
[E901 04:12:41.103128314 socket.cpp:957] [c10d] The client socket has timed out after 2s while trying to connect to (127.0.0.1, 33623).
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/distributed_test.py", line 254, in <module>
    main(args)
  File "/data/yingzi_ma/lean_project/ReProver/distributed_test.py", line 246, in main
    trainer.fit(model, train_loader)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 943, in _run
    self.strategy.setup_environment()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 154, in setup_environment
    self.setup_distributed()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 203, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/distributed.py", line 291, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 93, in wrapper
    func_return = func(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1361, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 258, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 185, in _create_c10d_store
    return TCPStore(
torch.distributed.DistNetworkError: The client socket has timed out after 2s while trying to connect to (127.0.0.1, 33623).
[E901 04:12:41.117705998 socket.cpp:957] [c10d] The client socket has timed out after 2s while trying to connect to (127.0.0.1, 33623).
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/distributed_test.py", line 254, in <module>
    main(args)
  File "/data/yingzi_ma/lean_project/ReProver/distributed_test.py", line 246, in main
    trainer.fit(model, train_loader)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 943, in _run
    self.strategy.setup_environment()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 154, in setup_environment
    self.setup_distributed()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 203, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/distributed.py", line 291, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 93, in wrapper
    func_return = func(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1361, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 258, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 185, in _create_c10d_store
    return TCPStore(
torch.distributed.DistNetworkError: The client socket has timed out after 2s while trying to connect to (127.0.0.1, 33623).
^C
(ReProver) yingzi_ma@compute-permanent-node-834:~/lean_project/ReProver$ python distributed_test.py --timeout 30 --num_gpus 4

/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python distributed_test.py --timeout 30 --num_gpus 4 ...
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python distributed_test.py --timeout 30 --num_gpus 4 ...
You are using a CUDA device ('NVIDIA A100-SXM4-80GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performa
nce. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

NCCL version 2.20.5+cuda12.4
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

  | Name  | Type   | Params
---------------------------------
0 | layer | Linear | 2
---------------------------------
2         Trainable params
0         Non-trainable params
2         Total params
0.000     Total estimated model params size (MB)
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py:298: The number of training batches (3) is smaller than the logging interval Trainer(log_every_n_steps=50). Set
 a lower value for log_every_n_steps if you want to see logs for the training epoch.
Epoch 0:   0%|
     | 0/3 [00:00<?, ?it/s]before barrier
rank: 1
world size: 4
before barrier
rank: 2
world size: 4
before barrier
rank: 3
world size: 4
before barrier
rank: 0
world size: 4
Rank 0: Barrier completed successfully
Rank 3: Barrier completed successfully
Rank 2: Barrier completed successfully
Rank 1: Barrier completed successfully
after barrier
after barrier
after barrier
after barrier
Epoch 0:  67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                               | 2/3 [00:00<
00:00,  8.93it/s, v_num=35]before barrier epoch end
Epoch 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<
00:00, 13.19it/s, v_num=35]before barrier epoch end
rank: 1
world size: 4
rank: 3
world size: 4
Epoch 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<
00:00, 13.15it/s, v_num=35]before barrier epoch end
rank: 0
world size: 4
before barrier epoch end
rank: 2
world size: 4
Rank 1: Barrier completed successfully
Rank 0: Barrier completed successfully
Rank 3: Barrier completed successfully
after barrier epoch end
after barrier epoch end
after barrier epoch end
Rank 2: Barrier completed successfully
after barrier epoch end
`Trainer.fit` stopped: `max_epochs=1` reached.
Epoch 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<
00:00,  9.11it/s, v_num=35]
[rank0]:[W901 04:15:02.397400788 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_proce
ss_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint h
as always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
(ReProver) yingzi_ma@compute-permanent-node-834:~/lean_project/ReProver$ python distributed_test.py --timeout 30 --num_gpus 4
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python distributed_test.py --timeout 30 --num_gpus 4 ...
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python distributed_test.py --timeout 30 --num_gpus 4 ...
You are using a CUDA device ('NVIDIA A100-SXM4-80GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performa
nce. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

NCCL version 2.20.5+cuda12.4
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

  | Name  | Type   | Params
---------------------------------
0 | layer | Linear | 2
---------------------------------
2         Trainable params
0         Non-trainable params
2         Total params
0.000     Total estimated model params size (MB)
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py:298: The number of training batches (3) is smaller than the logging interval Trainer(log_every_n_steps=50). Set
 a lower value for log_every_n_steps if you want to see logs for the training epoch.
Epoch 0:   0%|
     | 0/3 [00:00<?, ?it/s]before barrier
rank: 1
world size: 4
before barrier
rank: 2
world size: 4
before barrier
rank: 3
world size: 4
before barrier
rank: 0
world size: 4
Rank 3: Barrier completed successfully
Rank 0: Barrier completed successfully
Rank 1: Barrier completed successfully
Rank 2: Barrier completed successfully
after barrier
after barrier
after barrier
after barrier
Epoch 0:  67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                               | 2/3 [00:00<
00:00,  9.58it/s, v_num=36]before barrier epoch end
rank: 2
world size: 4
before barrier epoch end
rank: 1
world size: 4
Epoch 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<
00:00, 14.15it/s, v_num=36]before barrier epoch end
rank: 0
world size: 4
before barrier epoch end
rank: 3
world size: 4
Rank 0: Barrier completed successfully
Rank 1: Barrier completed successfully
Rank 3: Barrier completed successfully
Rank 2: Barrier completed successfully
after barrier epoch end
after barrier epoch end
after barrier epoch end
after barrier epoch end
`Trainer.fit` stopped: `max_epochs=1` reached.
Epoch 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<
00:00, 10.39it/s, v_num=36]
[rank0]:[W901 04:15:21.540724099 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_proce
ss_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint h
as always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
(ReProver) yingzi_ma@compute-permanent-node-834:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
[2024-09-01 04:19:47,933] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-01 04:19:51.604 | INFO     | __main__:main:1232 - Running progressive training
2024-09-01 04:19:51.604 | INFO     | __main__:main:1238 - Configuring LeanDojo...
2024-09-01 04:19:51.609 | INFO     | generate_benchmark_lean4:configure_leandojo:317 - Current working directory: /data/yingzi_ma/lean_project/ReProver
2024-09-01 04:19:51.609 | INFO     | __main__:main:1240 - LeanDojo configured
2024-09-01 04:19:53.241 | INFO     | __main__:search_github_repositories:403 - Processing leanprover/lean4
2024-09-01 04:19:53.242 | INFO     | __main__:search_github_repositories:421 - Skipping leanprover/lean4 since it is a known repository
2024-09-01 04:19:53.242 | INFO     | __main__:search_github_repositories:403 - Processing leanprover-community/mathlib3
Cloning https://github.com/leanprover-community/mathlib3.git
Repo name: leanprover-community/mathlib3
2024-09-01 04:19:54.127 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/leanprover-community/mathlib3/65a1391a0106c9204fe45bc73a039f056558cb83/lean-toolchain failed. Retrying..
.
2024-09-01 04:19:55.166 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/leanprover-community/mathlib3/65a1391a0106c9204fe45bc73a039f056558cb83/lean-toolchain failed. Retrying..
.
2024-09-01 04:19:57.205 | INFO     | __main__:search_github_repositories:419 - Failed to clone leanprover-community/mathlib3 because of HTTP Error 404: Not Found
2024-09-01 04:19:57.205 | INFO     | __main__:search_github_repositories:403 - Processing leanprover-community/mathlib4
Cloning https://github.com/leanprover-community/mathlib4.git
Repo name: leanprover-community/mathlib4
2024-09-01 04:19:58.142 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0-rc3
2024-09-01 04:20:13.505 | INFO     | __main__:search_github_repositories:403 - Processing uwdb/Cosette
Cloning https://github.com/uwdb/Cosette.git
Repo name: uwdb/Cosette
2024-09-01 04:20:14.203 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/uwdb/Cosette/c16b48ec7d278c717a9f1da3684f69621b3863f2/lean-toolchain failed. Retrying...
2024-09-01 04:20:15.242 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/uwdb/Cosette/c16b48ec7d278c717a9f1da3684f69621b3863f2/lean-toolchain failed. Retrying...
2024-09-01 04:20:17.283 | INFO     | __main__:search_github_repositories:419 - Failed to clone uwdb/Cosette because of HTTP Error 404: Not Found
2024-09-01 04:20:17.284 | INFO     | __main__:search_github_repositories:403 - Processing AndrasKovacs/smalltt
Cloning https://github.com/AndrasKovacs/smalltt.git
Repo name: AndrasKovacs/smalltt
2024-09-01 04:20:17.999 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/AndrasKovacs/smalltt/b5fc9b3747dcbf8c71ca9f976afb7b574b630996/lean-toolchain failed. Retrying...
2024-09-01 04:20:19.039 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/AndrasKovacs/smalltt/b5fc9b3747dcbf8c71ca9f976afb7b574b630996/lean-toolchain failed. Retrying...
2024-09-01 04:20:21.079 | INFO     | __main__:search_github_repositories:419 - Failed to clone AndrasKovacs/smalltt because of HTTP Error 404: Not Found
2024-09-01 04:20:21.080 | INFO     | __main__:search_github_repositories:403 - Processing dselsam/certigrad
Cloning https://github.com/dselsam/certigrad.git
Repo name: dselsam/certigrad
2024-09-01 04:20:21.773 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/dselsam/certigrad/c9a06e93f1ec58196d6d3b8563b29868d916727f/lean-toolchain failed. Retrying...
2024-09-01 04:20:22.813 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/dselsam/certigrad/c9a06e93f1ec58196d6d3b8563b29868d916727f/lean-toolchain failed. Retrying...
2024-09-01 04:20:24.853 | INFO     | __main__:search_github_repositories:419 - Failed to clone dselsam/certigrad because of HTTP Error 404: Not Found
2024-09-01 04:20:24.854 | INFO     | __main__:search_github_repositories:403 - Processing Kha/electrolysis
Cloning https://github.com/Kha/electrolysis.git
Repo name: Kha/electrolysis
2024-09-01 04:20:25.671 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/Kha/electrolysis/bd4655d91ca65856fb8373637ce3e7b17ee3a190/lean-toolchain failed. Retrying...
2024-09-01 04:20:26.711 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/Kha/electrolysis/bd4655d91ca65856fb8373637ce3e7b17ee3a190/lean-toolchain failed. Retrying...
2024-09-01 04:20:28.750 | INFO     | __main__:search_github_repositories:419 - Failed to clone Kha/electrolysis because of HTTP Error 404: Not Found
2024-09-01 04:20:28.751 | INFO     | __main__:search_github_repositories:403 - Processing ImperialCollegeLondon/formalising-mathematics
Cloning https://github.com/ImperialCollegeLondon/formalising-mathematics.git
Repo name: ImperialCollegeLondon/formalising-mathematics
2024-09-01 04:20:29.476 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/ImperialCollegeLondon/formalising-mathematics/d81ad67e36774eb68f242bcc1b88d33dacfd87bf/lean-toolchain fa
iled. Retrying...
2024-09-01 04:20:30.514 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/ImperialCollegeLondon/formalising-mathematics/d81ad67e36774eb68f242bcc1b88d33dacfd87bf/lean-toolchain fa
iled. Retrying...
2024-09-01 04:20:32.553 | INFO     | __main__:search_github_repositories:419 - Failed to clone ImperialCollegeLondon/formalising-mathematics because of HTTP Error 404: Not Found
2024-09-01 04:20:32.554 | INFO     | __main__:search_github_repositories:403 - Processing lecopivo/SciLean
Cloning https://github.com/lecopivo/SciLean.git
Repo name: lecopivo/SciLean
2024-09-01 04:20:33.272 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0-rc2
Found 2 repositories
Using lambda = 0.1
Processing /data/yingzi_ma/lean_project/repos_new/leanprover-community/mathlib4
2024-09-01 04:20:48.661 | INFO     | __main__:retrieve_proof:1047 - Processing https://github.com/leanprover-community/mathlib4.git
2024-09-01 04:20:48.661 | INFO     | __main__:retrieve_proof:1063 - Found compatible commit 2b29e73438e240a427bcecc7c0fe19306beb1310 for https://github.com/leanprover-community/mathlib4.git
2024-09-01 04:20:48.661 | INFO     | __main__:retrieve_proof:1064 - Lean version: v4.8.0
2024-09-01 04:20:48.900 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.8.0
2024-09-01 04:21:04.158 | INFO     | __main__:retrieve_proof:1069 - Generating benchmark at /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
2024-09-01 04:21:04.158 | INFO     | generate_benchmark_lean4:main:324 - Generating dataset to go into /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
2024-09-01 04:21:04.158 | INFO     | generate_benchmark_lean4:main:331 - lean toolchain version: {'content': 'leanprover/lean4:v4.8.0\n'}
2024-09-01 04:21:04.158 | INFO     | generate_benchmark_lean4:main:333 - lean version v: v4.8.0
2024-09-01 04:21:04.158 | INFO     | generate_benchmark_lean4:main:334 - is supported: True
2024-09-01 04:21:04.158 | INFO     | generate_benchmark_lean4:main:344 - lean path1 /data/yingzi_ma/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 04:21:04.158 | INFO     | generate_benchmark_lean4:main:345 - lean path2 /.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 04:21:04.158 | INFO     | generate_benchmark_lean4:main:346 - lean path3 ~/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 04:21:04.160 | INFO     | generate_benchmark_lean4:main:350 - Lean toolchain path 2 does not exist: /.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 04:21:04.160 | INFO     | generate_benchmark_lean4:main:352 - Lean toolchain path 3 does not exist: ~/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 04:21:04.160 | INFO     | generate_benchmark_lean4:main:355 - Switched to Lean toolchain at: /data/yingzi_ma/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 04:21:04.258 | INFO     | generate_benchmark_lean4:main:357 - lean --version: Lean (version 4.8.0, x86_64-unknown-linux-gnu, commit df668f00e6c0, Release)

2024-09-01 04:21:04.258 | INFO     | generate_benchmark_lean4:main:358 - repo: LeanGitRepo(url='https://github.com/leanprover-community/mathlib4', commit='2b29e73438e240a427bcecc7c0fe19306beb1310')
2024-09-01 04:21:04.258 | INFO     | generate_benchmark_lean4:main:360 - Configuring LeanDojo again...
2024-09-01 04:21:04.266 | INFO     | generate_benchmark_lean4:configure_leandojo:317 - Current working directory: /data/yingzi_ma/lean_project/ReProver
2024-09-01 04:21:04.266 | INFO     | generate_benchmark_lean4:main:362 - LeanDojo configured
2024-09-01 04:21:04.266 | INFO     | generate_benchmark_lean4:main:365 - Tracing the repo...
2024-09-01 04:21:04.269 | DEBUG    | lean_dojo.data_extraction.trace:get_traced_repo_path:87 - The traced repo is available in the cache.
2024-09-01 04:21:04.269 | INFO     | lean_dojo.data_extraction.trace:trace:116 - Loading the traced repo from /data/yingzi_ma/lean_project/.cache/lean_dojo/leanprover-community-mathlib4-2b29e73438e240a427bcecc7c0fe193
06beb1310/mathlib4
2024-09-01 04:21:07.674 | DEBUG    | lean_dojo.data_extraction.traced_data:load_from_disk:1123 - Loading 5514 traced XML files from /data/yingzi_ma/lean_project/.cache/lean_dojo/leanprover-community-mathlib4-2b29e7343
8e240a427bcecc7c0fe19306beb1310/mathlib4 with 31 workers
 37%|███████████████████████████████████████▍                                                 37%|███████████████████████████████████████▌                                                                  | 2055/5514 [
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 5514/5514 [15:59<00:00,  5.75it/s]
2024-09-01 04:37:06.730 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/mathlib4', commit='2b29e73438e240a427bce
cc7c0fe19306beb1310')
2024-09-01 04:37:08.134 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.6.0-rc1
2024-09-01 04:37:24.605 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.8.0-rc1
2024-09-01 04:37:40.454 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.7.0
2024-09-01 04:37:56.037 | DEBUG    | lean_dojo.data_extraction.lean:url_to_repo:70 - url_to_repo("https://github.com/leanprover-community/import-graph.git") failed. Retrying...
2024-09-01 04:37:57.178 | DEBUG    | lean_dojo.data_extraction.lean:url_to_repo:70 - url_to_repo("https://github.com/leanprover-community/import-graph.git") failed. Retrying...
2024-09-01 04:37:59.847 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for doc-gen4 main
2024-09-01 04:38:00.455 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for batteries main
2024-09-01 04:38:10.137 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for quote4 master
2024-09-01 04:38:10.529 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.10.0
2024-09-01 04:38:26.046 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for aesop master
2024-09-01 04:38:27.126 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0-rc1
2024-09-01 04:38:42.520 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for ProofWidgets4 v0.0.36
2024-09-01 04:38:43.359 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4-cli main
2024-09-01 04:38:43.993 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.9.0
2024-09-01 04:38:59.833 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for import-graph main
2024-09-01 04:39:00.459 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover/doc-gen4', commit='83f718b9055972dce4f92f5b3917426
b91a0d2fe')
2024-09-01 04:39:01.043 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.9.0-rc1
Following Github server redirection from /repos/mhuisi/lean4-cli to /repositories/341363356
2024-09-01 04:39:18.112 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4-nightly nightly-2024-06-05
2024-09-01 04:39:19.640 | WARNING  | lean_dojo.data_extraction.lean:__post_init__:446 - LeanGitRepo(url='https://github.com/mhuisi/lean4-cli', commit='bf066c328bcff19aa93adf4d24c4e896c0d4eaca') relies on an unsupporte
d Lean version: fbb3055f82ff9a4bc82f6722f6e73225617342fd
2024-09-01 04:39:19.640 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/batteries', commit='a7fd140a94bbbfa40cf1
0839227bbb9e8492be2d')
2024-09-01 04:39:19.850 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/quote4', commit='d38fb94558af9957b8f479e
350841ce65a1ec42c')
2024-09-01 04:39:20.038 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/aesop', commit='6c89b6765913a0d727c10664
93c3f5dc51c9713e')
2024-09-01 04:39:20.498 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/ProofWidgets4', commit='e6b6247c61280c77
ade6bbf0bc3c66a44fe2e0c5')
2024-09-01 04:39:20.976 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover/lean4-cli', commit='2cf1030dc2ae6b3632c84a09350b67
5ef3e347d0')
2024-09-01 04:39:21.170 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/import-graph', commit='0a756018b736ef4f4
bc3c9a45fc03cf97a0b1a0c')
2024-09-01 04:39:53.598 | DEBUG    | lean_dojo.data_extraction.traced_data:check_sanity:1009 - Checking the sanity of TracedRepo(repo=LeanGitRepo(url='https://github.com/leanprover-community/mathlib4', commit='2b29e73
438e240a427bcecc7c0fe19306beb1310'), dependencies={'lean4': LeanGitRepo(url='https://github.com/leanprover/lean4', commit='daa22187642d4cf6954c39a23eab20d8a8675416'), 'batteries': LeanGitRepo(url='https://github.com/l
eanprover-community/batteries', commit='021e272cb5cdcc82b7e1e760fe915ff2f64169ad'), 'Qq': LeanGitRepo(url='https://github.com/leanprover-community/quote4', commit='53156671405fbbd5402ed17a79bd129b961bd8d6'), 'aesop':
LeanGitRepo(url='https://github.com/leanprover-community/aesop', commit='53ba96ad7666d4a2515292974631629b5ea5dfee'), 'proofwidgets': LeanGitRepo(url='https://github.com/leanprover-community/ProofWidgets4', commit='e6b
6247c61280c77ade6bbf0bc3c66a44fe2e0c5'), 'Cli': LeanGitRepo(url='https://github.com/leanprover/lean4-cli', commit='2cf1030dc2ae6b3632c84a09350b675ef3e347d0'), '«doc-gen4»': LeanGitRepo(url='https://github.com/leanprov
er/doc-gen4', commit='83f718b9055972dce4f92f5b3917426b91a0d2fe'), 'MD4Lean': LeanGitRepo(url='https://github.com/acmepjz/md4lean', commit='5e95f4776be5e048364f325c7e9d619bb56fb005'), 'UnicodeBasic': LeanGitRepo(url='h
ttps://github.com/fgdorais/lean4-unicode-basic', commit='9447739fe9714f8a091192bad5cd5e7b5a8ae1e4'), 'BibtexQuery': LeanGitRepo(url='https://github.com/dupuisf/BibtexQuery', commit='c138ab5c566c4268798b24bfcbea2f4c424
13cdd'), 'importGraph': LeanGitRepo(url='https://github.com/leanprover-community/import-graph', commit='0a756018b736ef4f4bc3c9a45fc03cf97a0b1a0c')}, root_dir=PosixPath('/data/yingzi_ma/lean_project/.cache/lean_dojo/le
anprover-community-mathlib4-2b29e73438e240a427bcecc7c0fe19306beb1310/mathlib4'))
2024-09-01 04:40:17.562 | INFO     | generate_benchmark_lean4:main:367 - Successfully traced the repo
2024-09-01 04:40:17.563 | WARNING  | generate_benchmark_lean4:main:372 - /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310 already exists. Using it instead.
2024-09-01 04:40:17.563 | INFO     | __main__:retrieve_proof:1077 - Finished generating benchmark at /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
2024-09-01 04:40:34.047 | INFO     | dynamic_database:add_repository:583 - Attempting to add repository: https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 04:40:34.047 | INFO     | dynamic_database:add_repository:586 - Added new repository: https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2421/2421 [00:00<00:00, 35098.72it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 116251/116251 [01:44<00:00, 1110.44it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2421/2421 [00:00<00:00, 35819.79it/s]
2024-09-01 04:42:24.891 | INFO     | __main__:retrieve_proof:1115 - Before adding new repo:
2024-09-01 04:42:24.891 | INFO     | dynamic_database:print_database_contents:607 - Current database contents:
2024-09-01 04:42:24.891 | INFO     | dynamic_database:print_database_contents:609 -   - https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 04:42:24.891 | INFO     | dynamic_database:add_repository:583 - Attempting to add repository: https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 04:42:24.891 | INFO     | dynamic_database:add_repository:588 - Repository 'https://github.com/leanprover-community/mathlib4' with commit '2b29e73438e240a427bcecc7c0fe19306beb1310' already exists in the dat
abase.
2024-09-01 04:42:24.891 | INFO     | __main__:retrieve_proof:1118 - After adding new repo:
2024-09-01 04:42:24.892 | INFO     | dynamic_database:print_database_contents:607 - Current database contents:
2024-09-01 04:42:24.892 | INFO     | dynamic_database:print_database_contents:609 -   - https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 04:42:45.787 | INFO     | __main__:retrieve_proof:1127 - Adding repo to repos_for_merged_dataset
2024-09-01 04:42:45.789 | INFO     | dynamic_database:generate_merged_dataset:399 - Merging selected repositories in the database:
2024-09-01 04:42:45.789 | INFO     | dynamic_database:generate_merged_dataset:401 -   - https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 04:46:21.919 | WARNING  | dynamic_database:generate_merged_dataset:418 - /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310 already ex
ists. Removing it now.
2024-09-01 04:46:56.860 | INFO     | dynamic_database:generate_merged_dataset:422 - Exported proofs to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe1930
6beb1310
2024-09-01 04:46:57.813 | INFO     | dynamic_database:generate_merged_dataset:425 - Merged and exported corpus to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bce
cc7c0fe19306beb1310
2024-09-01 04:46:57.835 | INFO     | dynamic_database:generate_merged_dataset:428 - Exported traced files to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0
fe19306beb1310
2024-09-01 04:46:57.838 | INFO     | dynamic_database:generate_merged_dataset:431 - Exported metadata to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19
306beb1310
2024-09-01 04:46:57.870 | INFO     | __main__:find_latest_checkpoint:486 - Using the latest checkpoint: /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe
19306beb1310_lambda_0.1_epoch=0-Recall@10_val=58.95.ckpt
2024-09-01 04:46:57.870 | INFO     | __main__:retrieve_proof:1139 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb131
0_lambda_0.1_epoch=0-Recall@10_val=58.95.ckpt
2024-09-01 04:46:57.870 | INFO     | __main__:train_test_fisher:626 - Inside train_test_fisher
2024-09-01 04:46:57.870 | INFO     | __main__:train_test_fisher:627 - Starting training at epoch 0
[rank: 0] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default
 pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more
details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be load
ed via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of
the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/utilities/migration/utils.py:56: The loaded checkpoint was produced with Lightning v2.4.0, which is newer than your current Light
ning version: v2.2.4
2024-09-01 04:47:02.651 | INFO     | __main__:train_test_fisher:651 - Loaded premise retriever at /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306b
eb1310_lambda_0.1_epoch=0-Recall@10_val=58.95.ckpt and reset epoch count
2024-09-01 04:47:02.655 | INFO     | __main__:find_latest_fisher:496 - Using the latest Fisher Information Matrix: /data/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/mathlib4_29dcec074de168ac2bf835a77ef68bbe069194
c5_fisher_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickl
e module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more detail
s). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via
 this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the lo
aded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(io.BytesIO(b))
2024-09-01 04:47:03.485 | INFO     | __main__:load_fisher_information:473 - Fisher Information successfully loaded.
2024-09-01 04:47:03.485 | INFO     | retrieval.model:set_fisher_info:62 - Fisher Information has been updated in the model.
2024-09-01 04:47:03.485 | INFO     | __main__:train_test_fisher:657 - Fisher Information Matrix loaded.
Data path: /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This
behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-01 04:47:03.594 | INFO     | common:__init__:208 - Building the corpus from /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310/corpus.jso
nl
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 116251/116251 [00:27<00:00, 4266.25it/s]
2024-09-01 04:48:02.581 | INFO     | retrieval.datamodule:load_or_cache_data:61 - Saved loaded data to cache /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0
fe19306beb1310/random/cache_train/cached_data.pkl
Training dataset size: 359583
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2421/2421 [00:00<00:00, 4413.46it/s]
2024-09-01 04:48:03.270 | INFO     | retrieval.datamodule:load_or_cache_data:61 - Saved loaded data to cache /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0
fe19306beb1310/random/cache_val/cached_data.pkl
Validation dataset size: 4874
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2421/2421 [00:00<00:00, 4547.23it/s]
2024-09-01 04:48:03.935 | INFO     | retrieval.datamodule:load_or_cache_data:61 - Saved loaded data to cache /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0
fe19306beb1310/random/cache_pred/cached_data.pkl
Testing dataset size: 4922
Training dataset size after load: 359583
Validation dataset size after load: 4874
Testing dataset size after load: 4922
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python /data/yingzi_ma/lean_project/ReProver/main.py ...
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
2024-09-01 04:48:04.017 | INFO     | __main__:train_test_fisher:730 - Starting progressive training from epoch 0 to 1
2024-09-01 04:48:04.017 | INFO     | __main__:train_test_fisher:744 - Finished progressive training at epoch 0
2024-09-01 04:48:04.018 | WARNING  | __main__:train_test_fisher:754 - No best model found. Using the last trained model.
2024-09-01 04:48:04.019 | INFO     | __main__:train_test_fisher:760 - Testing...
2024-09-01 04:48:04.021 | INFO     | retrieval.main:run_cli:55 - PID: 1562395
[rank: 0] Seed set to 3407
2024-09-01 04:48:04.283 | INFO     | retrieval.main:before_instantiate_classes:28 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
/random
2024-09-01 04:48:04.283 | INFO     | retrieval.main:before_instantiate_classes:29 - Corpus path: /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb13
10/corpus.jsonl
2024-09-01 04:48:04.841 | INFO     | common:__init__:208 - Building the corpus from /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310/corpus.jso
nl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python main.py predict --config retrieval/confs/cli_lean4_r ...
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[rank: 0] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
[2024-09-01 04:48:39,715] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-01 04:48:39,715] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-01 04:48:39,715] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-01 04:48:42.899 | INFO     | __main__:main:1232 - Running progressive training
2024-09-01 04:48:42.899 | INFO     | __main__:main:1232 - Running progressive training
2024-09-01 04:48:42.899 | INFO     | __main__:main:1232 - Running progressive training
2024-09-01 04:48:42.899 | INFO     | __main__:main:1238 - Configuring LeanDojo...
2024-09-01 04:48:42.899 | INFO     | __main__:main:1238 - Configuring LeanDojo...
2024-09-01 04:48:42.899 | INFO     | __main__:main:1238 - Configuring LeanDojo...
2024-09-01 04:48:42.903 | INFO     | generate_benchmark_lean4:configure_leandojo:317 - Current working directory: /data/yingzi_ma/lean_project/ReProver
2024-09-01 04:48:42.903 | INFO     | generate_benchmark_lean4:configure_leandojo:317 - Current working directory: /data/yingzi_ma/lean_project/ReProver
2024-09-01 04:48:42.903 | INFO     | generate_benchmark_lean4:configure_leandojo:317 - Current working directory: /data/yingzi_ma/lean_project/ReProver
2024-09-01 04:48:42.903 | INFO     | __main__:main:1240 - LeanDojo configured
2024-09-01 04:48:42.904 | INFO     | __main__:main:1240 - LeanDojo configured
2024-09-01 04:48:42.904 | INFO     | __main__:main:1240 - LeanDojo configured
2024-09-01 04:48:43.043 | INFO     | __main__:search_github_repositories:423 - Failed to search GitHub
Found 2 repositories
Using lambda = 0.1
2024-09-01 04:48:43.044 | INFO     | __main__:main:1273 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1248, in main
    repo = repos[i]
IndexError: list index out of range
2024-09-01 04:48:43.048 | INFO     | __main__:search_github_repositories:423 - Failed to search GitHub
Found 2 repositories
Using lambda = 0.1
2024-09-01 04:48:43.048 | INFO     | __main__:main:1273 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1248, in main
    repo = repos[i]
IndexError: list index out of range
2024-09-01 04:48:43.054 | INFO     | __main__:search_github_repositories:423 - Failed to search GitHub
Found 2 repositories
Using lambda = 0.1
2024-09-01 04:48:43.054 | INFO     | __main__:main:1273 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1248, in main
    repo = repos[i]
IndexError: list index out of range
^Z
[12]+  Stopped                 bash run_code.sh
(ReProver) yingzi_ma@compute-permanent-node-834:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
[2024-09-01 04:54:32,978] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-01 04:54:36.088 | INFO     | __main__:main:1232 - Running progressive training
2024-09-01 04:54:36.088 | INFO     | __main__:main:1238 - Configuring LeanDojo...
2024-09-01 04:54:36.093 | INFO     | generate_benchmark_lean4:configure_leandojo:317 - Current working directory: /data/yingzi_ma/lean_project/ReProver
2024-09-01 04:54:36.093 | INFO     | __main__:main:1240 - LeanDojo configured
2024-09-01 04:54:36.241 | INFO     | __main__:search_github_repositories:423 - Failed to search GitHub
Found 2 repositories
Using lambda = 0.1
2024-09-01 04:54:36.242 | INFO     | __main__:main:1273 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1248, in main
    repo = repos[i]
IndexError: list index out of range
(ReProver) yingzi_ma@compute-permanent-node-834:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
[2024-09-01 05:11:31,996] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-01 05:11:35.127 | INFO     | __main__:main:1233 - Running progressive training
2024-09-01 05:11:35.128 | INFO     | __main__:main:1239 - Configuring LeanDojo...
2024-09-01 05:11:35.132 | INFO     | generate_benchmark_lean4:configure_leandojo:317 - Current working directory: /data/yingzi_ma/lean_project/ReProver
2024-09-01 05:11:35.132 | INFO     | __main__:main:1241 - LeanDojo configured
> /data/yingzi_ma/lean_project/ReProver/main.py(387)search_github_repositories()
    386     import ipdb; ipdb.set_trace()
--> 387     """Search for the given number of repositories on GitHub that have the given language."""
    388     headers = {'Authorization': personal_access_token}

ipdb> c
2024-09-01 05:11:39.393 | INFO     | __main__:search_github_repositories:404 - Processing leanprover/lean4
2024-09-01 05:11:39.393 | INFO     | __main__:search_github_repositories:422 - Skipping leanprover/lean4 since it is a known repository
2024-09-01 05:11:39.393 | INFO     | __main__:search_github_repositories:404 - Processing leanprover-community/mathlib3
Cloning https://github.com/leanprover-community/mathlib3.git
Repo name: leanprover-community/mathlib3
2024-09-01 05:11:40.647 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/leanprover-community/mathlib3/65a1391a0106c9204fe45bc73a039f056558cb83/lean-toolchain failed. Retrying..
.
2024-09-01 05:11:41.687 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/leanprover-community/mathlib3/65a1391a0106c9204fe45bc73a039f056558cb83/lean-toolchain failed. Retrying..
.
2024-09-01 05:11:43.727 | INFO     | __main__:search_github_repositories:420 - Failed to clone leanprover-community/mathlib3 because of HTTP Error 404: Not Found
2024-09-01 05:11:43.728 | INFO     | __main__:search_github_repositories:404 - Processing leanprover-community/mathlib4
Cloning https://github.com/leanprover-community/mathlib4.git
Repo name: leanprover-community/mathlib4
2024-09-01 05:11:45.078 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0-rc3
2024-09-01 05:12:00.220 | INFO     | __main__:search_github_repositories:404 - Processing uwdb/Cosette
Cloning https://github.com/uwdb/Cosette.git
Repo name: uwdb/Cosette
2024-09-01 05:12:00.980 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/uwdb/Cosette/c16b48ec7d278c717a9f1da3684f69621b3863f2/lean-toolchain failed. Retrying...
2024-09-01 05:12:02.019 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/uwdb/Cosette/c16b48ec7d278c717a9f1da3684f69621b3863f2/lean-toolchain failed. Retrying...
2024-09-01 05:12:04.060 | INFO     | __main__:search_github_repositories:420 - Failed to clone uwdb/Cosette because of HTTP Error 404: Not Found
2024-09-01 05:12:04.062 | INFO     | __main__:search_github_repositories:404 - Processing AndrasKovacs/smalltt
Cloning https://github.com/AndrasKovacs/smalltt.git
Repo name: AndrasKovacs/smalltt
2024-09-01 05:12:04.777 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/AndrasKovacs/smalltt/b5fc9b3747dcbf8c71ca9f976afb7b574b630996/lean-toolchain failed. Retrying...
2024-09-01 05:12:05.817 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/AndrasKovacs/smalltt/b5fc9b3747dcbf8c71ca9f976afb7b574b630996/lean-toolchain failed. Retrying...
2024-09-01 05:12:07.858 | INFO     | __main__:search_github_repositories:420 - Failed to clone AndrasKovacs/smalltt because of HTTP Error 404: Not Found
2024-09-01 05:12:07.860 | INFO     | __main__:search_github_repositories:404 - Processing dselsam/certigrad
Cloning https://github.com/dselsam/certigrad.git
Repo name: dselsam/certigrad
2024-09-01 05:12:08.600 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/dselsam/certigrad/c9a06e93f1ec58196d6d3b8563b29868d916727f/lean-toolchain failed. Retrying...
2024-09-01 05:12:09.640 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/dselsam/certigrad/c9a06e93f1ec58196d6d3b8563b29868d916727f/lean-toolchain failed. Retrying...
2024-09-01 05:12:11.680 | INFO     | __main__:search_github_repositories:420 - Failed to clone dselsam/certigrad because of HTTP Error 404: Not Found
2024-09-01 05:12:11.681 | INFO     | __main__:search_github_repositories:404 - Processing Kha/electrolysis
Cloning https://github.com/Kha/electrolysis.git
Repo name: Kha/electrolysis
2024-09-01 05:12:12.386 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/Kha/electrolysis/bd4655d91ca65856fb8373637ce3e7b17ee3a190/lean-toolchain failed. Retrying...
2024-09-01 05:12:13.425 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/Kha/electrolysis/bd4655d91ca65856fb8373637ce3e7b17ee3a190/lean-toolchain failed. Retrying...
2024-09-01 05:12:15.466 | INFO     | __main__:search_github_repositories:420 - Failed to clone Kha/electrolysis because of HTTP Error 404: Not Found
2024-09-01 05:12:15.468 | INFO     | __main__:search_github_repositories:404 - Processing ImperialCollegeLondon/formalising-mathematics
Cloning https://github.com/ImperialCollegeLondon/formalising-mathematics.git
Repo name: ImperialCollegeLondon/formalising-mathematics
2024-09-01 05:12:16.268 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/ImperialCollegeLondon/formalising-mathematics/d81ad67e36774eb68f242bcc1b88d33dacfd87bf/lean-toolchain fa
iled. Retrying...
2024-09-01 05:12:17.308 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/ImperialCollegeLondon/formalising-mathematics/d81ad67e36774eb68f242bcc1b88d33dacfd87bf/lean-toolchain fa
iled. Retrying...
2024-09-01 05:12:19.348 | INFO     | __main__:search_github_repositories:420 - Failed to clone ImperialCollegeLondon/formalising-mathematics because of HTTP Error 404: Not Found
2024-09-01 05:12:19.349 | INFO     | __main__:search_github_repositories:404 - Processing lecopivo/SciLean
Cloning https://github.com/lecopivo/SciLean.git
Repo name: lecopivo/SciLean
2024-09-01 05:12:20.086 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0-rc2
Found 2 repositories
Using lambda = 0.1
Processing /data/yingzi_ma/lean_project/repos_new/leanprover-community/mathlib4
2024-09-01 05:12:35.340 | INFO     | __main__:retrieve_proof:1048 - Processing https://github.com/leanprover-community/mathlib4.git
2024-09-01 05:12:35.340 | INFO     | __main__:retrieve_proof:1064 - Found compatible commit 2b29e73438e240a427bcecc7c0fe19306beb1310 for https://github.com/leanprover-community/mathlib4.git
2024-09-01 05:12:35.340 | INFO     | __main__:retrieve_proof:1065 - Lean version: v4.8.0
2024-09-01 05:12:35.630 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.8.0
2024-09-01 05:12:50.870 | INFO     | __main__:retrieve_proof:1070 - Generating benchmark at /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
2024-09-01 05:12:50.871 | INFO     | generate_benchmark_lean4:main:324 - Generating dataset to go into /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
2024-09-01 05:12:50.871 | INFO     | generate_benchmark_lean4:main:331 - lean toolchain version: {'content': 'leanprover/lean4:v4.8.0\n'}
2024-09-01 05:12:50.871 | INFO     | generate_benchmark_lean4:main:333 - lean version v: v4.8.0
2024-09-01 05:12:50.871 | INFO     | generate_benchmark_lean4:main:334 - is supported: True
2024-09-01 05:12:50.871 | INFO     | generate_benchmark_lean4:main:344 - lean path1 /data/yingzi_ma/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:12:50.871 | INFO     | generate_benchmark_lean4:main:345 - lean path2 /.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:12:50.871 | INFO     | generate_benchmark_lean4:main:346 - lean path3 ~/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:12:50.873 | INFO     | generate_benchmark_lean4:main:350 - Lean toolchain path 2 does not exist: /.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:12:50.873 | INFO     | generate_benchmark_lean4:main:352 - Lean toolchain path 3 does not exist: ~/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:12:50.873 | INFO     | generate_benchmark_lean4:main:355 - Switched to Lean toolchain at: /data/yingzi_ma/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:12:50.927 | INFO     | generate_benchmark_lean4:main:357 - lean --version: Lean (version 4.8.0, x86_64-unknown-linux-gnu, commit df668f00e6c0, Release)

2024-09-01 05:12:50.927 | INFO     | generate_benchmark_lean4:main:358 - repo: LeanGitRepo(url='https://github.com/leanprover-community/mathlib4', commit='2b29e73438e240a427bcecc7c0fe19306beb1310')
2024-09-01 05:12:50.927 | INFO     | generate_benchmark_lean4:main:360 - Configuring LeanDojo again...
2024-09-01 05:12:50.934 | INFO     | generate_benchmark_lean4:configure_leandojo:317 - Current working directory: /data/yingzi_ma/lean_project/ReProver
2024-09-01 05:12:50.934 | INFO     | generate_benchmark_lean4:main:362 - LeanDojo configured
2024-09-01 05:12:50.934 | INFO     | generate_benchmark_lean4:main:365 - Tracing the repo...
2024-09-01 05:12:50.937 | DEBUG    | lean_dojo.data_extraction.trace:get_traced_repo_path:87 - The traced repo is available in the cache.
2024-09-01 05:12:50.937 | INFO     | lean_dojo.data_extraction.trace:trace:116 - Loading the traced repo from /data/yingzi_ma/lean_project/.cache/lean_dojo/leanprover-community-mathlib4-2b29e73438e240a427bcecc7c0fe193
06beb1310/mathlib4
2024-09-01 05:12:53.204 | DEBUG    | lean_dojo.data_extraction.traced_data:load_from_disk:1123 - Loading 5514 traced XML files from /data/yingzi_ma/lean_project/.cache/lean_dojo/leanprover-community-mathlib4-2b29e7343
8e240a427bcecc7c0fe19306beb1310/mathlib4 with 31 workers
  6%|███████████                                                                                                                                                                      | 346/5514 [01:11<12:54,  6.67it/s]
 41%|████████████████████████████████████████████████████████████████████████▋                                                               41%|████████████████████████████████████████████████████████████████████████
▊                                          41%|████████████████████████████████████████████████████████████████████████▊                                          41%|███████████████████████████████████████████████████
█████████████████████▉                                          41%|████████████████████████████████████████████████████████████████████████▉                                          42%|██████████████████████████████
███████████████████████████████████████████                                          42%|█████████████████████████████████████████████████████████████████████████▏                                         42%|█████████
████████████████████████████████████████████████████████████████▎                                         42%|█████████████████████████████████████████████████████████████████████████▎
        42%|█████████████████████████████████████████████████████████████████████████▍                                         42%|█████████████████████████████████████████████████████████████████████████▌
                             42%|█████████████████████████████████████████████████████████████████████████▌                                         42%|█████████████████████████████████████████████████████████████████
████████▋                                         42%|█████████████████████████████████████████████████████████████████████████▋                                         42%|████████████████████████████████████████████
█████████████████████████████▊                                         42%|█████████████████████████████████████████████████████████████████████████▊                                         42%|███████████████████████
██████████████████████████████████████████████████▉                                         42%|█████████████████████████████████████████████████████████████████████████▉                                         42%|██
████████████████████████████████████████████████████████████████████████                                         42%|██████████████████████████████████████████████████████████████████████████
               42%|██████████████████████████████████████████████████████████████████████████▏                                        42%|██████████████████████████████████████████████████████████████████████████▏
                                    42%|██████████████████████████████████████████████████████████████████████████▎                                        42%|██████████████████████████████████████████████████████████
████████████████▍                                        42%|██████████████████████████████████████████████████████████████████████████▌                                        42%|█████████████████████████████████████
█████████████████████████████████████▌                                        42%|██████████████████████████████████████████████████████████████████████████▋                                        42%|████████████████
██████████████████████████████████████████████████████████▋                                        42%|██████████████████████████████████████████████████████████████████████████▋
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5514/5514 [17:27<00:00,  5.27it/s]
2024-09-01 05:30:20.337 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/mathlib4', commit='2b29e73438e240a427bce
cc7c0fe19306beb1310')
2024-09-01 05:30:21.765 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.6.0-rc1
2024-09-01 05:30:38.215 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.8.0-rc1
2024-09-01 05:30:54.162 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.7.0
2024-09-01 05:31:09.996 | DEBUG    | lean_dojo.data_extraction.lean:url_to_repo:70 - url_to_repo("https://github.com/leanprover-community/import-graph.git") failed. Retrying...
2024-09-01 05:31:11.109 | DEBUG    | lean_dojo.data_extraction.lean:url_to_repo:70 - url_to_repo("https://github.com/leanprover-community/import-graph.git") failed. Retrying...
2024-09-01 05:31:13.681 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for doc-gen4 main
2024-09-01 05:31:14.304 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for batteries main
2024-09-01 05:31:23.840 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for quote4 master
2024-09-01 05:31:24.269 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.10.0
2024-09-01 05:31:40.663 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for aesop master
2024-09-01 05:31:41.683 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0-rc1
2024-09-01 05:31:56.974 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for ProofWidgets4 v0.0.36
2024-09-01 05:31:57.777 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4-cli main
2024-09-01 05:31:58.446 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.9.0
2024-09-01 05:32:14.029 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for import-graph main
2024-09-01 05:32:14.648 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover/doc-gen4', commit='83f718b9055972dce4f92f5b3917426
b91a0d2fe')
2024-09-01 05:32:15.176 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.9.0-rc1
Following Github server redirection from /repos/mhuisi/lean4-cli to /repositories/341363356
2024-09-01 05:32:32.053 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4-nightly nightly-2024-06-05
2024-09-01 05:32:33.456 | WARNING  | lean_dojo.data_extraction.lean:__post_init__:446 - LeanGitRepo(url='https://github.com/mhuisi/lean4-cli', commit='bf066c328bcff19aa93adf4d24c4e896c0d4eaca') relies on an unsupporte
d Lean version: fbb3055f82ff9a4bc82f6722f6e73225617342fd
2024-09-01 05:32:33.457 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/batteries', commit='a7fd140a94bbbfa40cf1
0839227bbb9e8492be2d')
2024-09-01 05:32:33.676 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/quote4', commit='d38fb94558af9957b8f479e
350841ce65a1ec42c')
2024-09-01 05:32:33.867 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/aesop', commit='6c89b6765913a0d727c10664
93c3f5dc51c9713e')
2024-09-01 05:32:34.283 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/ProofWidgets4', commit='e6b6247c61280c77
ade6bbf0bc3c66a44fe2e0c5')
2024-09-01 05:32:34.678 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover/lean4-cli', commit='2cf1030dc2ae6b3632c84a09350b67
5ef3e347d0')
2024-09-01 05:32:34.935 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/import-graph', commit='0a756018b736ef4f4
bc3c9a45fc03cf97a0b1a0c')
2024-09-01 05:33:08.546 | DEBUG    | lean_dojo.data_extraction.traced_data:check_sanity:1009 - Checking the sanity of TracedRepo(repo=LeanGitRepo(url='https://github.com/leanprover-community/mathlib4', commit='2b29e73
438e240a427bcecc7c0fe19306beb1310'), dependencies={'lean4': LeanGitRepo(url='https://github.com/leanprover/lean4', commit='daa22187642d4cf6954c39a23eab20d8a8675416'), 'batteries': LeanGitRepo(url='https://github.com/l
eanprover-community/batteries', commit='021e272cb5cdcc82b7e1e760fe915ff2f64169ad'), 'Qq': LeanGitRepo(url='https://github.com/leanprover-community/quote4', commit='53156671405fbbd5402ed17a79bd129b961bd8d6'), 'aesop':
LeanGitRepo(url='https://github.com/leanprover-community/aesop', commit='53ba96ad7666d4a2515292974631629b5ea5dfee'), 'proofwidgets': LeanGitRepo(url='https://github.com/leanprover-community/ProofWidgets4', commit='e6b
6247c61280c77ade6bbf0bc3c66a44fe2e0c5'), 'Cli': LeanGitRepo(url='https://github.com/leanprover/lean4-cli', commit='2cf1030dc2ae6b3632c84a09350b675ef3e347d0'), '«doc-gen4»': LeanGitRepo(url='https://github.com/leanprov
er/doc-gen4', commit='83f718b9055972dce4f92f5b3917426b91a0d2fe'), 'MD4Lean': LeanGitRepo(url='https://github.com/acmepjz/md4lean', commit='5e95f4776be5e048364f325c7e9d619bb56fb005'), 'UnicodeBasic': LeanGitRepo(url='h
ttps://github.com/fgdorais/lean4-unicode-basic', commit='9447739fe9714f8a091192bad5cd5e7b5a8ae1e4'), 'BibtexQuery': LeanGitRepo(url='https://github.com/dupuisf/BibtexQuery', commit='c138ab5c566c4268798b24bfcbea2f4c424
13cdd'), 'importGraph': LeanGitRepo(url='https://github.com/leanprover-community/import-graph', commit='0a756018b736ef4f4bc3c9a45fc03cf97a0b1a0c')}, root_dir=PosixPath('/data/yingzi_ma/lean_project/.cache/lean_dojo/le
anprover-community-mathlib4-2b29e73438e240a427bcecc7c0fe19306beb1310/mathlib4'))
2024-09-01 05:33:32.322 | INFO     | generate_benchmark_lean4:main:367 - Successfully traced the repo
2024-09-01 05:33:32.323 | WARNING  | generate_benchmark_lean4:main:372 - /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310 already exists. Using it instead.
2024-09-01 05:33:32.323 | INFO     | __main__:retrieve_proof:1078 - Finished generating benchmark at /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
2024-09-01 05:33:48.431 | INFO     | dynamic_database:add_repository:583 - Attempting to add repository: https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 05:33:48.431 | INFO     | dynamic_database:add_repository:586 - Added new repository: https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2421/2421 [00:00<00:00, 35369.14it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 116251/116251 [00:03<00:00, 33420.42it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2421/2421 [00:00<00:00, 36118.70it/s]
2024-09-01 05:33:57.891 | INFO     | __main__:retrieve_proof:1116 - Before adding new repo:
2024-09-01 05:33:57.891 | INFO     | dynamic_database:print_database_contents:607 - Current database contents:
2024-09-01 05:33:57.891 | INFO     | dynamic_database:print_database_contents:609 -   - https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 05:33:57.892 | INFO     | dynamic_database:add_repository:583 - Attempting to add repository: https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 05:33:57.892 | INFO     | dynamic_database:add_repository:588 - Repository 'https://github.com/leanprover-community/mathlib4' with commit '2b29e73438e240a427bcecc7c0fe19306beb1310' already exists in the dat
abase.
2024-09-01 05:33:57.892 | INFO     | __main__:retrieve_proof:1119 - After adding new repo:
2024-09-01 05:33:57.892 | INFO     | dynamic_database:print_database_contents:607 - Current database contents:
2024-09-01 05:33:57.892 | INFO     | dynamic_database:print_database_contents:609 -   - https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 05:34:18.899 | INFO     | __main__:retrieve_proof:1128 - Adding repo to repos_for_merged_dataset
2024-09-01 05:34:18.900 | INFO     | dynamic_database:generate_merged_dataset:399 - Merging selected repositories in the database:
2024-09-01 05:34:18.900 | INFO     | dynamic_database:generate_merged_dataset:401 -   - https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 05:37:46.303 | WARNING  | dynamic_database:generate_merged_dataset:418 - /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310 already ex
ists. Removing it now.
2024-09-01 05:40:11.904 | INFO     | dynamic_database:generate_merged_dataset:422 - Exported proofs to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe1930
6beb1310
2024-09-01 05:40:12.863 | INFO     | dynamic_database:generate_merged_dataset:425 - Merged and exported corpus to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bce
cc7c0fe19306beb1310
2024-09-01 05:40:12.885 | INFO     | dynamic_database:generate_merged_dataset:428 - Exported traced files to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0
fe19306beb1310
2024-09-01 05:40:12.888 | INFO     | dynamic_database:generate_merged_dataset:431 - Exported metadata to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19
306beb1310
2024-09-01 05:40:12.920 | INFO     | __main__:find_latest_checkpoint:487 - Using the latest checkpoint: /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe
19306beb1310_lambda_0.1_epoch=0-Recall@10_val=58.95.ckpt
2024-09-01 05:40:12.920 | INFO     | __main__:retrieve_proof:1140 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb131
0_lambda_0.1_epoch=0-Recall@10_val=58.95.ckpt
2024-09-01 05:40:12.920 | INFO     | __main__:train_test_fisher:627 - Inside train_test_fisher
2024-09-01 05:40:12.920 | INFO     | __main__:train_test_fisher:628 - Starting training at epoch 0
[rank: 0] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default
 pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more
details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be load
ed via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of
the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/utilities/migration/utils.py:56: The loaded checkpoint was produced with Lightning v2.4.0, which is newer than your current Light
ning version: v2.2.4
2024-09-01 05:40:16.830 | INFO     | __main__:train_test_fisher:652 - Loaded premise retriever at /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306b
eb1310_lambda_0.1_epoch=0-Recall@10_val=58.95.ckpt and reset epoch count
2024-09-01 05:40:16.845 | INFO     | __main__:find_latest_fisher:497 - Using the latest Fisher Information Matrix: /data/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/mathlib4_29dcec074de168ac2bf835a77ef68bbe069194
c5_fisher_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickl
e module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more detail
s). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via
 this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the lo
aded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(io.BytesIO(b))
2024-09-01 05:40:17.332 | INFO     | __main__:load_fisher_information:474 - Fisher Information successfully loaded.
2024-09-01 05:40:17.333 | INFO     | retrieval.model:set_fisher_info:62 - Fisher Information has been updated in the model.
2024-09-01 05:40:17.333 | INFO     | __main__:train_test_fisher:658 - Fisher Information Matrix loaded.
Data path: /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This
behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-01 05:40:17.440 | INFO     | common:__init__:208 - Building the corpus from /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310/corpus.jso
nl
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 116251/116251 [00:27<00:00, 4222.53it/s]
2024-09-01 05:41:17.408 | INFO     | retrieval.datamodule:load_or_cache_data:61 - Saved loaded data to cache /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0
fe19306beb1310/random/cache_train/cached_data.pkl
Training dataset size: 359583
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2421/2421 [00:00<00:00, 4316.78it/s]
2024-09-01 05:41:18.102 | INFO     | retrieval.datamodule:load_or_cache_data:61 - Saved loaded data to cache /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0
fe19306beb1310/random/cache_val/cached_data.pkl
Validation dataset size: 4874
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2421/2421 [00:00<00:00, 4470.61it/s]
2024-09-01 05:41:18.777 | INFO     | retrieval.datamodule:load_or_cache_data:61 - Saved loaded data to cache /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0
fe19306beb1310/random/cache_pred/cached_data.pkl
Testing dataset size: 4922
Training dataset size after load: 359583
Validation dataset size after load: 4874
Testing dataset size after load: 4922
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python /data/yingzi_ma/lean_project/ReProver/main.py ...
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
2024-09-01 05:41:18.887 | INFO     | __main__:train_test_fisher:731 - Starting progressive training from epoch 0 to 1
2024-09-01 05:41:18.887 | INFO     | __main__:train_test_fisher:745 - Finished progressive training at epoch 0
2024-09-01 05:41:18.887 | WARNING  | __main__:train_test_fisher:755 - No best model found. Using the last trained model.
2024-09-01 05:41:18.888 | INFO     | __main__:train_test_fisher:761 - Testing...
2024-09-01 05:41:18.890 | INFO     | retrieval.main:run_cli:55 - PID: 1589627
[rank: 0] Seed set to 3407
2024-09-01 05:41:19.155 | INFO     | retrieval.main:before_instantiate_classes:28 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
/random
2024-09-01 05:41:19.155 | INFO     | retrieval.main:before_instantiate_classes:29 - Corpus path: /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb13
10/corpus.jsonl
2024-09-01 05:41:19.721 | INFO     | common:__init__:208 - Building the corpus from /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310/corpus.jso
nl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204: The `srun` command is available on your system but is not used. HINT: If your intention is to r
un Lightning on SLURM, prepend your python command with `srun` like so: srun python main.py predict --config retrieval/confs/cli_lean4_r ...
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[rank: 0] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
[2024-09-01 05:41:54,067] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-01 05:41:54,067] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-01 05:41:54,067] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-01 05:41:57.136 | INFO     | __main__:main:1245 - Running progressive training
2024-09-01 05:41:57.136 | INFO     | __main__:main:1245 - Running progressive training
2024-09-01 05:41:57.136 | INFO     | __main__:main:1251 - Configuring LeanDojo...
2024-09-01 05:41:57.136 | INFO     | __main__:main:1251 - Configuring LeanDojo...
2024-09-01 05:41:57.136 | INFO     | __main__:main:1245 - Running progressive training
2024-09-01 05:41:57.136 | INFO     | __main__:main:1251 - Configuring LeanDojo...
2024-09-01 05:41:57.141 | INFO     | generate_benchmark_lean4:configure_leandojo:317 - Current working directory: /data/yingzi_ma/lean_project/ReProver
2024-09-01 05:41:57.141 | INFO     | generate_benchmark_lean4:configure_leandojo:317 - Current working directory: /data/yingzi_ma/lean_project/ReProver
2024-09-01 05:41:57.141 | INFO     | __main__:main:1253 - LeanDojo configured
2024-09-01 05:41:57.141 | INFO     | __main__:main:1253 - LeanDojo configured
2024-09-01 05:41:57.141 | INFO     | generate_benchmark_lean4:configure_leandojo:317 - Current working directory: /data/yingzi_ma/lean_project/ReProver
2024-09-01 05:41:57.141 | INFO     | __main__:main:1253 - LeanDojo configured
> /data/yingzi_ma/lean_project/ReProver/main.py(387)search_github_repositories()
    386     import ipdb; ipdb.set_trace()
--> 387     """Search for the given number of repositories on GitHub that have the given language."""
    388     headers = {'Authorization': personal_access_token}
> /data/yingzi_ma/lean_project/ReProver/main.py(387)search_github_repositories()
    386     import ipdb; ipdb.set_trace()
--> 387     """Search for the given number of repositories on GitHub that have the given language."""
    388     headers = {'Authorization': personal_access_token}


ipdb> > /data/yingzi_ma/lean_project/ReProver/main.py(387)search_github_repositories()
    386     import ipdb; ipdb.set_trace()
--> 387     """Search for the given number of repositories on GitHub that have the given language."""
    388     headers = {'Authorization': personal_access_token}

ipdb> ipdb> ∫:capWARNING: your terminal doesn't support cursor position requests (CPR).
ipdb> n
> /data/yingzi_ma/lean_project/ReProver/main.py(388)search_github_repositories()
    387     """Search for the given number of repositories on GitHub that have the given language."""
--> 388     headers = {'Authorization': personal_access_token}
    389     query_params = {

ipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(390)search_github_repositories()
    389     query_params = {
--> 390         'q': f'language:{language}',
    391         'sort': 'stars',

ipdb> ∫:capture∫:
ipdb>
ip b>
ipdb> n
> /data/yingzi_ma/lean_project/ReProver/main.py(391)search_github_repositories()
    390         'q': f'language:{language}',
--> 391         'sort': 'stars',
    392         'order': 'desc',

iipdb>
n> /data/yingzi_ma/lean_project/ReProver/main.py(392)search_github_repositories()
    391         'sort': 'stars',
--> 392         'order': 'desc',
ipdb> ∫:capture∫:

    nnn
*** SyntaxError: invalid character '∫' (U+222B)
iipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(393)search_github_repositories()
    392         'order': 'desc',
--> 393         'per_page': 100,
    394     }

iipdb>
ipdb> n
> /data/yingzi_ma/lean_project/ReProver/main.py(388)search_github_repositories()
    387     """Search for the given number of repositories on GitHub that have the given language."""
--> 388     headers = {'Authorization': personal_access_token}
    389     query_params = {

iipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(390)search_github_repositories()
    389     query_params = {
--> 390         'q': f'language:{language}',
    391         'sort': 'stars',

ipdb> ipdb> nnqryama
*** NameError: name 'nnqryama' is not defined
iipdb>
*** NameError: name 'nnqryama' is not defined
iipdb>
*** NameError: name 'nnqryama' is not defined
ipdb> n ue_pmsnnn
> /data/yingzi_ma/lean_project/ReProver/main.py(391)search_github_repositories()
    390         'q': f'language:{language}',
--> 391         'sort': 'stars',
    392         'order': 'desc',

iipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(392)search_github_repositories()
    391         'sort': 'stars',
--> 392         'order': 'desc',
    393         'per_page': 100,

iipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(393)search_github_repositories()
    392         'order': 'desc',
--> 393         'per_page': 100,
    394     }

iipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(389)search_github_repositories()
    388     headers = {'Authorization': personal_access_token}
--> 389     query_params = {
    390         'q': f'language:{language}',

ipdb> nnn
*** NameError: name 'nnn' is not defined
iipdb>
*** NameError: name 'nnn' is not defined
iipdb>
*** NameError: name 'nnn' is not defined
iipdb>
*** NameError: name 'nnn' is not defined
ipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(395)search_github_repositories()
    394     }
--> 395     response = requests.get('https://api.github.com/search/repositories', headers=headers, params=query_params)
    396

iipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(397)search_github_repositories()
    396
--> 397     if response.status_code == 200:
    398         repositories = response.json()['items']

ipdb> reipdb> eson.dsat_od
*** NameError: name 'eson' is not defined
ipdb> nrp
*** NameError: name 'nrp' is not defined
ipdb> n
> /data/yingzi_ma/lean_project/ReProver/main.py(398)search_github_repositories()
    397     if response.status_code == 200:
--> 398         repositories = response.json()['items']
    399         cloned_count = 0

iipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(399)search_github_repositories()
    398         repositories = response.json()['items']
--> 399         cloned_count = 0
    400         for repo in repositories:

ipdb> n
> /data/yingzi_ma/lean_project/ReProver/main.py(389)search_github_repositories()
    388     headers = {'Authorization': personal_access_token}
--> 389     query_params = {
    390         'q': f'language:{language}',

iipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(395)search_github_repositories()
    394     }
--> 395     response = requests.get('https://api.github.com/search/repositories', headers=headers, params=query_params)
    396

iipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(397)search_github_repositories()
    396
--> 397     if response.status_code == 200:
    398         repositories = response.json()['items']

iipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(398)search_github_repositories()
    397     if response.status_code == 200:
--> 398         repositories = response.json()['items']
    399         cloned_count = 0

iipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(399)search_github_repositories()
    398         repositories = response.json()['items']
--> 399         cloned_count = 0
    400         for repo in repositories:

iipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(400)search_github_repositories()
    399         cloned_count = 0
--> 400         for repo in repositories:
    401             if cloned_count >= num_repos:

ipdb> nnnnnnn
*** NameError: name 'nnnnnnn' is not defined
iipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(401)search_github_repositories()
    400         for repo in repositories:
--> 401             if cloned_count >= num_repos:
    402                 break

ipdb> n
> /data/yingzi_ma/lean_project/ReProver/main.py(400)search_github_repositories()
    399         cloned_count = 0
--> 400         for repo in repositories:
    401             if cloned_count >= num_repos:

iipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(401)search_github_repositories()
    400         for repo in repositories:
--> 401             if cloned_count >= num_repos:
    402                 break

ipdb> nn
*** NameError: name 'nn' is not defined
iipdb>
*** NameError: name 'nn' is not defined
iipdb>
*** NameError: name 'nn' is not defined
ipdb> nnn
*** NameError: name 'nnn' is not defined
iipdb>
*** NameError: name 'nnn' is not defined
ipdb>
*** NameError: name 'nnn' is not defined
ipdb>
*** NameError: name 'nnn' is not defined
ipdb> n
> /data/yingzi_ma/lean_project/ReProver/main.py(403)search_github_repositories()
    402                 break
--> 403             repo_full_name = repo['full_name']
    404             logger.info(f"Processing {repo_full_name}")

ipdb>
*** NameError: name 'nnn' is not defined
ipdb>
*** NameError: name 'nnn' is not defined
ipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(404)search_github_repositories()
    403             repo_full_name = repo['full_name']
--> 404             logger.info(f"Processing {repo_full_name}")
    405             if repo_full_name not in known_repositories:

ipdb>
*** NameError: name 'nnn' is not defined
ipdb>
2024-09-01 05:44:47.636 | INFO     | __main__:search_github_repositories:404 - Processing leanprover/lean4
> /data/yingzi_ma/lean_project/ReProver/main.py(405)search_github_repositories()
    404             logger.info(f"Processing {repo_full_name}")
--> 405             if repo_full_name not in known_repositories:
    406                 name = None

ipdb>
*** NameError: name 'nnn' is not defined
ipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(422)search_github_repositories()
    421             else:
--> 422                 logger.info(f"Skipping {repo_full_name} since it is a known repository")
    423     else:

ipdb>
ipdb>
*** NameError: name 'nnn' is not defined
ipdb> 2024-09-01 05:44:57.597 | INFO     | __main__:search_github_repositories:422 - Skipping leanprover/lean4 since it is a known repository
> /data/yingzi_ma/lean_project/ReProver/main.py(400)search_github_repositories()
    399         cloned_count = 0
--> 400         for repo in repositories:
    401             if cloned_count >= num_repos:

ipdb>
*** NameError: name 'nnn' is not defined
ipdb>
*** NameError: name 'nnn' is not defined
ipdb>
ipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(401)search_github_repositories()
    400         for repo in repositories:
--> 401             if cloned_count >= num_repos:
    402                 break

ipdb> *** NameError: name 'nnn' is not defined
ipdb>
*** NameError: name 'nnn' is not defined
ipdb>
> /data/yingzi_ma/lean_project/ReProver/main.py(403)search_github_repositories()
    402                 break
--> 403             repo_full_name = repo['full_name']
    404             logger.info(f"Processing {repo_full_name}")

iipdb>
*** NameError: name 'nnn' is not defined
ipdb> c
2024-09-01 05:45:05.569 | INFO     | __main__:search_github_repositories:404 - Processing leanprover-community/mathlib3
Cloning https://github.com/leanprover-community/mathlib3.git
Repo name: leanprover-community/mathlib3
2024-09-01 05:45:06.494 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/leanprover-community/mathlib3/65a1391a0106c9204fe45bc73a039f056558cb83/lean-toolchain failed. Retrying..
.
2024-09-01 05:45:07.533 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/leanprover-community/mathlib3/65a1391a0106c9204fe45bc73a039f056558cb83/lean-toolchain failed. Retrying..
.
2024-09-01 05:45:09.574 | INFO     | __main__:search_github_repositories:420 - Failed to clone leanprover-community/mathlib3 because of HTTP Error 404: Not Found
2024-09-01 05:45:09.575 | INFO     | __main__:search_github_repositories:404 - Processing leanprover-community/mathlib4
Cloning https://github.com/leanprover-community/mathlib4.git
Repo name: leanprover-community/mathlib4
2024-09-01 05:45:10.503 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0-rc3
iipdb> c
2024-09-01 05:45:25.823 | INFO     | __main__:search_github_repositories:404 - Processing uwdb/Cosette
Cloning https://github.com/uwdb/Cosette.git
Repo name: uwdb/Cosette
2024-09-01 05:45:26.537 | INFO     | __main__:search_github_repositories:404 - Processing leanprover/lean4
2024-09-01 05:45:26.538 | INFO     | __main__:search_github_repositories:422 - Skipping leanprover/lean4 since it is a known repository
2024-09-01 05:45:26.538 | INFO     | __main__:search_github_repositories:404 - Processing leanprover-community/mathlib3
Cloning https://github.com/leanprover-community/mathlib3.git
Repo name: leanprover-community/mathlib3
2024-09-01 05:45:26.579 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/uwdb/Cosette/c16b48ec7d278c717a9f1da3684f69621b3863f2/lean-toolchain failed. Retrying...
2024-09-01 05:45:27.562 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/leanprover-community/mathlib3/65a1391a0106c9204fe45bc73a039f056558cb83/lean-toolchain failed. Retrying..
.
2024-09-01 05:45:27.619 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/uwdb/Cosette/c16b48ec7d278c717a9f1da3684f69621b3863f2/lean-toolchain failed. Retrying...
2024-09-01 05:45:28.601 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/leanprover-community/mathlib3/65a1391a0106c9204fe45bc73a039f056558cb83/lean-toolchain failed. Retrying..
.
2024-09-01 05:45:29.659 | INFO     | __main__:search_github_repositories:420 - Failed to clone uwdb/Cosette because of HTTP Error 404: Not Found
2024-09-01 05:45:29.660 | INFO     | __main__:search_github_repositories:404 - Processing AndrasKovacs/smalltt
Cloning https://github.com/AndrasKovacs/smalltt.git
Repo name: AndrasKovacs/smalltt
2024-09-01 05:45:30.294 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/AndrasKovacs/smalltt/b5fc9b3747dcbf8c71ca9f976afb7b574b630996/lean-toolchain failed. Retrying...
2024-09-01 05:45:30.641 | INFO     | __main__:search_github_repositories:420 - Failed to clone leanprover-community/mathlib3 because of HTTP Error 404: Not Found
2024-09-01 05:45:30.642 | INFO     | __main__:search_github_repositories:404 - Processing leanprover-community/mathlib4
Cloning https://github.com/leanprover-community/mathlib4.git
Repo name: leanprover-community/mathlib4
2024-09-01 05:45:31.334 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/AndrasKovacs/smalltt/b5fc9b3747dcbf8c71ca9f976afb7b574b630996/lean-toolchain failed. Retrying...
2024-09-01 05:45:31.407 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0-rc3
2024-09-01 05:45:33.374 | INFO     | __main__:search_github_repositories:420 - Failed to clone AndrasKovacs/smalltt because of HTTP Error 404: Not Found
2024-09-01 05:45:33.374 | INFO     | __main__:search_github_repositories:404 - Processing dselsam/certigrad
Cloning https://github.com/dselsam/certigrad.git
Repo name: dselsam/certigrad
2024-09-01 05:45:34.013 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/dselsam/certigrad/c9a06e93f1ec58196d6d3b8563b29868d916727f/lean-toolchain failed. Retrying...
2024-09-01 05:45:35.052 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/dselsam/certigrad/c9a06e93f1ec58196d6d3b8563b29868d916727f/lean-toolchain failed. Retrying...
2024-09-01 05:45:37.093 | INFO     | __main__:search_github_repositories:420 - Failed to clone dselsam/certigrad because of HTTP Error 404: Not Found
2024-09-01 05:45:37.094 | INFO     | __main__:search_github_repositories:404 - Processing Kha/electrolysis
Cloning https://github.com/Kha/electrolysis.git
Repo name: Kha/electrolysis
2024-09-01 05:45:37.751 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/Kha/electrolysis/bd4655d91ca65856fb8373637ce3e7b17ee3a190/lean-toolchain failed. Retrying...
2024-09-01 05:45:38.790 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/Kha/electrolysis/bd4655d91ca65856fb8373637ce3e7b17ee3a190/lean-toolchain failed. Retrying...
2024-09-01 05:45:40.831 | INFO     | __main__:search_github_repositories:420 - Failed to clone Kha/electrolysis because of HTTP Error 404: Not Found
2024-09-01 05:45:40.832 | INFO     | __main__:search_github_repositories:404 - Processing ImperialCollegeLondon/formalising-mathematics
Cloning https://github.com/ImperialCollegeLondon/formalising-mathematics.git
Repo name: ImperialCollegeLondon/formalising-mathematics
2024-09-01 05:45:41.522 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/ImperialCollegeLondon/formalising-mathematics/d81ad67e36774eb68f242bcc1b88d33dacfd87bf/lean-toolchain fa
iled. Retrying...
2024-09-01 05:45:42.562 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/ImperialCollegeLondon/formalising-mathematics/d81ad67e36774eb68f242bcc1b88d33dacfd87bf/lean-toolchain fa
iled. Retrying...
2024-09-01 05:45:44.601 | INFO     | __main__:search_github_repositories:420 - Failed to clone ImperialCollegeLondon/formalising-mathematics because of HTTP Error 404: Not Found
2024-09-01 05:45:44.602 | INFO     | __main__:search_github_repositories:404 - Processing lecopivo/SciLean
Cloning https://github.com/lecopivo/SciLean.git
Repo name: lecopivo/SciLean
2024-09-01 05:45:45.275 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0-rc2
2024-09-01 05:45:46.718 | INFO     | __main__:search_github_repositories:404 - Processing uwdb/Cosette
Cloning https://github.com/uwdb/Cosette.git
Repo name: uwdb/Cosette
2024-09-01 05:45:47.286 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/uwdb/Cosette/c16b48ec7d278c717a9f1da3684f69621b3863f2/lean-toolchain failed. Retrying...
2024-09-01 05:45:48.326 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/uwdb/Cosette/c16b48ec7d278c717a9f1da3684f69621b3863f2/lean-toolchain failed. Retrying...
2024-09-01 05:45:50.367 | INFO     | __main__:search_github_repositories:420 - Failed to clone uwdb/Cosette because of HTTP Error 404: Not Found
2024-09-01 05:45:50.369 | INFO     | __main__:search_github_repositories:404 - Processing AndrasKovacs/smalltt
Cloning https://github.com/AndrasKovacs/smalltt.git
Repo name: AndrasKovacs/smalltt
2024-09-01 05:45:50.838 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/AndrasKovacs/smalltt/b5fc9b3747dcbf8c71ca9f976afb7b574b630996/lean-toolchain failed. Retrying...
2024-09-01 05:45:51.877 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/AndrasKovacs/smalltt/b5fc9b3747dcbf8c71ca9f976afb7b574b630996/lean-toolchain failed. Retrying...
2024-09-01 05:45:53.917 | INFO     | __main__:search_github_repositories:420 - Failed to clone AndrasKovacs/smalltt because of HTTP Error 404: Not Found
2024-09-01 05:45:53.918 | INFO     | __main__:search_github_repositories:404 - Processing dselsam/certigrad
Cloning https://github.com/dselsam/certigrad.git
Repo name: dselsam/certigrad
2024-09-01 05:45:54.426 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/dselsam/certigrad/c9a06e93f1ec58196d6d3b8563b29868d916727f/lean-toolchain failed. Retrying...
2024-09-01 05:45:55.463 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/dselsam/certigrad/c9a06e93f1ec58196d6d3b8563b29868d916727f/lean-toolchain failed. Retrying...
2024-09-01 05:45:57.502 | INFO     | __main__:search_github_repositories:420 - Failed to clone dselsam/certigrad because of HTTP Error 404: Not Found
2024-09-01 05:45:57.503 | INFO     | __main__:search_github_repositories:404 - Processing Kha/electrolysis
Cloning https://github.com/Kha/electrolysis.git
Repo name: Kha/electrolysis
2024-09-01 05:45:58.003 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/Kha/electrolysis/bd4655d91ca65856fb8373637ce3e7b17ee3a190/lean-toolchain failed. Retrying...
2024-09-01 05:45:59.042 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/Kha/electrolysis/bd4655d91ca65856fb8373637ce3e7b17ee3a190/lean-toolchain failed. Retrying...
Found 2 repositories
Using lambda = 0.1
Processing /data/yingzi_ma/lean_project/repos_new/leanprover-community/mathlib4
2024-09-01 05:46:00.511 | INFO     | __main__:retrieve_proof:1060 - Processing https://github.com/leanprover-community/mathlib4.git
2024-09-01 05:46:00.511 | INFO     | __main__:retrieve_proof:1076 - Found compatible commit 2b29e73438e240a427bcecc7c0fe19306beb1310 for https://github.com/leanprover-community/mathlib4.git
2024-09-01 05:46:00.511 | INFO     | __main__:retrieve_proof:1077 - Lean version: v4.8.0
2024-09-01 05:46:00.721 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.8.0
2024-09-01 05:46:01.083 | INFO     | __main__:search_github_repositories:420 - Failed to clone Kha/electrolysis because of HTTP Error 404: Not Found
2024-09-01 05:46:01.084 | INFO     | __main__:search_github_repositories:404 - Processing ImperialCollegeLondon/formalising-mathematics
Cloning https://github.com/ImperialCollegeLondon/formalising-mathematics.git
Repo name: ImperialCollegeLondon/formalising-mathematics
2024-09-01 05:46:01.691 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/ImperialCollegeLondon/formalising-mathematics/d81ad67e36774eb68f242bcc1b88d33dacfd87bf/lean-toolchain fa
iled. Retrying...
2024-09-01 05:46:02.731 | DEBUG    | lean_dojo.utils:read_url:178 - Request to https://raw.githubusercontent.com/ImperialCollegeLondon/formalising-mathematics/d81ad67e36774eb68f242bcc1b88d33dacfd87bf/lean-toolchain fa
iled. Retrying...
2024-09-01 05:46:04.771 | INFO     | __main__:search_github_repositories:420 - Failed to clone ImperialCollegeLondon/formalising-mathematics because of HTTP Error 404: Not Found
2024-09-01 05:46:04.772 | INFO     | __main__:search_github_repositories:404 - Processing lecopivo/SciLean
Cloning https://github.com/lecopivo/SciLean.git
Repo name: lecopivo/SciLean
2024-09-01 05:46:05.331 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0-rc2
2024-09-01 05:46:16.031 | INFO     | __main__:retrieve_proof:1082 - Generating benchmark at /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
2024-09-01 05:46:16.031 | INFO     | generate_benchmark_lean4:main:324 - Generating dataset to go into /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
2024-09-01 05:46:16.031 | INFO     | generate_benchmark_lean4:main:331 - lean toolchain version: {'content': 'leanprover/lean4:v4.8.0\n'}
2024-09-01 05:46:16.031 | INFO     | generate_benchmark_lean4:main:333 - lean version v: v4.8.0
2024-09-01 05:46:16.031 | INFO     | generate_benchmark_lean4:main:334 - is supported: True
2024-09-01 05:46:16.032 | INFO     | generate_benchmark_lean4:main:344 - lean path1 /data/yingzi_ma/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:46:16.032 | INFO     | generate_benchmark_lean4:main:345 - lean path2 /.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:46:16.032 | INFO     | generate_benchmark_lean4:main:346 - lean path3 ~/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:46:16.033 | INFO     | generate_benchmark_lean4:main:350 - Lean toolchain path 2 does not exist: /.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:46:16.033 | INFO     | generate_benchmark_lean4:main:352 - Lean toolchain path 3 does not exist: ~/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:46:16.033 | INFO     | generate_benchmark_lean4:main:355 - Switched to Lean toolchain at: /data/yingzi_ma/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:46:16.083 | INFO     | generate_benchmark_lean4:main:357 - lean --version: Lean (version 4.8.0, x86_64-unknown-linux-gnu, commit df668f00e6c0, Release)

2024-09-01 05:46:16.083 | INFO     | generate_benchmark_lean4:main:358 - repo: LeanGitRepo(url='https://github.com/leanprover-community/mathlib4', commit='2b29e73438e240a427bcecc7c0fe19306beb1310')
2024-09-01 05:46:16.083 | INFO     | generate_benchmark_lean4:main:360 - Configuring LeanDojo again...
2024-09-01 05:46:16.090 | INFO     | generate_benchmark_lean4:configure_leandojo:317 - Current working directory: /data/yingzi_ma/lean_project/ReProver
2024-09-01 05:46:16.090 | INFO     | generate_benchmark_lean4:main:362 - LeanDojo configured
2024-09-01 05:46:16.091 | INFO     | generate_benchmark_lean4:main:365 - Tracing the repo...
2024-09-01 05:46:16.093 | DEBUG    | lean_dojo.data_extraction.trace:get_traced_repo_path:87 - The traced repo is available in the cache.
2024-09-01 05:46:16.093 | INFO     | lean_dojo.data_extraction.trace:trace:116 - Loading the traced repo from /data/yingzi_ma/lean_project/.cache/lean_dojo/leanprover-community-mathlib4-2b29e73438e240a427bcecc7c0fe193
06beb1310/mathlib4
2024-09-01 05:46:18.471 | DEBUG    | lean_dojo.data_extraction.traced_data:load_from_disk:1123 - Loading 5514 traced XML files from /data/yingzi_ma/lean_project/.cache/lean_dojo/leanprover-community-mathlib4-2b29e7343
8e240a427bcecc7c0fe19306beb1310/mathlib4 with 31 workers
  1%|█                                                                                                                                                                                 | 33/5514 [00:02<06:49, 13.38it/s]
Found 2 repositories
Using lambda = 0.1
Processing /data/yingzi_ma/lean_project/repos_new/leanprover-community/mathlib4
2024-09-01 05:46:20.868 | INFO     | __main__:retrieve_proof:1060 - Processing https://github.com/leanprover-community/mathlib4.git
2024-09-01 05:46:20.868 | INFO     | __main__:retrieve_proof:1076 - Found compatible commit 2b29e73438e240a427bcecc7c0fe19306beb1310 for https://github.com/leanprover-community/mathlib4.git
2024-09-01 05:46:20.868 | INFO     | __main__:retrieve_proof:1077 - Lean version: v4.8.0
2024-09-01 05:46:20.905 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.8.0
  2%|███▏                                                                                                                                                                             | 100/5514 [00:17<24:42,  3.65it/s]
2024-09-01 05:46:36.254 | INFO     | __main__:retrieve_proof:1082 - Generating benchmark at /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
2024-09-01 05:46:36.255 | INFO     | generate_benchmark_lean4:main:324 - Generating dataset to go into /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
2024-09-01 05:46:36.255 | INFO     | generate_benchmark_lean4:main:331 - lean toolchain version: {'content': 'leanprover/lean4:v4.8.0\n'}
2024-09-01 05:46:36.255 | INFO     | generate_benchmark_lean4:main:333 - lean version v: v4.8.0
2024-09-01 05:46:36.255 | INFO     | generate_benchmark_lean4:main:334 - is supported: True
2024-09-01 05:46:36.255 | INFO     | generate_benchmark_lean4:main:344 - lean path1 /data/yingzi_ma/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:46:36.255 | INFO     | generate_benchmark_lean4:main:345 - lean path2 /.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:46:36.255 | INFO     | generate_benchmark_lean4:main:346 - lean path3 ~/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:46:36.256 | INFO     | generate_benchmark_lean4:main:350 - Lean toolchain path 2 does not exist: /.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:46:36.256 | INFO     | generate_benchmark_lean4:main:352 - Lean toolchain path 3 does not exist: ~/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:46:36.256 | INFO     | generate_benchmark_lean4:main:355 - Switched to Lean toolchain at: /data/yingzi_ma/.elan/toolchains/leanprover--lean4---4.8.0
2024-09-01 05:46:36.319 | INFO     | generate_benchmark_lean4:main:357 - lean --version: Lean (version 4.8.0, x86_64-unknown-linux-gnu, commit df668f00e6c0, Release)

2024-09-01 05:46:36.319 | INFO     | generate_benchmark_lean4:main:358 - repo: LeanGitRepo(url='https://github.com/leanprover-community/mathlib4', commit='2b29e73438e240a427bcecc7c0fe19306beb1310')
2024-09-01 05:46:36.320 | INFO     | generate_benchmark_lean4:main:360 - Configuring LeanDojo again...
2024-09-01 05:46:36.326 | INFO     | generate_benchmark_lean4:configure_leandojo:317 - Current working directory: /data/yingzi_ma/lean_project/ReProver
2024-09-01 05:46:36.326 | INFO     | generate_benchmark_lean4:main:362 - LeanDojo configured
2024-09-01 05:46:36.326 | INFO     | generate_benchmark_lean4:main:365 - Tracing the repo...
2024-09-01 05:46:36.328 | DEBUG    | lean_dojo.data_extraction.trace:get_traced_repo_path:87 - The traced repo is available in the cache.
2024-09-01 05:46:36.328 | INFO     | lean_dojo.data_extraction.trace:trace:116 - Loading the traced repo from /data/yingzi_ma/lean_project/.cache/lean_dojo/leanprover-community-mathlib4-2b29e73438e240a427bcecc7c0fe193
06beb1310/mathlib4
  2%|████▏                                                                                                                                                                            | 129/5514 [00:20<06:13, 14.42it/s]
2024-09-01 05:46:38.541 | DEBUG    | lean_dojo.data_extraction.traced_data:load_from_disk:1123 - Loading 5514 traced XML files from /data/yingzi_ma/lean_project/.cache/lean_dojo/leanprover-community-mathlib4-2b29e7343
8e240a427bcecc7c0fe19306beb1310/mathlib4 with 31 workers
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5514/5514 [15:40<00:00,  5.86it/s]
2024-09-01 06:02:19.126 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/mathlib4', commit='2b29e73438e240a427bce
cc7c0fe19306beb1310')
 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                    | 4365/5514 [16:01<01:53, 10.11it/s]
2024-09-01 06:02:20.485 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.6.0-rc1
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                             | 4589/5514 [16:18<00:24, 37.54it/s]
2024-09-01 06:02:37.106 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.8.0-rc1
 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                      | 4808/5514 [16:34<00:50, 13.85it/s]
2024-09-01 06:02:53.267 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.7.0
 91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍               | 5026/5514 [16:50<00:37, 12.99it/s]
2024-09-01 06:03:09.188 | DEBUG    | lean_dojo.data_extraction.lean:url_to_repo:70 - url_to_repo("https://github.com/leanprover-community/import-graph.git") failed. Retrying...
 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 5046/5514 [16:51<00:18, 25.25it/s]
2024-09-01 06:03:10.305 | DEBUG    | lean_dojo.data_extraction.lean:url_to_repo:70 - url_to_repo("https://github.com/leanprover-community/import-graph.git") failed. Retrying...
 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌             | 5093/5514 [16:54<00:27, 15.13it/s]
2024-09-01 06:03:12.905 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for doc-gen4 main
 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏            | 5114/5514 [16:55<00:13, 28.96it/s]
2024-09-01 06:03:13.526 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for batteries main
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 5255/5514 [17:02<00:05, 45.89it/s]
2024-09-01 06:03:23.124 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for quote4 master
 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 5260/5514 [17:05<00:34,  7.41it/s]
2024-09-01 06:03:23.533 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.10.0
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5514/5514 [17:17<00:00,  5.31it/s]
2024-09-01 06:03:36.440 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/mathlib4', commit='2b29e73438e240a427bce
cc7c0fe19306beb1310')
2024-09-01 06:03:37.647 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.6.0-rc1
2024-09-01 06:03:39.036 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for aesop master
2024-09-01 06:03:40.146 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0-rc1
2024-09-01 06:03:54.118 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.8.0-rc1
2024-09-01 06:03:55.419 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for ProofWidgets4 v0.0.36
2024-09-01 06:03:56.240 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4-cli main
2024-09-01 06:03:56.860 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.9.0
2024-09-01 06:04:10.192 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.7.0
2024-09-01 06:04:12.747 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for import-graph main
2024-09-01 06:04:13.371 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover/doc-gen4', commit='83f718b9055972dce4f92f5b3917426
b91a0d2fe')
2024-09-01 06:04:13.895 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.9.0-rc1
2024-09-01 06:04:26.006 | DEBUG    | lean_dojo.data_extraction.lean:url_to_repo:70 - url_to_repo("https://github.com/leanprover-community/import-graph.git") failed. Retrying...
2024-09-01 06:04:27.127 | DEBUG    | lean_dojo.data_extraction.lean:url_to_repo:70 - url_to_repo("https://github.com/leanprover-community/import-graph.git") failed. Retrying...
2024-09-01 06:04:29.722 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for doc-gen4 main
2024-09-01 06:04:30.185 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for batteries main
Following Github server redirection from /repos/mhuisi/lean4-cli to /repositories/341363356
2024-09-01 06:04:30.997 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4-nightly nightly-2024-06-05
2024-09-01 06:04:32.485 | WARNING  | lean_dojo.data_extraction.lean:__post_init__:446 - LeanGitRepo(url='https://github.com/mhuisi/lean4-cli', commit='bf066c328bcff19aa93adf4d24c4e896c0d4eaca') relies on an unsupporte
d Lean version: fbb3055f82ff9a4bc82f6722f6e73225617342fd
2024-09-01 06:04:32.486 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/batteries', commit='a7fd140a94bbbfa40cf1
0839227bbb9e8492be2d')
2024-09-01 06:04:32.683 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/quote4', commit='d38fb94558af9957b8f479e
350841ce65a1ec42c')
2024-09-01 06:04:32.869 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/aesop', commit='6c89b6765913a0d727c10664
93c3f5dc51c9713e')
2024-09-01 06:04:33.244 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/ProofWidgets4', commit='e6b6247c61280c77
ade6bbf0bc3c66a44fe2e0c5')
2024-09-01 06:04:33.595 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover/lean4-cli', commit='2cf1030dc2ae6b3632c84a09350b67
5ef3e347d0')
2024-09-01 06:04:33.779 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/import-graph', commit='0a756018b736ef4f4
bc3c9a45fc03cf97a0b1a0c')
2024-09-01 06:04:39.964 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for quote4 master
2024-09-01 06:04:40.394 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.10.0
^[[56;1Ripdb> pn2024-09-01 06:04:56.508 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for aesop master
2024-09-01 06:04:57.386 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.11.0-rc1
2024-09-01 06:05:08.691 | DEBUG    | lean_dojo.data_extraction.traced_data:check_sanity:1009 - Checking the sanity of TracedRepo(repo=LeanGitRepo(url='https://github.com/leanprover-community/mathlib4', commit='2b29e73
438e240a427bcecc7c0fe19306beb1310'), dependencies={'lean4': LeanGitRepo(url='https://github.com/leanprover/lean4', commit='daa22187642d4cf6954c39a23eab20d8a8675416'), 'batteries': LeanGitRepo(url='https://github.com/l
eanprover-community/batteries', commit='021e272cb5cdcc82b7e1e760fe915ff2f64169ad'), 'Qq': LeanGitRepo(url='https://github.com/leanprover-community/quote4', commit='53156671405fbbd5402ed17a79bd129b961bd8d6'), 'aesop':
LeanGitRepo(url='https://github.com/leanprover-community/aesop', commit='53ba96ad7666d4a2515292974631629b5ea5dfee'), 'proofwidgets': LeanGitRepo(url='https://github.com/leanprover-community/ProofWidgets4', commit='e6b
6247c61280c77ade6bbf0bc3c66a44fe2e0c5'), 'Cli': LeanGitRepo(url='https://github.com/leanprover/lean4-cli', commit='2cf1030dc2ae6b3632c84a09350b675ef3e347d0'), '«doc-gen4»': LeanGitRepo(url='https://github.com/leanprov
er/doc-gen4', commit='83f718b9055972dce4f92f5b3917426b91a0d2fe'), 'MD4Lean': LeanGitRepo(url='https://github.com/acmepjz/md4lean', commit='5e95f4776be5e048364f325c7e9d619bb56fb005'), 'UnicodeBasic': LeanGitRepo(url='h
ttps://github.com/fgdorais/lean4-unicode-basic', commit='9447739fe9714f8a091192bad5cd5e7b5a8ae1e4'), 'BibtexQuery': LeanGitRepo(url='https://github.com/dupuisf/BibtexQuery', commit='c138ab5c566c4268798b24bfcbea2f4c424
13cdd'), 'importGraph': LeanGitRepo(url='https://github.com/leanprover-community/import-graph', commit='0a756018b736ef4f4bc3c9a45fc03cf97a0b1a0c')}, root_dir=PosixPath('/data/yingzi_ma/lean_project/.cache/lean_dojo/le
anprover-community-mathlib4-2b29e73438e240a427bcecc7c0fe19306beb1310/mathlib4'))
2024-09-01 06:05:13.712 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for ProofWidgets4 v0.0.36
2024-09-01 06:05:14.538 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4-cli main
2024-09-01 06:05:15.000 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.9.0
2024-09-01 06:05:31.457 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for import-graph main
2024-09-01 06:05:31.956 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover/doc-gen4', commit='83f718b9055972dce4f92f5b3917426
b91a0d2fe')
2024-09-01 06:05:32.401 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4 v4.9.0-rc1
2024-09-01 06:05:32.968 | INFO     | generate_benchmark_lean4:main:367 - Successfully traced the repo
2024-09-01 06:05:32.970 | WARNING  | generate_benchmark_lean4:main:372 - /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310 already exists. Using it instead.
2024-09-01 06:05:32.970 | INFO     | __main__:retrieve_proof:1090 - Finished generating benchmark at /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
Following Github server redirection from /repos/mhuisi/lean4-cli to /repositories/341363356
2024-09-01 06:05:49.842 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for lean4-nightly nightly-2024-06-05
2024-09-01 06:05:50.048 | INFO     | dynamic_database:add_repository:583 - Attempting to add repository: https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 06:05:50.048 | INFO     | dynamic_database:add_repository:586 - Added new repository: https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2421/2421 [00:00<00:00, 35259.47it/s]
2024-09-01 06:05:51.487 | WARNING  | lean_dojo.data_extraction.lean:__post_init__:446 - LeanGitRepo(url='https://github.com/mhuisi/lean4-cli', commit='bf066c328bcff19aa93adf4d24c4e896c0d4eaca') relies on an unsupporte
d Lean version: fbb3055f82ff9a4bc82f6722f6e73225617342fd
2024-09-01 06:05:51.487 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/batteries', commit='a7fd140a94bbbfa40cf1
0839227bbb9e8492be2d')
2024-09-01 06:05:51.531 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/quote4', commit='d38fb94558af9957b8f479e
350841ce65a1ec42c')
2024-09-01 06:05:51.573 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/aesop', commit='6c89b6765913a0d727c10664
93c3f5dc51c9713e')
2024-09-01 06:05:51.655 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/ProofWidgets4', commit='e6b6247c61280c77
ade6bbf0bc3c66a44fe2e0c5')
2024-09-01 06:05:51.736 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover/lean4-cli', commit='2cf1030dc2ae6b3632c84a09350b67
5ef3e347d0')
2024-09-01 06:05:51.776 | DEBUG    | lean_dojo.data_extraction.lean:get_dependencies:499 - Querying the dependencies of LeanGitRepo(url='https://github.com/leanprover-community/import-graph', commit='0a756018b736ef4f4
bc3c9a45fc03cf97a0b1a0c')
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 116251/116251 [00:03<00:00, 33376.26it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2421/2421 [00:00<00:00, 35841.29it/s]
2024-09-01 06:05:59.588 | INFO     | __main__:retrieve_proof:1128 - Before adding new repo:
2024-09-01 06:05:59.588 | INFO     | dynamic_database:print_database_contents:607 - Current database contents:
2024-09-01 06:05:59.589 | INFO     | dynamic_database:print_database_contents:609 -   - https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 06:05:59.589 | INFO     | dynamic_database:add_repository:583 - Attempting to add repository: https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 06:05:59.589 | INFO     | dynamic_database:add_repository:588 - Repository 'https://github.com/leanprover-community/mathlib4' with commit '2b29e73438e240a427bcecc7c0fe19306beb1310' already exists in the dat
abase.
2024-09-01 06:05:59.589 | INFO     | __main__:retrieve_proof:1131 - After adding new repo:
2024-09-01 06:05:59.589 | INFO     | dynamic_database:print_database_contents:607 - Current database contents:
2024-09-01 06:05:59.589 | INFO     | dynamic_database:print_database_contents:609 -   - https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 06:06:26.918 | DEBUG    | lean_dojo.data_extraction.traced_data:check_sanity:1009 - Checking the sanity of TracedRepo(repo=LeanGitRepo(url='https://github.com/leanprover-community/mathlib4', commit='2b29e73
438e240a427bcecc7c0fe19306beb1310'), dependencies={'lean4': LeanGitRepo(url='https://github.com/leanprover/lean4', commit='daa22187642d4cf6954c39a23eab20d8a8675416'), 'batteries': LeanGitRepo(url='https://github.com/l
eanprover-community/batteries', commit='021e272cb5cdcc82b7e1e760fe915ff2f64169ad'), 'Qq': LeanGitRepo(url='https://github.com/leanprover-community/quote4', commit='53156671405fbbd5402ed17a79bd129b961bd8d6'), 'aesop':
LeanGitRepo(url='https://github.com/leanprover-community/aesop', commit='53ba96ad7666d4a2515292974631629b5ea5dfee'), 'proofwidgets': LeanGitRepo(url='https://github.com/leanprover-community/ProofWidgets4', commit='e6b
6247c61280c77ade6bbf0bc3c66a44fe2e0c5'), 'Cli': LeanGitRepo(url='https://github.com/leanprover/lean4-cli', commit='2cf1030dc2ae6b3632c84a09350b675ef3e347d0'), '«doc-gen4»': LeanGitRepo(url='https://github.com/leanprov
er/doc-gen4', commit='83f718b9055972dce4f92f5b3917426b91a0d2fe'), 'MD4Lean': LeanGitRepo(url='https://github.com/acmepjz/md4lean', commit='5e95f4776be5e048364f325c7e9d619bb56fb005'), 'UnicodeBasic': LeanGitRepo(url='h
ttps://github.com/fgdorais/lean4-unicode-basic', commit='9447739fe9714f8a091192bad5cd5e7b5a8ae1e4'), 'BibtexQuery': LeanGitRepo(url='https://github.com/dupuisf/BibtexQuery', commit='c138ab5c566c4268798b24bfcbea2f4c424
13cdd'), 'importGraph': LeanGitRepo(url='https://github.com/leanprover-community/import-graph', commit='0a756018b736ef4f4bc3c9a45fc03cf97a0b1a0c')}, root_dir=PosixPath('/data/yingzi_ma/lean_project/.cache/lean_dojo/le
anprover-community-mathlib4-2b29e73438e240a427bcecc7c0fe19306beb1310/mathlib4'))
2024-09-01 06:06:50.684 | INFO     | generate_benchmark_lean4:main:367 - Successfully traced the repo
2024-09-01 06:06:50.685 | WARNING  | generate_benchmark_lean4:main:372 - /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310 already exists. Using it instead.
2024-09-01 06:06:50.685 | INFO     | __main__:retrieve_proof:1090 - Finished generating benchmark at /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2421/2421 [00:00<00:00, 32631.84it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 116251/116251 [00:03<00:00, 32683.09it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2421/2421 [00:00<00:00, 34932.69it/s]
2024-09-01 06:07:00.367 | INFO     | __main__:retrieve_proof:1128 - Before adding new repo:
2024-09-01 06:07:00.367 | INFO     | dynamic_database:print_database_contents:607 - Current database contents:
2024-09-01 06:07:00.367 | INFO     | dynamic_database:add_repository:583 - Attempting to add repository: https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 06:07:00.367 | INFO     | dynamic_database:add_repository:586 - Added new repository: https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 06:07:00.367 | INFO     | __main__:retrieve_proof:1131 - After adding new repo:
2024-09-01 06:07:00.367 | INFO     | dynamic_database:print_database_contents:607 - Current database contents:
2024-09-01 06:07:00.367 | INFO     | dynamic_database:print_database_contents:609 -   - https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 06:07:22.341 | INFO     | __main__:retrieve_proof:1140 - Adding repo to repos_for_merged_dataset
2024-09-01 06:07:22.342 | INFO     | dynamic_database:generate_merged_dataset:399 - Merging selected repositories in the database:
2024-09-01 06:07:22.342 | INFO     | dynamic_database:generate_merged_dataset:401 -   - https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-01 06:08:21.735 | INFO     | __main__:retrieve_proof:1140 - Adding repo to repos_for_merged_dataset
2024-09-01 06:08:21.738 | INFO     | dynamic_database:generate_merged_dataset:399 - Merging selected repositories in the database:
2024-09-01 06:08:21.738 | INFO     | dynamic_database:generate_merged_dataset:401 -   - https://github.com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
^[[24;1R^[[25;9Ripdb> pn2024-09-01 06:10:54.551 | WARNING  | dynamic_database:generate_merged_dataset:418 - /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0f
e19306beb1310 already exists. Removing it now.
^[[42;1Ripdb> pn2024-09-01 06:11:48.122 | INFO     | __main__:main:1274 - An error occurred: Timed out after 1801 seconds waiting for clients. 1/4 clients joined.
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1254, in main
    search_github_repositories("Lean", num_repos)
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1146, in retrieve_proof
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 773, in train_test_fisher
    f.write("\n\n\n")
  File "/data/yingzi_ma/lean_project/ReProver/retrieval/main.py", line 58, in run_cli
    cli = CLI(PremiseRetriever, RetrievalDataModule)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/cli.py", line 388, in __init__
    self._run_subcommand(self.subcommand)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/cli.py", line 679, in _run_subcommand
    fn(**fn_kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in predict
    return call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 903, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 943, in _run
    self.strategy.setup_environment()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 154, in setup_environment
    self.setup_distributed()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 203, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/distributed.py", line 291, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 93, in wrapper
    func_return = func(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1361, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 258, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 185, in _create_c10d_store
    return TCPStore(
torch.distributed.DistStoreError: Timed out after 1801 seconds waiting for clients. 1/4 clients joined.
2024-09-01 06:11:49.085 | WARNING  | dynamic_database:generate_merged_dataset:418 - /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310 already ex
ists. Removing it now.
^[[47;1R^[[25;9R^[[25;17R^[[54;26R^[[47;35Ripdb> pn2024-09-01 06:12:26.165 | INFO     | dynamic_database:generate_merged_dataset:422 - Exported proofs to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged
_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
2024-09-01 06:12:27.153 | INFO     | dynamic_database:generate_merged_dataset:425 - Merged and exported corpus to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bce
cc7c0fe19306beb1310
2024-09-01 06:12:27.176 | INFO     | dynamic_database:generate_merged_dataset:428 - Exported traced files to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0
fe19306beb1310
2024-09-01 06:12:27.180 | INFO     | dynamic_database:generate_merged_dataset:431 - Exported metadata to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19
306beb1310
2024-09-01 06:12:27.217 | INFO     | __main__:find_latest_checkpoint:487 - Using the latest checkpoint: /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe
19306beb1310_lambda_0.1_epoch=0-Recall@10_val=58.95.ckpt
2024-09-01 06:12:27.217 | INFO     | __main__:retrieve_proof:1152 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb131
0_lambda_0.1_epoch=0-Recall@10_val=58.95.ckpt
2024-09-01 06:12:27.217 | INFO     | __main__:train_test_fisher:627 - Inside train_test_fisher
2024-09-01 06:12:27.218 | INFO     | __main__:train_test_fisher:628 - Starting training at epoch 0
[rank: 3] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default
 pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more
details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be load
ed via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of
the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
2024-09-01 06:12:31.262 | INFO     | __main__:train_test_fisher:652 - Loaded premise retriever at /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306b
eb1310_lambda_0.1_epoch=0-Recall@10_val=58.95.ckpt and reset epoch count
2024-09-01 06:12:31.272 | INFO     | __main__:find_latest_fisher:497 - Using the latest Fisher Information Matrix: /data/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/mathlib4_29dcec074de168ac2bf835a77ef68bbe069194
c5_fisher_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickl
e module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more detail
s). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via
 this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the lo
aded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(io.BytesIO(b))
2024-09-01 06:12:31.785 | INFO     | __main__:load_fisher_information:474 - Fisher Information successfully loaded.
2024-09-01 06:12:31.785 | INFO     | retrieval.model:set_fisher_info:92 - Fisher Information has been updated in the model.
2024-09-01 06:12:31.785 | INFO     | __main__:train_test_fisher:658 - Fisher Information Matrix loaded.
Data path: /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This
behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-01 06:12:31.892 | INFO     | common:__init__:208 - Building the corpus from /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310/corpus.jso
nl
 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 112975/116251 [00:27<00:00, 3828.42it/s]
2024-09-01 06:13:31.463 | INFO     | dynamic_database:generate_merged_dataset:422 - Exported proofs to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe1930
6beb1310
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 116251/116251 [00:28<00:00, 4121.32it/s]
2024-09-01 06:13:32.484 | INFO     | dynamic_database:generate_merged_dataset:425 - Merged and exported corpus to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bce
cc7c0fe19306beb1310
2024-09-01 06:13:32.508 | INFO     | dynamic_database:generate_merged_dataset:428 - Exported traced files to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0
fe19306beb1310
2024-09-01 06:13:32.513 | INFO     | dynamic_database:generate_merged_dataset:431 - Exported metadata to /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19
306beb1310
2024-09-01 06:13:32.559 | INFO     | __main__:find_latest_checkpoint:487 - Using the latest checkpoint: /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe
19306beb1310_lambda_0.1_epoch=0-Recall@10_val=58.95.ckpt
2024-09-01 06:13:32.559 | INFO     | __main__:retrieve_proof:1152 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb131
0_lambda_0.1_epoch=0-Recall@10_val=58.95.ckpt
2024-09-01 06:13:32.560 | INFO     | __main__:train_test_fisher:627 - Inside train_test_fisher
2024-09-01 06:13:32.560 | INFO     | __main__:train_test_fisher:628 - Starting training at epoch 0
[rank: 2] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default
 pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more
details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be load
ed via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of
the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
2024-09-01 06:13:34.942 | INFO     | retrieval.datamodule:load_or_cache_data:61 - Saved loaded data to cache /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0
fe19306beb1310/random/cache_train/cached_data.pkl
Training dataset size: 359583
2024-09-01 06:13:34.985 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19
306beb1310/random/cache_val/cached_data.pkl
Validation dataset size: 4874
2024-09-01 06:13:35.030 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19
306beb1310/random/cache_pred/cached_data.pkl
Testing dataset size: 4922
Training dataset size after load: 359583
Validation dataset size after load: 4874
Testing dataset size after load: 4922
2024-09-01 06:13:35.133 | INFO     | __main__:train_test_fisher:731 - Starting progressive training from epoch 0 to 1
2024-09-01 06:13:35.133 | INFO     | __main__:train_test_fisher:753 - Finished progressive training at epoch 0
2024-09-01 06:13:35.133 | WARNING  | __main__:train_test_fisher:763 - No best model found. Using the last trained model.
2024-09-01 06:13:35.134 | INFO     | __main__:train_test_fisher:769 - Testing...
2024-09-01 06:13:35.136 | INFO     | retrieval.main:run_cli:55 - PID: 1605628
[rank: 3] Seed set to 3407
2024-09-01 06:13:35.413 | INFO     | retrieval.main:before_instantiate_classes:28 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
/random
2024-09-01 06:13:35.413 | INFO     | retrieval.main:before_instantiate_classes:29 - Corpus path: /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb13
10/corpus.jsonl
2024-09-01 06:13:36.008 | INFO     | common:__init__:208 - Building the corpus from /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310/corpus.jso
nl
2024-09-01 06:13:36.796 | INFO     | __main__:train_test_fisher:652 - Loaded premise retriever at /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306b
eb1310_lambda_0.1_epoch=0-Recall@10_val=58.95.ckpt and reset epoch count
2024-09-01 06:13:36.797 | INFO     | __main__:find_latest_fisher:497 - Using the latest Fisher Information Matrix: /data/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/mathlib4_29dcec074de168ac2bf835a77ef68bbe069194
c5_fisher_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickl
e module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more detail
s). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via
 this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the lo
aded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(io.BytesIO(b))
2024-09-01 06:13:37.425 | INFO     | __main__:load_fisher_information:474 - Fisher Information successfully loaded.
2024-09-01 06:13:37.425 | INFO     | retrieval.model:set_fisher_info:92 - Fisher Information has been updated in the model.
2024-09-01 06:13:37.425 | INFO     | __main__:train_test_fisher:658 - Fisher Information Matrix loaded.
Data path: /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This
behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-01 06:13:37.528 | INFO     | common:__init__:208 - Building the corpus from /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310/corpus.jso
nl
[rank: 3] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 116251/116251 [00:27<00:00, 4198.65it/s]
2024-09-01 06:14:40.531 | INFO     | retrieval.datamodule:load_or_cache_data:61 - Saved loaded data to cache /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0
fe19306beb1310/random/cache_train/cached_data.pkl
Training dataset size: 359583
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2421/2421 [00:00<00:00, 4295.05it/s]
2024-09-01 06:14:41.235 | INFO     | retrieval.datamodule:load_or_cache_data:61 - Saved loaded data to cache /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0
fe19306beb1310/random/cache_val/cached_data.pkl
Validation dataset size: 4874
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2421/2421 [00:00<00:00, 4445.43it/s]
2024-09-01 06:14:41.913 | INFO     | retrieval.datamodule:load_or_cache_data:61 - Saved loaded data to cache /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0
fe19306beb1310/random/cache_pred/cached_data.pkl
Testing dataset size: 4922
Training dataset size after load: 359583
Validation dataset size after load: 4874
Testing dataset size after load: 4922
2024-09-01 06:14:42.025 | INFO     | __main__:train_test_fisher:731 - Starting progressive training from epoch 0 to 1
2024-09-01 06:14:42.025 | INFO     | __main__:train_test_fisher:753 - Finished progressive training at epoch 0
2024-09-01 06:14:42.026 | WARNING  | __main__:train_test_fisher:763 - No best model found. Using the last trained model.
2024-09-01 06:14:42.027 | INFO     | __main__:train_test_fisher:769 - Testing...
2024-09-01 06:14:42.029 | INFO     | retrieval.main:run_cli:55 - PID: 1605627
[rank: 2] Seed set to 3407
2024-09-01 06:14:42.295 | INFO     | retrieval.main:before_instantiate_classes:28 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310
/random
2024-09-01 06:14:42.295 | INFO     | retrieval.main:before_instantiate_classes:29 - Corpus path: /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb13
10/corpus.jsonl
2024-09-01 06:14:42.845 | INFO     | common:__init__:208 - Building the corpus from /data/yingzi_ma/lean_project/datasets_PT_single_repo_ewc/merged_with_new_mathlib4_2b29e73438e240a427bcecc7c0fe19306beb1310/corpus.jso
nl
[rank: 2] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
(ReProver) yingzi_ma@compute-permanent-node-834:~/lean_project/ReProver$ ;1R;1R;9R;1R;1R;9R;17R;26R;35R;;105Ripdb> pn
bash: syntax error near unexpected token `;'
(ReProver) yingzi_ma@compute-permanent-node-834:~/lean_project/ReProver$ ;66R;70R;74R5;78R0;83R;88R;92R;96R;1;110Ripdb> pn
