srun --partition=compute --gpus=4 --nodes=1 --time=2-00:00:00 --pty /bin/bash
(base) yingzi_ma@cais-login-0:~/lean_project/ReProver$ srun --partition=compute --gpus=4 --nodes=1 --time=2-00:00:00 --p
ty /bin/bash
srun: job 30328 queued and waiting for resources

srun: job 30328 has been allocated resources

(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1341
    clone_url = "https://github.com/lecopivo/SciLean.git"
IndentationError: unexpected indent
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
[2024-09-13 06:42:00,890] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 06:42:06.600 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:42:06.600 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:42:06.603 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:42:06.603 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:42:06.603 | INFO     | __main__:main:1210 - Starting the main process
2024-09-13 06:42:06.603 | INFO     | __main__:main:1218 - Loading database from /data/yingzi_ma/lean_project/dynamic_dat
abase_PT_single_repo_no_ewc.json
^Z
[1]+  Stopped                 bash run_code.sh
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
^Z
[2]+  Stopped                 bash run_code.sh
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
[2024-09-13 06:42:54,866] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 06:42:58.630 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:42:58.630 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:42:58.633 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:42:58.633 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:42:58.633 | INFO     | __main__:main:1210 - Starting the main process
2024-09-13 06:42:58.633 | INFO     | __main__:main:1218 - Loading database from /data/yingzi_ma/lean_project/dynamic_dat
abase_PT_single_repo_no_ewc.json
^Z
[3]+  Stopped                 bash run_code.sh
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
[2024-09-13 06:43:10,373] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 06:43:14.159 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:43:14.159 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:43:14.162 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:43:14.162 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:43:14.162 | INFO     | __main__:main:1210 - Starting the main process
2024-09-13 06:43:14.163 | INFO     | __main__:main:1218 - Loading database from /data/yingzi_ma/lean_project/dynamic_dat
abase_PT_single_repo_no_ewc.json
2024-09-13 06:43:34.543 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 06:43:34.543 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/lean
prover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 06:43:38.420 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/lecopivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 06:43:38.420 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/leco
pivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 06:43:38.707 | INFO     | __main__:main:1220 - Loaded database from /data/yingzi_ma/lean_project/dynamic_data
base_PT_single_repo_no_ewc.json
2024-09-13 06:43:38.707 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 06:43:38.708 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 06:43:39.125 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 06:44:23.915 | INFO     | __main__:main:1694 - An error occurred: Failed to read repository information after
 multiple attempts
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1356, in main
    with open(repo_info_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/yingzi_ma/lean_project/datasets_PT_single_repo_no_ewc/rep
o_info_compatible.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1361, in main
    raise Exception("Failed to read repository information after multiple attempts")
Exception: Failed to read repository information after multiple attempts
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
[2024-09-13 06:44:44,286] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 06:44:48.183 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:44:48.183 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:44:48.186 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:44:48.186 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:44:48.186 | INFO     | __main__:main:1210 - Starting the main process
2024-09-13 06:44:48.186 | INFO     | __main__:main:1218 - Loading database from /data/yingzi_ma/lean_project/dynamic_dat
abase_PT_single_repo_no_ewc.json
2024-09-13 06:45:08.798 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 06:45:08.798 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/lean
prover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 06:45:12.700 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/lecopivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 06:45:12.700 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/leco
pivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 06:45:12.986 | INFO     | __main__:main:1220 - Loaded database from /data/yingzi_ma/lean_project/dynamic_data
base_PT_single_repo_no_ewc.json
2024-09-13 06:45:12.986 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 06:45:12.986 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 06:45:13.263 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 06:45:29.363 | INFO     | __main__:main:1347 - Finding compatible repositories...
2024-09-13 06:45:29.366 | INFO     | __main__:main:1350 - Finished finding compatible repositories
2024-09-13 06:45:29.366 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:45:29.366 | INFO     | __main__:main:1369 - i: 0
2024-09-13 06:45:29.366 | INFO     | __main__:main:1375 - Main process
2024-09-13 06:45:29.366 | INFO     | __main__:main:1376 - Using lambda = 0.1
2024-09-13 06:45:29.366 | INFO     | __main__:main:1377 - Processing https://github.com/lecopivo/SciLean
2024-09-13 06:45:29.367 | INFO     | __main__:main:1398 - Adding repo to repos_for_merged_dataset
2024-09-13 06:45:29.367 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 06:45:29.367 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:45:29.367 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:45:29.367 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 06:45:29.367 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 0] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 06:45:32.365 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 06:45:32.366 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 06:45:32.879 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 06:45:32.879 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 06:45:32.879 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204
: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM,
prepend your python command with `srun` like so: srun python main.py ...
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
2024-09-13 06:45:32.983 | INFO     | __main__:main:1505 - right before barrier for data module
2024-09-13 06:45:32.983 | INFO     | __main__:main:1520 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 06:45:33.087 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 06:45:42.126 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:45:42.140 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:45:42.155 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:45:42.155 | INFO     | __main__:main:1534 - Training dataset size after load: 149228
2024-09-13 06:45:42.155 | INFO     | __main__:main:1535 - Validation dataset size after load: 2087
2024-09-13 06:45:42.155 | INFO     | __main__:main:1536 - Testing dataset size after load: 2298
2024-09-13 06:45:42.155 | INFO     | __main__:main:1538 - Starting progressive training from epoch 1 to 2
2024-09-13 06:45:42.155 | INFO     | __main__:main:1541 - hit the barrier before training
[rank: 0] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
[2024-09-13 06:45:47,840] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 06:45:47,845] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 06:45:47,846] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 06:45:51.962 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:45:51.962 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:45:51.962 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:45:51.963 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:45:51.963 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:45:51.963 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:45:51.965 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:45:51.965 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:45:51.965 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:45:51.965 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:45:51.966 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:45:51.966 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 06:45:51.966 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:45:51.966 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 06:45:51.966 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 06:45:51.966 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 06:45:51.966 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 06:45:51.966 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 06:45:52.152 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 06:45:52.162 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 06:45:52.176 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 06:46:08.110 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:46:08.110 | INFO     | __main__:main:1369 - i: 0
2024-09-13 06:46:08.110 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 06:46:08.111 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:46:08.111 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:46:08.111 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 06:46:08.111 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 2] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 06:46:08.391 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:46:08.391 | INFO     | __main__:main:1369 - i: 0
2024-09-13 06:46:08.391 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 06:46:08.392 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:46:08.392 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:46:08.392 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 06:46:08.392 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 3] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 06:46:08.501 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:46:08.501 | INFO     | __main__:main:1369 - i: 0
2024-09-13 06:46:08.501 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 06:46:08.501 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:46:08.501 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:46:08.501 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 06:46:08.502 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 1] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 06:46:10.575 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 06:46:10.576 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 06:46:10.683 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 06:46:10.684 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 06:46:10.855 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 06:46:10.856 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 06:46:11.231 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 06:46:11.231 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 06:46:11.231 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
2024-09-13 06:46:11.285 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 06:46:11.286 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 06:46:11.286 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
2024-09-13 06:46:11.315 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 06:46:11.315 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 06:46:11.315 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
2024-09-13 06:46:11.340 | INFO     | __main__:main:1505 - right before barrier for data module
2024-09-13 06:46:11.340 | INFO     | __main__:main:1505 - right before barrier for data module
2024-09-13 06:46:11.341 | INFO     | __main__:main:1520 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
2024-09-13 06:46:11.341 | INFO     | __main__:main:1520 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
2024-09-13 06:46:11.359 | INFO     | __main__:main:1505 - right before barrier for data module
2024-09-13 06:46:11.359 | INFO     | __main__:main:1520 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 06:46:11.436 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 06:46:11.436 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 06:46:11.460 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 06:46:21.374 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:46:21.386 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:46:21.398 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:46:21.398 | INFO     | __main__:main:1534 - Training dataset size after load: 149228
2024-09-13 06:46:21.398 | INFO     | __main__:main:1535 - Validation dataset size after load: 2087
2024-09-13 06:46:21.398 | INFO     | __main__:main:1536 - Testing dataset size after load: 2298
2024-09-13 06:46:21.398 | INFO     | __main__:main:1538 - Starting progressive training from epoch 1 to 2
2024-09-13 06:46:21.398 | INFO     | __main__:main:1541 - hit the barrier before training
[rank: 2] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
2024-09-13 06:46:27.700 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:46:27.719 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:46:27.739 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:46:27.739 | INFO     | __main__:main:1534 - Training dataset size after load: 149228
2024-09-13 06:46:27.739 | INFO     | __main__:main:1535 - Validation dataset size after load: 2087
2024-09-13 06:46:27.739 | INFO     | __main__:main:1536 - Testing dataset size after load: 2298
2024-09-13 06:46:27.739 | INFO     | __main__:main:1538 - Starting progressive training from epoch 1 to 2
2024-09-13 06:46:27.739 | INFO     | __main__:main:1541 - hit the barrier before training
2024-09-13 06:46:27.908 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:46:27.920 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:46:27.931 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:46:27.932 | INFO     | __main__:main:1534 - Training dataset size after load: 149228
2024-09-13 06:46:27.932 | INFO     | __main__:main:1535 - Validation dataset size after load: 2087
2024-09-13 06:46:27.932 | INFO     | __main__:main:1536 - Testing dataset size after load: 2298
2024-09-13 06:46:27.932 | INFO     | __main__:main:1538 - Starting progressive training from epoch 1 to 2
2024-09-13 06:46:27.932 | INFO     | __main__:main:1541 - hit the barrier before training
[rank: 1] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
[rank: 3] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

NCCL version 2.20.5+cuda12.4
2024-09-13 06:46:30.259 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:46:30.350 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:46:30.368 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:65
3: Checkpoint directory /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_no_ewc exists and is not empty.
2024-09-13 06:46:31.489 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:46:31.567 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:46:31.582 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:46:31.628 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
2024-09-13 06:46:31.650 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:46:31.708 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
Training dataset size: 149228
2024-09-13 06:46:31.723 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:46:31.731 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:46:31.745 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
Restoring states from the checkpoint path at /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_
new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_val=70.07.ckpt
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
2024-09-13 06:46:32.874 | INFO     | common:get_optimizers:449 - Optimizing with AdamW
2024-09-13 06:46:32.874 | INFO     | common:get_optimizers:449 - Optimizing with AdamW
2024-09-13 06:46:32.875 | INFO     | common:get_optimizers:449 - Optimizing with AdamW
2024-09-13 06:46:32.875 | INFO     | common:get_optimizers:449 - Optimizing with AdamW

  | Name    | Type           | Params
-------------------------------------------
0 | encoder | T5EncoderModel | 217 M
-------------------------------------------
217 M     Trainable params
0         Non-trainable params
217 M     Total params
870.630   Total estimated model params size (MB)
Restored all states from the checkpoint at /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_ne
w_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_val=70.07.ckpt
`Trainer.fit` stopped: `max_epochs=2` reached.
2024-09-13 06:46:35.461 | INFO     | __main__:main:1544 - hit the barrier after training
2024-09-13 06:46:35.650 | INFO     | __main__:main:1544 - hit the barrier after training
2024-09-13 06:46:35.799 | INFO     | __main__:main:1544 - hit the barrier after training
2024-09-13 06:46:35.955 | INFO     | __main__:main:1544 - hit the barrier after training
2024-09-13 06:46:35.955 | INFO     | __main__:main:1550 - Finished progressive training at epoch 2
2024-09-13 06:46:35.955 | INFO     | __main__:main:1550 - Finished progressive training at epoch 2
2024-09-13 06:46:35.955 | INFO     | __main__:main:1550 - Finished progressive training at epoch 2
2024-09-13 06:46:35.955 | INFO     | __main__:main:1550 - Finished progressive training at epoch 2
2024-09-13 06:46:35.956 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:46:35.956 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:46:35.956 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:46:35.956 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:46:35.956 | INFO     | __main__:main:1557 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:46:35.956 | INFO     | __main__:main:1557 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:46:35.956 | INFO     | __main__:main:1557 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:46:35.956 | INFO     | __main__:main:1557 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:46:37.949 | INFO     | __main__:main:1566 - Testing...
2024-09-13 06:46:37.954 | INFO     | retrieval.main:run_cli:60 - PID: 2277849
2024-09-13 06:46:38.162 | INFO     | __main__:main:1566 - Testing...
2024-09-13 06:46:38.170 | INFO     | retrieval.main:run_cli:60 - PID: 2277299
[rank: 2] Seed set to 3407
2024-09-13 06:46:38.267 | INFO     | retrieval.main:before_instantiate_classes:33 - Data path: /data/yingzi_ma/lean_proj
ect/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
2024-09-13 06:46:38.268 | INFO     | retrieval.main:before_instantiate_classes:34 - Corpus path: /data/yingzi_ma/lean_pr
oject/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
[rank: 0] Seed set to 3407
2024-09-13 06:46:38.358 | INFO     | retrieval.main:before_instantiate_classes:33 - Data path: /data/yingzi_ma/lean_proj
ect/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
2024-09-13 06:46:38.358 | INFO     | retrieval.main:before_instantiate_classes:34 - Corpus path: /data/yingzi_ma/lean_pr
oject/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 06:46:38.362 | INFO     | __main__:main:1566 - Testing...
2024-09-13 06:46:38.363 | INFO     | retrieval.main:run_cli:60 - PID: 2277848
2024-09-13 06:46:38.465 | INFO     | __main__:main:1566 - Testing...
2024-09-13 06:46:38.465 | INFO     | retrieval.main:run_cli:60 - PID: 2277850
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
[rank: 1] Seed set to 3407
2024-09-13 06:46:38.564 | INFO     | retrieval.main:before_instantiate_classes:33 - Data path: /data/yingzi_ma/lean_proj
ect/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
2024-09-13 06:46:38.564 | INFO     | retrieval.main:before_instantiate_classes:34 - Corpus path: /data/yingzi_ma/lean_pr
oject/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
[rank: 3] Seed set to 3407
2024-09-13 06:46:38.656 | INFO     | retrieval.main:before_instantiate_classes:33 - Data path: /data/yingzi_ma/lean_proj
ect/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
2024-09-13 06:46:38.657 | INFO     | retrieval.main:before_instantiate_classes:34 - Corpus path: /data/yingzi_ma/lean_pr
oject/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 06:46:38.889 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 06:46:38.892 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 06:46:39.205 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 06:46:39.235 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
[rank: 3] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204
: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM,
prepend your python command with `srun` like so: srun python main.py predict --config retrieval/confs/cli_lean4_r ...
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[rank: 0] Seed set to 3407
[rank: 2] Seed set to 3407
[rank: 1] Seed set to 3407
2024-09-13 06:46:51.253 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:46:51.268 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:46:55.505 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:46:55.519 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:46:58.148 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:46:58.170 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:46:58.223 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:46:58.241 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
Restoring states from the checkpoint path at /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_
new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_val=70.07.ckpt
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
Loaded model weights from the checkpoint at /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_n
ew_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_val=70.07.ckpt
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
2024-09-13 06:47:01.251 | INFO     | retrieval.model:on_predict_start:447 - Embeddings staled on predict start: True
2024-09-13 06:47:01.252 | INFO     | retrieval.model:reindex_corpus:291 - Re-indexing the retrieval corpus
Predicting: |                                                                                     | 0/? [00:00<?, ?it/s]
2024-09-13 06:47:01.302 | INFO     | retrieval.model:on_predict_start:447 - Embeddings staled on predict start: True
2024-09-13 06:47:01.303 | INFO     | retrieval.model:reindex_corpus:291 - Re-indexing the retrieval corpus
                                                                                                                       2
024-09-13 06:47:01.443 | INFO     | retrieval.model:on_predict_start:447 - Embeddings staled on predict start: Trueit/s]
2024-09-13 06:47:01.444 | INFO     | retrieval.model:reindex_corpus:291 - Re-indexing the retrieval corpus
  0%|                                                                                          | 0/1692 [00:00<?, ?it/s]
2024-09-13 06:47:01.476 | INFO     | retrieval.model:on_predict_start:447 - Embeddings staled on predict start: True
2024-09-13 06:47:01.476 | INFO     | retrieval.model:reindex_corpus:291 - Re-indexing the retrieval corpus
  8%|██████▌                                                                         | 139/1692 [00:48<13:45,  1.88it/s^
Z 8%|██████▌                                                                         | 139/1692 [00:48<13:48,  1.88it/s]
[4]+  Stopped                 bash run_code.sh
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
[2024-09-13 06:48:29,361] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 06:48:33.233 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:48:33.233 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:48:33.236 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:48:33.236 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:48:33.236 | INFO     | __main__:main:1210 - Starting the main process
2024-09-13 06:48:33.236 | INFO     | __main__:main:1218 - Loading database from /data/yingzi_ma/lean_project/dynamic_dat
abase_PT_single_repo_no_ewc.json
^Z
[5]+  Stopped                 bash run_code.sh
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
[2024-09-13 06:49:01,357] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 06:49:05.219 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:49:05.219 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:49:05.222 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:49:05.222 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:49:05.222 | INFO     | __main__:main:1210 - Starting the main process
2024-09-13 06:49:05.222 | INFO     | __main__:main:1218 - Loading database from /data/yingzi_ma/lean_project/dynamic_dat
abase_PT_single_repo_no_ewc.json
2024-09-13 06:49:27.330 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 06:49:27.330 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/lean
prover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 06:49:31.468 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/lecopivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 06:49:31.468 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/leco
pivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 06:49:31.791 | INFO     | __main__:main:1220 - Loaded database from /data/yingzi_ma/lean_project/dynamic_data
base_PT_single_repo_no_ewc.json
2024-09-13 06:49:31.791 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 06:49:31.791 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 06:49:32.159 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 06:49:47.877 | INFO     | __main__:main:1347 - Finding compatible repositories...
2024-09-13 06:49:47.880 | INFO     | __main__:main:1350 - Finished finding compatible repositories
2024-09-13 06:49:47.880 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:49:47.880 | INFO     | __main__:main:1369 - i: 0
2024-09-13 06:49:47.880 | INFO     | __main__:main:1375 - Main process
2024-09-13 06:49:47.880 | INFO     | __main__:main:1376 - Using lambda = 0.1
2024-09-13 06:49:47.880 | INFO     | __main__:main:1377 - Processing https://github.com/lecopivo/SciLean
2024-09-13 06:49:47.880 | INFO     | __main__:main:1398 - Adding repo to repos_for_merged_dataset
2024-09-13 06:49:47.880 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 06:49:47.881 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:49:47.881 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:49:47.881 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 06:49:47.881 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 0] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 06:49:49.911 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 06:49:49.912 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 06:49:50.252 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 06:49:50.252 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 06:49:50.252 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204
: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM,
prepend your python command with `srun` like so: srun python main.py ...
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
`Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
2024-09-13 06:49:50.361 | INFO     | __main__:main:1507 - right before barrier for data module
2024-09-13 06:49:50.362 | INFO     | __main__:main:1522 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 06:49:50.520 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 06:49:59.836 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:49:59.850 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:49:59.863 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:49:59.863 | INFO     | __main__:main:1536 - Training dataset size after load: 149228
2024-09-13 06:49:59.863 | INFO     | __main__:main:1537 - Validation dataset size after load: 2087
2024-09-13 06:49:59.863 | INFO     | __main__:main:1538 - Testing dataset size after load: 2298
2024-09-13 06:49:59.863 | INFO     | __main__:main:1540 - Starting progressive training from epoch 1 to 2
2024-09-13 06:49:59.863 | INFO     | __main__:main:1543 - hit the barrier before training
[rank: 0] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
[2024-09-13 06:50:05,397] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 06:50:05,400] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 06:50:05,400] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 06:50:09.414 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:50:09.414 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:50:09.414 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:50:09.414 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:50:09.414 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:50:09.414 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:50:09.417 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:50:09.417 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:50:09.417 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:50:09.417 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:50:09.417 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:50:09.418 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 06:50:09.418 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 06:50:09.418 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:50:09.418 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 06:50:09.418 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 06:50:09.418 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 06:50:09.418 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 06:50:09.614 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 06:50:09.619 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 06:50:09.637 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 06:50:25.748 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:50:25.748 | INFO     | __main__:main:1369 - i: 0
2024-09-13 06:50:25.748 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 06:50:25.749 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:50:25.749 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:50:25.749 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 06:50:25.749 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 1] Seed set to 3407
2024-09-13 06:50:25.791 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:50:25.791 | INFO     | __main__:main:1369 - i: 0
2024-09-13 06:50:25.791 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 06:50:25.792 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:50:25.792 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:50:25.792 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 06:50:25.792 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 2] Seed set to 3407
2024-09-13 06:50:25.844 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:50:25.844 | INFO     | __main__:main:1369 - i: 0
2024-09-13 06:50:25.844 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 06:50:25.845 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:50:25.845 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:50:25.845 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 06:50:25.845 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 3] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 06:50:28.628 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 06:50:28.629 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 06:50:28.731 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 06:50:28.731 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 06:50:28.789 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 06:50:28.789 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 06:50:29.232 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 06:50:29.232 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 06:50:29.232 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
2024-09-13 06:50:29.269 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 06:50:29.269 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 06:50:29.269 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
2024-09-13 06:50:29.335 | INFO     | __main__:main:1507 - right before barrier for data module
2024-09-13 06:50:29.335 | INFO     | __main__:main:1522 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
2024-09-13 06:50:29.335 | INFO     | __main__:main:1507 - right before barrier for data module
2024-09-13 06:50:29.336 | INFO     | __main__:main:1522 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 06:50:29.429 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 06:50:29.446 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 06:50:29.630 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 06:50:29.630 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 06:50:29.630 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
2024-09-13 06:50:29.681 | INFO     | __main__:main:1507 - right before barrier for data module
2024-09-13 06:50:29.681 | INFO     | __main__:main:1522 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 06:50:29.773 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 06:50:40.043 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:50:40.056 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:50:40.068 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:50:40.068 | INFO     | __main__:main:1536 - Training dataset size after load: 149228
2024-09-13 06:50:40.068 | INFO     | __main__:main:1537 - Validation dataset size after load: 2087
2024-09-13 06:50:40.068 | INFO     | __main__:main:1538 - Testing dataset size after load: 2298
2024-09-13 06:50:40.068 | INFO     | __main__:main:1540 - Starting progressive training from epoch 1 to 2
2024-09-13 06:50:40.068 | INFO     | __main__:main:1543 - hit the barrier before training
[rank: 2] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
2024-09-13 06:50:40.527 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:50:40.540 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:50:40.554 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:50:40.554 | INFO     | __main__:main:1536 - Training dataset size after load: 149228
2024-09-13 06:50:40.554 | INFO     | __main__:main:1537 - Validation dataset size after load: 2087
2024-09-13 06:50:40.555 | INFO     | __main__:main:1538 - Testing dataset size after load: 2298
2024-09-13 06:50:40.555 | INFO     | __main__:main:1540 - Starting progressive training from epoch 1 to 2
2024-09-13 06:50:40.555 | INFO     | __main__:main:1543 - hit the barrier before training
[rank: 3] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
2024-09-13 06:50:41.036 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:50:41.047 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:50:41.060 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:50:41.060 | INFO     | __main__:main:1536 - Training dataset size after load: 149228
2024-09-13 06:50:41.060 | INFO     | __main__:main:1537 - Validation dataset size after load: 2087
2024-09-13 06:50:41.060 | INFO     | __main__:main:1538 - Testing dataset size after load: 2298
2024-09-13 06:50:41.060 | INFO     | __main__:main:1540 - Starting progressive training from epoch 1 to 2
2024-09-13 06:50:41.060 | INFO     | __main__:main:1543 - hit the barrier before training
[rank: 1] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

NCCL version 2.20.5+cuda12.4
2024-09-13 06:50:43.031 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:50:43.145 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:50:43.170 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:65
3: Checkpoint directory /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_no_ewc exists and is not empty.
2024-09-13 06:50:44.476 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:50:44.560 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:50:44.565 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
2024-09-13 06:50:44.572 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
2024-09-13 06:50:44.575 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
Training dataset size: 149228
Training dataset size: 149228
2024-09-13 06:50:44.651 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:50:44.657 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:50:44.666 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:50:44.673 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
Restoring states from the checkpoint path at /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_
new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_val=70.07.ckpt
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
2024-09-13 06:50:45.803 | INFO     | common:get_optimizers:449 - Optimizing with AdamW
2024-09-13 06:50:45.803 | INFO     | common:get_optimizers:449 - Optimizing with AdamW
2024-09-13 06:50:45.804 | INFO     | common:get_optimizers:449 - Optimizing with AdamW
2024-09-13 06:50:45.804 | INFO     | common:get_optimizers:449 - Optimizing with AdamW

  | Name    | Type           | Params
-------------------------------------------
0 | encoder | T5EncoderModel | 217 M
-------------------------------------------
217 M     Trainable params
0         Non-trainable params
217 M     Total params
870.630   Total estimated model params size (MB)
Restored all states from the checkpoint at /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_ne
w_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_val=70.07.ckpt
`Trainer.fit` stopped: `max_epochs=2` reached.
2024-09-13 06:50:48.977 | INFO     | __main__:main:1546 - hit the barrier after training
2024-09-13 06:50:49.184 | INFO     | __main__:main:1546 - hit the barrier after training
2024-09-13 06:50:49.257 | INFO     | __main__:main:1546 - hit the barrier after training
2024-09-13 06:50:49.327 | INFO     | __main__:main:1546 - hit the barrier after training
2024-09-13 06:50:49.327 | INFO     | __main__:main:1552 - Finished progressive training at epoch 2
2024-09-13 06:50:49.327 | INFO     | __main__:main:1552 - Finished progressive training at epoch 2
2024-09-13 06:50:49.327 | INFO     | __main__:main:1552 - Finished progressive training at epoch 2
2024-09-13 06:50:49.327 | INFO     | __main__:main:1552 - Finished progressive training at epoch 2
2024-09-13 06:50:49.328 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:50:49.328 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:50:49.328 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:50:49.328 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:50:49.328 | INFO     | __main__:main:1559 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:50:49.328 | INFO     | __main__:main:1559 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:50:49.328 | INFO     | __main__:main:1559 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:50:49.328 | INFO     | __main__:main:1559 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:50:51.509 | INFO     | __main__:main:1625 - Calculating Fisher Information Matrix for EWC
2024-09-13 06:50:51.509 | INFO     | __main__:main:1629 - right before barrier fisher
2024-09-13 06:50:51.769 | INFO     | __main__:main:1625 - Calculating Fisher Information Matrix for EWC
2024-09-13 06:50:51.770 | INFO     | __main__:main:1629 - right before barrier fisher
2024-09-13 06:50:51.780 | INFO     | __main__:main:1625 - Calculating Fisher Information Matrix for EWC
2024-09-13 06:50:51.780 | INFO     | __main__:main:1629 - right before barrier fisher
2024-09-13 06:50:52.023 | INFO     | __main__:main:1625 - Calculating Fisher Information Matrix for EWC
2024-09-13 06:50:52.023 | INFO     | __main__:main:1629 - right before barrier fisher
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204
: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM,
prepend your python command with `srun` like so: srun python main.py ...
[rank: 1] Seed set to 3407
[rank: 3] Seed set to 3407
[rank: 2] Seed set to 3407
[rank: 0] Seed set to 3407
2024-09-13 06:50:55.350 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:50:55.753 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
2024-09-13 06:50:55.796 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
Training dataset size: 149228
2024-09-13 06:50:56.699 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
An error occurred during fisher: `test_dataloader` must be implemented to be used with the Lightning Trainer
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1631, in main
    trainer.test(model, datamodule=data_module)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 754, in test
    return call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 4
3, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/sub
process_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 987, in _run
    results = self._run_stage()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 1026, in _run_stage
    return self._evaluation_loop.run()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", lin
e 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 110, in run
    self.setup_data()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 166, in setup_data
    dataloaders = _request_dataloader(source)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_
connector.py", line 342, in _request_dataloader
    return data_source.dataloader()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_
connector.py", line 309, in dataloader
    return call._call_lightning_datamodule_hook(self.instance.trainer, self.name)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 1
79, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/core/hooks.py", line 510
, in test_dataloader
    raise MisconfigurationException("`test_dataloader` must be implemented to be used with the Lightning Trainer")
lightning_fabric.utilities.exceptions.MisconfigurationException: `test_dataloader` must be implemented to be used with t
he Lightning Trainer

2024-09-13 06:50:57.355 | INFO     | __main__:main:1692 - Finished processing the repository
2024-09-13 06:50:57.355 | INFO     | __main__:main:1694 - current epoch: 2
2024-09-13 06:50:57.355 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:50:57.355 | INFO     | __main__:main:1369 - i: 1
2024-09-13 06:50:57.355 | INFO     | __main__:main:1696 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1370, in main
    repo = lean_git_repos[i]
IndexError: list index out of range
An error occurred during fisher: `test_dataloader` must be implemented to be used with the Lightning Trainer
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1631, in main
    trainer.test(model, datamodule=data_module)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 754, in test
    return call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 4
3, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/sub
process_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 987, in _run
    results = self._run_stage()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 1026, in _run_stage
    return self._evaluation_loop.run()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", lin
e 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 110, in run
    self.setup_data()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 166, in setup_data
    dataloaders = _request_dataloader(source)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_
connector.py", line 342, in _request_dataloader
    return data_source.dataloader()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_
connector.py", line 309, in dataloader
    return call._call_lightning_datamodule_hook(self.instance.trainer, self.name)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 1
79, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/core/hooks.py", line 510
, in test_dataloader
    raise MisconfigurationException("`test_dataloader` must be implemented to be used with the Lightning Trainer")
lightning_fabric.utilities.exceptions.MisconfigurationException: `test_dataloader` must be implemented to be used with t
he Lightning Trainer

2024-09-13 06:50:57.404 | INFO     | __main__:main:1692 - Finished processing the repository
2024-09-13 06:50:57.404 | INFO     | __main__:main:1694 - current epoch: 2
2024-09-13 06:50:57.405 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:50:57.405 | INFO     | __main__:main:1369 - i: 1
2024-09-13 06:50:57.405 | INFO     | __main__:main:1696 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1370, in main
    repo = lean_git_repos[i]
IndexError: list index out of range
An error occurred during fisher: `test_dataloader` must be implemented to be used with the Lightning Trainer
An error occurred during fisher: `test_dataloader` must be implemented to be used with the Lightning Trainer
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1631, in main
    trainer.test(model, datamodule=data_module)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 754, in test
    return call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 4
3, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/sub
process_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 987, in _run
    results = self._run_stage()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 1026, in _run_stage
    return self._evaluation_loop.run()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", lin
e 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 110, in run
    self.setup_data()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 166, in setup_data
    dataloaders = _request_dataloader(source)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_
connector.py", line 342, in _request_dataloader
    return data_source.dataloader()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_
connector.py", line 309, in dataloader
    return call._call_lightning_datamodule_hook(self.instance.trainer, self.name)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 1
79, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/core/hooks.py", line 510
, in test_dataloader
    raise MisconfigurationException("`test_dataloader` must be implemented to be used with the Lightning Trainer")
lightning_fabric.utilities.exceptions.MisconfigurationException: `test_dataloader` must be implemented to be used with t
he Lightning Trainer

2024-09-13 06:50:57.486 | INFO     | __main__:main:1692 - Finished processing the repository
2024-09-13 06:50:57.486 | INFO     | __main__:main:1694 - current epoch: 2
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1631, in main
    trainer.test(model, datamodule=data_module)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 754, in test
    return call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 4
3, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/sub
process_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 987, in _run
    results = self._run_stage()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 1026, in _run_stage
    return self._evaluation_loop.run()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", lin
e 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 110, in run
    self.setup_data()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 166, in setup_data
    dataloaders = _request_dataloader(source)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_
connector.py", line 342, in _request_dataloader
    return data_source.dataloader()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_
connector.py", line 309, in dataloader
    return call._call_lightning_datamodule_hook(self.instance.trainer, self.name)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 1
79, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/core/hooks.py", line 510
, in test_dataloader
    raise MisconfigurationException("`test_dataloader` must be implemented to be used with the Lightning Trainer")
lightning_fabric.utilities.exceptions.MisconfigurationException: `test_dataloader` must be implemented to be used with t
he Lightning Trainer

2024-09-13 06:50:57.486 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:50:57.486 | INFO     | __main__:main:1369 - i: 1
2024-09-13 06:50:57.486 | INFO     | __main__:main:1692 - Finished processing the repository
2024-09-13 06:50:57.487 | INFO     | __main__:main:1696 - An error occurred: list index out of range
2024-09-13 06:50:57.487 | INFO     | __main__:main:1694 - current epoch: 2
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1370, in main
    repo = lean_git_repos[i]
IndexError: list index out of range
2024-09-13 06:50:57.487 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:50:57.487 | INFO     | __main__:main:1369 - i: 1
2024-09-13 06:50:57.487 | INFO     | __main__:main:1696 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1370, in main
    repo = lean_git_repos[i]
IndexError: list index out of range
[rank0]:[W913 06:51:01.716522428 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed befor
e we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that
 any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and bl
ock the progress of another member of the process group. This constraint has always been present,  but this warning has
only been added since PyTorch 2.4 (function operator())
^Z
[6]+  Stopped                 bash run_code.sh
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$
