srun --partition=compute --gpus=4 --nodes=1 --time=2-00:00:00 --pty /bin/bash
(base) yingzi_ma@cais-login-0:~/lean_project/ReProver$ srun --partition=compute --gpus=4 --nodes=1 --time=2-00:00:00 --p
ty /bin/bash
srun: job 30328 queued and waiting for resources

srun: job 30328 has been allocated resources

(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1341
    clone_url = "https://github.com/lecopivo/SciLean.git"
IndentationError: unexpected indent
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
[2024-09-13 06:42:00,890] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 06:42:06.600 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:42:06.600 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:42:06.603 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:42:06.603 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:42:06.603 | INFO     | __main__:main:1210 - Starting the main process
2024-09-13 06:42:06.603 | INFO     | __main__:main:1218 - Loading database from /data/yingzi_ma/lean_project/dynamic_dat
abase_PT_single_repo_no_ewc.json
^Z
[1]+  Stopped                 bash run_code.sh
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
^Z
[2]+  Stopped                 bash run_code.sh
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
[2024-09-13 06:42:54,866] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 06:42:58.630 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:42:58.630 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:42:58.633 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:42:58.633 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:42:58.633 | INFO     | __main__:main:1210 - Starting the main process
2024-09-13 06:42:58.633 | INFO     | __main__:main:1218 - Loading database from /data/yingzi_ma/lean_project/dynamic_dat
abase_PT_single_repo_no_ewc.json
^Z
[3]+  Stopped                 bash run_code.sh
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
[2024-09-13 06:43:10,373] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 06:43:14.159 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:43:14.159 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:43:14.162 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:43:14.162 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:43:14.162 | INFO     | __main__:main:1210 - Starting the main process
2024-09-13 06:43:14.163 | INFO     | __main__:main:1218 - Loading database from /data/yingzi_ma/lean_project/dynamic_dat
abase_PT_single_repo_no_ewc.json
2024-09-13 06:43:34.543 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 06:43:34.543 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/lean
prover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 06:43:38.420 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/lecopivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 06:43:38.420 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/leco
pivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 06:43:38.707 | INFO     | __main__:main:1220 - Loaded database from /data/yingzi_ma/lean_project/dynamic_data
base_PT_single_repo_no_ewc.json
2024-09-13 06:43:38.707 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 06:43:38.708 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 06:43:39.125 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 06:44:23.915 | INFO     | __main__:main:1694 - An error occurred: Failed to read repository information after
 multiple attempts
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1356, in main
    with open(repo_info_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/yingzi_ma/lean_project/datasets_PT_single_repo_no_ewc/rep
o_info_compatible.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1361, in main
    raise Exception("Failed to read repository information after multiple attempts")
Exception: Failed to read repository information after multiple attempts
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
[2024-09-13 06:44:44,286] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 06:44:48.183 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:44:48.183 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:44:48.186 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:44:48.186 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:44:48.186 | INFO     | __main__:main:1210 - Starting the main process
2024-09-13 06:44:48.186 | INFO     | __main__:main:1218 - Loading database from /data/yingzi_ma/lean_project/dynamic_dat
abase_PT_single_repo_no_ewc.json
2024-09-13 06:45:08.798 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 06:45:08.798 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/lean
prover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 06:45:12.700 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/lecopivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 06:45:12.700 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/leco
pivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 06:45:12.986 | INFO     | __main__:main:1220 - Loaded database from /data/yingzi_ma/lean_project/dynamic_data
base_PT_single_repo_no_ewc.json
2024-09-13 06:45:12.986 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 06:45:12.986 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 06:45:13.263 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 06:45:29.363 | INFO     | __main__:main:1347 - Finding compatible repositories...
2024-09-13 06:45:29.366 | INFO     | __main__:main:1350 - Finished finding compatible repositories
2024-09-13 06:45:29.366 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:45:29.366 | INFO     | __main__:main:1369 - i: 0
2024-09-13 06:45:29.366 | INFO     | __main__:main:1375 - Main process
2024-09-13 06:45:29.366 | INFO     | __main__:main:1376 - Using lambda = 0.1
2024-09-13 06:45:29.366 | INFO     | __main__:main:1377 - Processing https://github.com/lecopivo/SciLean
2024-09-13 06:45:29.367 | INFO     | __main__:main:1398 - Adding repo to repos_for_merged_dataset
2024-09-13 06:45:29.367 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 06:45:29.367 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:45:29.367 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:45:29.367 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 06:45:29.367 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 0] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 06:45:32.365 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 06:45:32.366 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 06:45:32.879 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 06:45:32.879 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 06:45:32.879 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204
: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM,
prepend your python command with `srun` like so: srun python main.py ...
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
2024-09-13 06:45:32.983 | INFO     | __main__:main:1505 - right before barrier for data module
2024-09-13 06:45:32.983 | INFO     | __main__:main:1520 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 06:45:33.087 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 06:45:42.126 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:45:42.140 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:45:42.155 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:45:42.155 | INFO     | __main__:main:1534 - Training dataset size after load: 149228
2024-09-13 06:45:42.155 | INFO     | __main__:main:1535 - Validation dataset size after load: 2087
2024-09-13 06:45:42.155 | INFO     | __main__:main:1536 - Testing dataset size after load: 2298
2024-09-13 06:45:42.155 | INFO     | __main__:main:1538 - Starting progressive training from epoch 1 to 2
2024-09-13 06:45:42.155 | INFO     | __main__:main:1541 - hit the barrier before training
[rank: 0] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
[2024-09-13 06:45:47,840] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 06:45:47,845] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 06:45:47,846] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 06:45:51.962 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:45:51.962 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:45:51.962 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 06:45:51.963 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:45:51.963 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:45:51.963 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 06:45:51.965 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:45:51.965 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:45:51.965 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:45:51.965 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 06:45:51.966 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:45:51.966 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 06:45:51.966 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 06:45:51.966 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 06:45:51.966 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 06:45:51.966 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 06:45:51.966 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 06:45:51.966 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 06:45:52.152 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 06:45:52.162 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 06:45:52.176 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 06:46:08.110 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:46:08.110 | INFO     | __main__:main:1369 - i: 0
2024-09-13 06:46:08.110 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 06:46:08.111 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:46:08.111 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:46:08.111 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 06:46:08.111 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 2] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 06:46:08.391 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:46:08.391 | INFO     | __main__:main:1369 - i: 0
2024-09-13 06:46:08.391 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 06:46:08.392 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:46:08.392 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:46:08.392 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 06:46:08.392 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 3] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 06:46:08.501 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 06:46:08.501 | INFO     | __main__:main:1369 - i: 0
2024-09-13 06:46:08.501 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 06:46:08.501 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 06:46:08.501 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 06:46:08.501 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 06:46:08.502 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 1] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 06:46:10.575 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 06:46:10.576 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 06:46:10.683 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 06:46:10.684 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 06:46:10.855 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 06:46:10.856 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 06:46:11.231 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 06:46:11.231 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 06:46:11.231 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
2024-09-13 06:46:11.285 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 06:46:11.286 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 06:46:11.286 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
2024-09-13 06:46:11.315 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 06:46:11.315 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 06:46:11.315 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
2024-09-13 06:46:11.340 | INFO     | __main__:main:1505 - right before barrier for data module
2024-09-13 06:46:11.340 | INFO     | __main__:main:1505 - right before barrier for data module
2024-09-13 06:46:11.341 | INFO     | __main__:main:1520 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
2024-09-13 06:46:11.341 | INFO     | __main__:main:1520 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
2024-09-13 06:46:11.359 | INFO     | __main__:main:1505 - right before barrier for data module
2024-09-13 06:46:11.359 | INFO     | __main__:main:1520 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 06:46:11.436 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 06:46:11.436 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 06:46:11.460 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 06:46:21.374 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 06:46:21.386 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 06:46:21.398 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 06:46:21.398 | INFO     | __main__:main:1534 - Training dataset size after load: 149228
2024-09-13 06:46:21.398 | INFO     | __main__:main:1535 - Validation dataset size after load: 2087
2024-09-13 06:46:21.398 | INFO     | __main__:main:1536 - Testing dataset size after load: 2298
2024-09-13 06:46:21.398 | INFO     | __main__:main:1538 - Starting progressive training from epoch 1 to 2
2024-09-13 06:46:21.398 | INFO     | __main__:main:1541 - hit the barrier before training
[rank: 2] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4

