2024-09-13 07:00:06.583 | INFO     | __main__:main:1694 - current epoch: 2
2024-09-13 07:00:06.583 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:00:06.583 | INFO     | __main__:main:1369 - i: 1
2024-09-13 07:00:06.583 | INFO     | __main__:main:1696 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1370, in main
    repo = lean_git_repos[i]
IndexError: list index out of range
Testing DataLoader 0:   0%|                                                                    | 0/9327 [00:03<?, ?it/s]
[rank0]:[W913 07:00:09.420119828 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed befor
e we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that
 any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and bl
ock the progress of another member of the process group. This constraint has always been present,  but this warning has
only been added since PyTorch 2.4 (function operator())
^Z
[8]+  Stopped                 bash run_code.sh
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
[2024-09-13 07:03:09,598] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 07:03:19.958 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:03:19.958 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:03:19.961 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:03:19.961 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:03:19.961 | INFO     | __main__:main:1210 - Starting the main process
2024-09-13 07:03:19.961 | INFO     | __main__:main:1218 - Loading database from /data/yingzi_ma/lean_project/dynamic_dat
abase_PT_single_repo_no_ewc.json
2024-09-13 07:03:40.766 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 07:03:40.766 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/lean
prover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 07:03:44.668 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/lecopivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 07:03:44.668 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/leco
pivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 07:03:44.955 | INFO     | __main__:main:1220 - Loaded database from /data/yingzi_ma/lean_project/dynamic_data
base_PT_single_repo_no_ewc.json
2024-09-13 07:03:44.956 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:03:44.956 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:03:45.339 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 07:04:01.588 | INFO     | __main__:main:1347 - Finding compatible repositories...
2024-09-13 07:04:01.600 | INFO     | __main__:main:1350 - Finished finding compatible repositories
2024-09-13 07:04:01.600 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:04:01.600 | INFO     | __main__:main:1369 - i: 0
2024-09-13 07:04:01.601 | INFO     | __main__:main:1375 - Main process
2024-09-13 07:04:01.601 | INFO     | __main__:main:1376 - Using lambda = 0.1
2024-09-13 07:04:01.601 | INFO     | __main__:main:1377 - Processing https://github.com/lecopivo/SciLean
2024-09-13 07:04:01.601 | INFO     | __main__:main:1398 - Adding repo to repos_for_merged_dataset
2024-09-13 07:04:01.601 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 07:04:01.603 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:04:01.603 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:04:01.603 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 07:04:01.603 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 0] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 07:04:04.477 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 07:04:04.480 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 07:04:04.886 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 07:04:04.887 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 07:04:04.887 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204
: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM,
prepend your python command with `srun` like so: srun python main.py ...
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
`Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
2024-09-13 07:04:05.425 | INFO     | __main__:main:1507 - right before barrier for data module
2024-09-13 07:04:05.427 | INFO     | __main__:main:1522 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 07:04:05.552 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 07:04:14.632 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:04:14.649 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:04:14.664 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 07:04:14.664 | INFO     | __main__:main:1536 - Training dataset size after load: 149228
2024-09-13 07:04:14.664 | INFO     | __main__:main:1537 - Validation dataset size after load: 2087
2024-09-13 07:04:14.664 | INFO     | __main__:main:1538 - Testing dataset size after load: 2298
2024-09-13 07:04:14.664 | INFO     | __main__:main:1540 - Starting progressive training from epoch 1 to 2
2024-09-13 07:04:14.664 | INFO     | __main__:main:1543 - hit the barrier before training
[rank: 0] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
[2024-09-13 07:04:27,096] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 07:04:27,098] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 07:04:27,098] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 07:04:36.469 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:04:36.469 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:04:36.469 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:04:36.469 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:04:36.469 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:04:36.469 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:04:36.472 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:04:36.472 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:04:36.472 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:04:36.472 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:04:36.472 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:04:36.472 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:04:36.472 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:04:36.472 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:04:36.472 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:04:36.472 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:04:36.472 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:04:36.473 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:04:36.654 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 07:04:36.665 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 07:04:36.674 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
^Z
[9]+  Stopped                 bash run_code.sh
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
[2024-09-13 07:05:05,662] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 07:05:14.965 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:05:14.966 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:05:14.968 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:05:14.968 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:05:14.969 | INFO     | __main__:main:1210 - Starting the main process
2024-09-13 07:05:14.969 | INFO     | __main__:main:1218 - Loading database from /data/yingzi_ma/lean_project/dynamic_dat
abase_PT_single_repo_no_ewc.json
2024-09-13 07:05:36.867 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 07:05:36.867 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/lean
prover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 07:05:41.125 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/lecopivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 07:05:41.125 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/leco
pivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 07:05:41.465 | INFO     | __main__:main:1220 - Loaded database from /data/yingzi_ma/lean_project/dynamic_data
base_PT_single_repo_no_ewc.json
2024-09-13 07:05:41.465 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:05:41.465 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:05:41.715 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 07:05:57.908 | INFO     | __main__:main:1347 - Finding compatible repositories...
2024-09-13 07:05:57.919 | INFO     | __main__:main:1350 - Finished finding compatible repositories
2024-09-13 07:05:57.920 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:05:57.920 | INFO     | __main__:main:1369 - i: 0
2024-09-13 07:05:57.920 | INFO     | __main__:main:1375 - Main process
2024-09-13 07:05:57.920 | INFO     | __main__:main:1376 - Using lambda = 0.1
2024-09-13 07:05:57.920 | INFO     | __main__:main:1377 - Processing https://github.com/lecopivo/SciLean
2024-09-13 07:05:57.920 | INFO     | __main__:main:1398 - Adding repo to repos_for_merged_dataset
2024-09-13 07:05:57.920 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 07:05:57.922 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:05:57.922 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:05:57.922 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 07:05:57.922 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 0] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 07:06:00.611 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 07:06:00.614 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 07:06:01.024 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 07:06:01.024 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 07:06:01.025 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204
: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM,
prepend your python command with `srun` like so: srun python main.py ...
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_val_batches=1)` was configured so 1 batch will be used.
2024-09-13 07:06:01.445 | INFO     | __main__:main:1507 - right before barrier for data module
2024-09-13 07:06:01.445 | INFO     | __main__:main:1522 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 07:06:01.589 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 07:06:11.112 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:06:11.129 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:06:11.144 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 07:06:11.144 | INFO     | __main__:main:1536 - Training dataset size after load: 149228
2024-09-13 07:06:11.144 | INFO     | __main__:main:1537 - Validation dataset size after load: 2087
2024-09-13 07:06:11.144 | INFO     | __main__:main:1538 - Testing dataset size after load: 2298
2024-09-13 07:06:11.144 | INFO     | __main__:main:1540 - Starting progressive training from epoch 1 to 2
2024-09-13 07:06:11.144 | INFO     | __main__:main:1543 - hit the barrier before training
[rank: 0] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
[2024-09-13 07:06:23,703] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 07:06:23,703] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 07:06:23,703] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 07:06:33.876 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:06:33.876 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:06:33.876 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:06:33.876 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:06:33.876 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:06:33.876 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:06:33.880 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:06:33.880 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:06:33.880 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:06:33.880 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:06:33.880 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:06:33.880 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:06:33.880 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:06:33.880 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:06:33.880 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:06:33.880 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:06:33.880 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:06:33.880 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:06:34.067 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 07:06:34.100 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 07:06:34.107 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 07:06:50.166 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:06:50.166 | INFO     | __main__:main:1369 - i: 0
2024-09-13 07:06:50.166 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 07:06:50.170 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:06:50.170 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:06:50.170 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 07:06:50.170 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 3] Seed set to 3407
2024-09-13 07:06:50.294 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:06:50.294 | INFO     | __main__:main:1369 - i: 0
2024-09-13 07:06:50.294 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 07:06:50.295 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:06:50.295 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:06:50.295 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 07:06:50.295 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 2] Seed set to 3407
2024-09-13 07:06:50.352 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:06:50.352 | INFO     | __main__:main:1369 - i: 0
2024-09-13 07:06:50.353 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 07:06:50.354 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:06:50.354 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:06:50.354 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 07:06:50.354 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 1] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 07:06:53.644 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 07:06:53.644 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 07:06:53.648 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
2024-09-13 07:06:53.648 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 07:06:53.659 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 07:06:53.661 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 07:06:54.240 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 07:06:54.240 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 07:06:54.240 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
2024-09-13 07:06:54.246 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 07:06:54.246 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 07:06:54.246 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
2024-09-13 07:06:54.261 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 07:06:54.261 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 07:06:54.261 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
2024-09-13 07:06:54.673 | INFO     | __main__:main:1507 - right before barrier for data module
2024-09-13 07:06:54.673 | INFO     | __main__:main:1507 - right before barrier for data module
2024-09-13 07:06:54.674 | INFO     | __main__:main:1507 - right before barrier for data module
2024-09-13 07:06:54.674 | INFO     | __main__:main:1522 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
2024-09-13 07:06:54.674 | INFO     | __main__:main:1522 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
2024-09-13 07:06:54.674 | INFO     | __main__:main:1522 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 07:06:54.805 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 07:06:54.805 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 07:06:54.805 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 07:07:05.662 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:07:05.681 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:07:05.696 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 07:07:05.696 | INFO     | __main__:main:1536 - Training dataset size after load: 149228
2024-09-13 07:07:05.696 | INFO     | __main__:main:1537 - Validation dataset size after load: 2087
2024-09-13 07:07:05.696 | INFO     | __main__:main:1538 - Testing dataset size after load: 2298
2024-09-13 07:07:05.696 | INFO     | __main__:main:1540 - Starting progressive training from epoch 1 to 2
2024-09-13 07:07:05.696 | INFO     | __main__:main:1543 - hit the barrier before training
2024-09-13 07:07:05.806 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:07:05.819 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:07:05.831 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 07:07:05.831 | INFO     | __main__:main:1536 - Training dataset size after load: 149228
2024-09-13 07:07:05.831 | INFO     | __main__:main:1537 - Validation dataset size after load: 2087
2024-09-13 07:07:05.831 | INFO     | __main__:main:1538 - Testing dataset size after load: 2298
2024-09-13 07:07:05.831 | INFO     | __main__:main:1540 - Starting progressive training from epoch 1 to 2
2024-09-13 07:07:05.831 | INFO     | __main__:main:1543 - hit the barrier before training
[rank: 1] Seed set to 3407
[rank: 3] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
2024-09-13 07:07:06.185 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:07:06.197 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:07:06.209 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 07:07:06.209 | INFO     | __main__:main:1536 - Training dataset size after load: 149228
2024-09-13 07:07:06.209 | INFO     | __main__:main:1537 - Validation dataset size after load: 2087
2024-09-13 07:07:06.209 | INFO     | __main__:main:1538 - Testing dataset size after load: 2298
2024-09-13 07:07:06.209 | INFO     | __main__:main:1540 - Starting progressive training from epoch 1 to 2
2024-09-13 07:07:06.209 | INFO     | __main__:main:1543 - hit the barrier before training
[rank: 2] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

NCCL version 2.20.5+cuda12.4
2024-09-13 07:07:08.598 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:07:08.711 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:07:08.731 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:65
3: Checkpoint directory /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_no_ewc exists and is not empty.
2024-09-13 07:07:10.055 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
2024-09-13 07:07:10.060 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
2024-09-13 07:07:10.111 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
Training dataset size: 149228
2024-09-13 07:07:10.149 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:07:10.153 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:07:10.165 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 07:07:10.174 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
Training dataset size: 149228
2024-09-13 07:07:10.195 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:07:10.210 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
Restoring states from the checkpoint path at /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_
new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_val=70.07.ckpt
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
2024-09-13 07:07:11.405 | INFO     | common:get_optimizers:449 - Optimizing with AdamW
2024-09-13 07:07:11.407 | INFO     | common:get_optimizers:449 - Optimizing with AdamW
2024-09-13 07:07:11.408 | INFO     | common:get_optimizers:449 - Optimizing with AdamW
2024-09-13 07:07:11.410 | INFO     | common:get_optimizers:449 - Optimizing with AdamW

  | Name    | Type           | Params
-------------------------------------------
0 | encoder | T5EncoderModel | 217 M
-------------------------------------------
217 M     Trainable params
0         Non-trainable params
217 M     Total params
870.630   Total estimated model params size (MB)
Restored all states from the checkpoint at /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_ne
w_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_val=70.07.ckpt
`Trainer.fit` stopped: `max_epochs=2` reached.
2024-09-13 07:07:14.994 | INFO     | __main__:main:1546 - hit the barrier after training
2024-09-13 07:07:15.242 | INFO     | __main__:main:1546 - hit the barrier after training
2024-09-13 07:07:15.254 | INFO     | __main__:main:1546 - hit the barrier after training
2024-09-13 07:07:15.257 | INFO     | __main__:main:1546 - hit the barrier after training
2024-09-13 07:07:15.257 | INFO     | __main__:main:1552 - Finished progressive training at epoch 2
2024-09-13 07:07:15.257 | INFO     | __main__:main:1552 - Finished progressive training at epoch 2
2024-09-13 07:07:15.257 | INFO     | __main__:main:1552 - Finished progressive training at epoch 2
2024-09-13 07:07:15.257 | INFO     | __main__:main:1552 - Finished progressive training at epoch 2
2024-09-13 07:07:15.260 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:07:15.260 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:07:15.260 | INFO     | __main__:main:1559 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:07:15.260 | INFO     | __main__:main:1559 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:07:15.260 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:07:15.260 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:07:15.260 | INFO     | __main__:main:1559 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:07:15.260 | INFO     | __main__:main:1559 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:07:17.669 | INFO     | __main__:main:1625 - Calculating Fisher Information Matrix for EWC
2024-09-13 07:07:17.669 | INFO     | __main__:main:1629 - right before barrier fisher
2024-09-13 07:07:17.697 | INFO     | __main__:main:1625 - Calculating Fisher Information Matrix for EWC
2024-09-13 07:07:17.697 | INFO     | __main__:main:1629 - right before barrier fisher
2024-09-13 07:07:18.106 | INFO     | __main__:main:1625 - Calculating Fisher Information Matrix for EWC
2024-09-13 07:07:18.106 | INFO     | __main__:main:1629 - right before barrier fisher
2024-09-13 07:07:18.130 | INFO     | __main__:main:1625 - Calculating Fisher Information Matrix for EWC
2024-09-13 07:07:18.130 | INFO     | __main__:main:1629 - right before barrier fisher
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204
: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM,
prepend your python command with `srun` like so: srun python main.py ...
[rank: 1] Seed set to 3407
[rank: 0] Seed set to 3407
[rank: 2] Seed set to 3407
[rank: 3] Seed set to 3407
2024-09-13 07:07:21.470 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:07:23.004 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:07:23.297 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
2024-09-13 07:07:23.324 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
Training dataset size: 149228
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connecto
r.py:232: Using `DistributedSampler` with the dataloaders. During `trainer.test()`, it is recommended to use `Trainer(de
vices=1, num_nodes=1)` to ensure each sample/batch gets evaluated exactly once. Otherwise, multi-device settings use `Di
stributedSampler` that replicates some samples to make sure all devices have same batch size in case of uneven inputs.
2024-09-13 07:07:24.164 | INFO     | retrieval.model:on_test_start:398 - Fisher info cleared
2024-09-13 07:07:24.193 | INFO     | retrieval.model:on_test_start:400 - Previous params saved
2024-09-13 07:07:24.242 | INFO     | retrieval.model:on_test_start:398 - Fisher info cleared
2024-09-13 07:07:24.265 | INFO     | retrieval.model:test_step:406 - Inside test_step
2024-09-13 07:07:24.284 | INFO     | retrieval.model:on_test_start:400 - Previous params saved
2024-09-13 07:07:24.336 | INFO     | retrieval.model:on_test_start:398 - Fisher info cleared
Testing: |                                                                                        | 0/? [00:00<?, ?it/s]
2024-09-13 07:07:24.361 | INFO     | retrieval.model:on_test_start:398 - Fisher info cleared
2024-09-13 07:07:24.392 | INFO     | retrieval.model:on_test_start:400 - Previous params saved
2024-09-13 07:07:24.394 | INFO     | retrieval.model:on_test_start:400 - Previous params saved
Testing DataLoader 0:   0%|                                                                    | 0/9327 [00:00<?, ?it/s]
2024-09-13 07:07:24.429 | INFO     | retrieval.model:test_step:406 - Inside test_step
2024-09-13 07:07:24.451 | INFO     | retrieval.model:test_step:406 - Inside test_step
2024-09-13 07:07:24.470 | INFO     | retrieval.model:test_step:406 - Inside test_step
2024-09-13 07:07:24.833 | INFO     | retrieval.model:test_step:416 - Test loss before EWC: 0.0302
2024-09-13 07:07:24.972 | INFO     | retrieval.model:test_step:416 - Test loss before EWC: 0.0136
2024-09-13 07:07:25.037 | INFO     | retrieval.model:test_step:416 - Test loss before EWC: 0.0247
2024-09-13 07:07:25.048 | INFO     | retrieval.model:test_step:416 - Test loss before EWC: 0.0354
An error occurred during fisher: element 0 of tensors does not require grad and does not have a grad_fn
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1631, in main
    trainer.test(model, datamodule=data_module)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 754, in test
    return call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 4
3, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/sub
process_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 987, in _run
    results = self._run_stage()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 1026, in _run_stage
    return self._evaluation_loop.run()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", lin
e 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 3
09, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py",
 line 425, in test_step
    return self.lightning_module.test_step(*args, **kwargs)
  File "/data/yingzi_ma/lean_project/ReProver/retrieval/model.py", line 417, in test_step
    loss.backward()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/__init__.py", line 289, in
backward
    _engine_run_backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/graph.py", line 768, in _en
gine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

2024-09-13 07:07:25.709 | INFO     | __main__:main:1692 - Finished processing the repository
2024-09-13 07:07:25.709 | INFO     | __main__:main:1694 - current epoch: 2
2024-09-13 07:07:25.709 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:07:25.709 | INFO     | __main__:main:1369 - i: 1
2024-09-13 07:07:25.709 | INFO     | __main__:main:1696 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1370, in main
    repo = lean_git_repos[i]
IndexError: list index out of range
An error occurred during fisher: element 0 of tensors does not require grad and does not have a grad_fn
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1631, in main
    trainer.test(model, datamodule=data_module)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 754, in test
    return call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 4
3, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/sub
process_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 987, in _run
    results = self._run_stage()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 1026, in _run_stage
    return self._evaluation_loop.run()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", lin
e 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 3
09, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py",
 line 425, in test_step
    return self.lightning_module.test_step(*args, **kwargs)
  File "/data/yingzi_ma/lean_project/ReProver/retrieval/model.py", line 417, in test_step
    loss.backward()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/__init__.py", line 289, in
backward
    _engine_run_backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/graph.py", line 768, in _en
gine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

2024-09-13 07:07:25.901 | INFO     | __main__:main:1692 - Finished processing the repository
2024-09-13 07:07:25.901 | INFO     | __main__:main:1694 - current epoch: 2
2024-09-13 07:07:25.902 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:07:25.902 | INFO     | __main__:main:1369 - i: 1
2024-09-13 07:07:25.902 | INFO     | __main__:main:1696 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1370, in main
    repo = lean_git_repos[i]
IndexError: list index out of range
An error occurred during fisher: element 0 of tensors does not require grad and does not have a grad_fn
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1631, in main
    trainer.test(model, datamodule=data_module)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 754, in test
    return call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 4
3, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/sub
process_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 987, in _run
    results = self._run_stage()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 1026, in _run_stage
    return self._evaluation_loop.run()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", lin
e 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 3
09, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py",
 line 425, in test_step
    return self.lightning_module.test_step(*args, **kwargs)
  File "/data/yingzi_ma/lean_project/ReProver/retrieval/model.py", line 417, in test_step
    loss.backward()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/__init__.py", line 289, in
backward
    _engine_run_backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/graph.py", line 768, in _en
gine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

2024-09-13 07:07:25.935 | INFO     | __main__:main:1692 - Finished processing the repository
2024-09-13 07:07:25.935 | INFO     | __main__:main:1694 - current epoch: 2
2024-09-13 07:07:25.935 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:07:25.935 | INFO     | __main__:main:1369 - i: 1
2024-09-13 07:07:25.935 | INFO     | __main__:main:1696 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1370, in main
    repo = lean_git_repos[i]
IndexError: list index out of range
An error occurred during fisher: element 0 of tensors does not require grad and does not have a grad_fn
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1631, in main
    trainer.test(model, datamodule=data_module)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 754, in test
    return call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 4
3, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/sub
process_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 987, in _run
    results = self._run_stage()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 1026, in _run_stage
    return self._evaluation_loop.run()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", lin
e 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 3
09, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py",
 line 425, in test_step
    return self.lightning_module.test_step(*args, **kwargs)
  File "/data/yingzi_ma/lean_project/ReProver/retrieval/model.py", line 417, in test_step
    loss.backward()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/__init__.py", line 289, in
backward
    _engine_run_backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/graph.py", line 768, in _en
gine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

2024-09-13 07:07:26.047 | INFO     | __main__:main:1692 - Finished processing the repository
2024-09-13 07:07:26.047 | INFO     | __main__:main:1694 - current epoch: 2
2024-09-13 07:07:26.048 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:07:26.048 | INFO     | __main__:main:1369 - i: 1
2024-09-13 07:07:26.048 | INFO     | __main__:main:1696 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1370, in main
    repo = lean_git_repos[i]
IndexError: list index out of range
Testing DataLoader 0:   0%|                                                                    | 0/9327 [00:03<?, ?it/s]
[rank0]:[W913 07:07:29.362491251 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed befor
e we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that
 any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and bl
ock the progress of another member of the process group. This constraint has always been present,  but this warning has
only been added since PyTorch 2.4 (function operator())
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
[2024-09-13 07:08:42,657] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 07:08:51.876 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:08:51.876 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:08:51.879 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:08:51.879 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:08:51.879 | INFO     | __main__:main:1210 - Starting the main process
2024-09-13 07:08:51.880 | INFO     | __main__:main:1218 - Loading database from /data/yingzi_ma/lean_project/dynamic_dat
abase_PT_single_repo_no_ewc.json
2024-09-13 07:09:14.016 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 07:09:14.016 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/lean
prover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 07:09:18.254 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/lecopivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 07:09:18.254 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/leco
pivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 07:09:18.574 | INFO     | __main__:main:1220 - Loaded database from /data/yingzi_ma/lean_project/dynamic_data
base_PT_single_repo_no_ewc.json
2024-09-13 07:09:18.574 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:09:18.574 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:09:18.976 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 07:09:35.256 | INFO     | __main__:main:1347 - Finding compatible repositories...
2024-09-13 07:09:35.265 | INFO     | __main__:main:1350 - Finished finding compatible repositories
2024-09-13 07:09:35.265 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:09:35.265 | INFO     | __main__:main:1369 - i: 0
2024-09-13 07:09:35.265 | INFO     | __main__:main:1375 - Main process
2024-09-13 07:09:35.265 | INFO     | __main__:main:1376 - Using lambda = 0.1
2024-09-13 07:09:35.266 | INFO     | __main__:main:1377 - Processing https://github.com/lecopivo/SciLean
2024-09-13 07:09:35.266 | INFO     | __main__:main:1398 - Adding repo to repos_for_merged_dataset
2024-09-13 07:09:35.266 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 07:09:35.268 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:09:35.268 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:09:35.268 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 07:09:35.268 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 0] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 07:09:38.051 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 07:09:38.055 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 07:09:38.416 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 07:09:38.416 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 07:09:38.416 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204
: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM,
prepend your python command with `srun` like so: srun python main.py ...
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_val_batches=1)` was configured so 1 batch will be used.
2024-09-13 07:09:38.809 | INFO     | __main__:main:1507 - right before barrier for data module
2024-09-13 07:09:38.810 | INFO     | __main__:main:1522 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 07:09:38.927 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 07:09:48.483 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:09:48.499 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:09:48.513 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 07:09:48.513 | INFO     | __main__:main:1536 - Training dataset size after load: 149228
2024-09-13 07:09:48.513 | INFO     | __main__:main:1537 - Validation dataset size after load: 2087
2024-09-13 07:09:48.513 | INFO     | __main__:main:1538 - Testing dataset size after load: 2298
2024-09-13 07:09:48.513 | INFO     | __main__:main:1540 - Starting progressive training from epoch 1 to 2
2024-09-13 07:09:48.513 | INFO     | __main__:main:1543 - hit the barrier before training
[rank: 0] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
[2024-09-13 07:10:01,173] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 07:10:01,174] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 07:10:01,175] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 07:10:11.048 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:10:11.048 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:10:11.048 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:10:11.048 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:10:11.048 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:10:11.048 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:10:11.053 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:10:11.054 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:10:11.054 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:10:11.054 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:10:11.054 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:10:11.054 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:10:11.054 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:10:11.054 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:10:11.054 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:10:11.054 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:10:11.054 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:10:11.054 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:10:11.279 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 07:10:11.283 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 07:10:11.320 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
^Z
[10]+  Stopped                 bash run_code.sh
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$ bash run_code.sh
Script executed from: /data/yingzi_ma/lean_project/ReProver
Removing old cache files
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834741.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834743.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834746.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834747.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_835354.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_GCS.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834744.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_RAYLET.log': Permission denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834742.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_833907.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_AUTOSCALER.log': Permission deni
ed
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834748.log': Permiss
ion denied
rm: cannot remove '/tmp/ray/session_2024-08-22_03-10-43_407834_833965/logs/events/event_CORE_WORKER_834745.log': Permiss
ion denied
Stopping ray
Could not terminate `/usr/bin/python3 /usr/local/bin/user_traffic_monitor.py` due to (pid=784996, name='python3')
Did not find any active Ray processes.
Running main.py
[2024-09-13 07:16:25,072] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 07:16:30.001 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:16:30.001 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:16:30.004 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:16:30.004 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:16:30.004 | INFO     | __main__:main:1210 - Starting the main process
2024-09-13 07:16:30.004 | INFO     | __main__:main:1218 - Loading database from /data/yingzi_ma/lean_project/dynamic_dat
abase_PT_single_repo_no_ewc.json
2024-09-13 07:16:52.225 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/leanprover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 07:16:52.225 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/lean
prover-community/mathlib4 (commit: 2b29e73438e240a427bcecc7c0fe19306beb1310)
2024-09-13 07:16:56.529 | INFO     | dynamic_database:add_repository:600 - Attempting to add repository: https://github.
com/lecopivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 07:16:56.529 | INFO     | dynamic_database:add_repository:603 - Added new repository: https://github.com/leco
pivo/SciLean (commit: 22d53b2f4e3db2a172e71da6eb9c916e62655744)
2024-09-13 07:16:56.854 | INFO     | __main__:main:1220 - Loaded database from /data/yingzi_ma/lean_project/dynamic_data
base_PT_single_repo_no_ewc.json
2024-09-13 07:16:56.854 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:16:56.854 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:16:57.305 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 07:17:13.123 | INFO     | __main__:main:1347 - Finding compatible repositories...
2024-09-13 07:17:13.126 | INFO     | __main__:main:1350 - Finished finding compatible repositories
2024-09-13 07:17:13.126 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:17:13.126 | INFO     | __main__:main:1369 - i: 0
2024-09-13 07:17:13.126 | INFO     | __main__:main:1375 - Main process
2024-09-13 07:17:13.126 | INFO     | __main__:main:1376 - Using lambda = 0.1
2024-09-13 07:17:13.126 | INFO     | __main__:main:1377 - Processing https://github.com/lecopivo/SciLean
2024-09-13 07:17:13.126 | INFO     | __main__:main:1398 - Adding repo to repos_for_merged_dataset
2024-09-13 07:17:13.127 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 07:17:13.127 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:17:13.127 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:17:13.128 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 07:17:13.128 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 0] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 07:17:15.371 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 07:17:15.372 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 07:17:15.757 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 07:17:15.758 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 07:17:15.758 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204
: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM,
prepend your python command with `srun` like so: srun python main.py ...
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_val_batches=1)` was configured so 1 batch will be used.
2024-09-13 07:17:15.896 | INFO     | __main__:main:1507 - right before barrier for data module
2024-09-13 07:17:15.896 | INFO     | __main__:main:1522 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 07:17:16.000 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 07:17:25.674 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:17:25.688 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:17:25.701 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 07:17:25.701 | INFO     | __main__:main:1536 - Training dataset size after load: 149228
2024-09-13 07:17:25.701 | INFO     | __main__:main:1537 - Validation dataset size after load: 2087
2024-09-13 07:17:25.701 | INFO     | __main__:main:1538 - Testing dataset size after load: 2298
2024-09-13 07:17:25.701 | INFO     | __main__:main:1540 - Starting progressive training from epoch 1 to 2
2024-09-13 07:17:25.701 | INFO     | __main__:main:1543 - hit the barrier before training
[rank: 0] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
[2024-09-13 07:17:31,922] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 07:17:31,922] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-09-13 07:17:31,922] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-09-13 07:17:36.601 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:17:36.601 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:17:36.601 | INFO     | __main__:main:1197 - Running progressive training
2024-09-13 07:17:36.601 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:17:36.601 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:17:36.601 | INFO     | __main__:main:1203 - Configuring LeanDojo...
2024-09-13 07:17:36.604 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:17:36.604 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:17:36.604 | INFO     | generate_benchmark_lean4:configure_leandojo:347 - Current working directory: /data/
yingzi_ma/lean_project/ReProver
2024-09-13 07:17:36.604 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:17:36.604 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:17:36.604 | INFO     | __main__:main:1205 - LeanDojo configured
2024-09-13 07:17:36.604 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:17:36.604 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:17:36.604 | INFO     | __main__:main:1227 - Found 15 repositories
2024-09-13 07:17:36.604 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:17:36.604 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:17:36.604 | INFO     | __main__:main:1318 - Starting without curriculum learning
2024-09-13 07:17:36.800 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 07:17:36.801 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 07:17:36.841 | DEBUG    | lean_dojo.data_extraction.lean:_to_commit_hash:90 - Querying the commit hash for le
an4 v4.7.0
2024-09-13 07:17:52.592 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:17:52.592 | INFO     | __main__:main:1369 - i: 0
2024-09-13 07:17:52.592 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 07:17:52.594 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:17:52.594 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:17:52.594 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 07:17:52.594 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 3] Seed set to 3407
2024-09-13 07:17:52.736 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:17:52.737 | INFO     | __main__:main:1369 - i: 0
2024-09-13 07:17:52.737 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 07:17:52.737 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:17:52.737 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:17:52.737 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 07:17:52.737 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 1] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 07:17:52.918 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:17:52.919 | INFO     | __main__:main:1369 - i: 0
2024-09-13 07:17:52.919 | INFO     | __main__:main:1409 - All GPUs
2024-09-13 07:17:52.919 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:17:52.919 | INFO     | __main__:main:1416 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:17:52.920 | INFO     | __main__:main:1422 - Inside train_test_fisher
2024-09-13 07:17:52.920 | INFO     | __main__:main:1423 - Starting training at epoch 1
[rank: 2] Seed set to 3407
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
2024-09-13 07:17:55.285 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 07:17:55.286 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 07:17:55.538 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 07:17:55.539 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 07:17:55.609 | INFO     | __main__:main:1447 - Loaded premise retriever at /data/yingzi_ma/lean_project/check
points_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@
10_val=70.07.ckpt
2024-09-13 07:17:55.610 | INFO     | __main__:find_latest_fisher:527 - Using the latest Fisher Information Matrix: /data
/yingzi_ma/lean_project/fisher_PT_single_repo_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_fishe
r_info.pkl
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using
 `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It
 is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.
com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for
 `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary
 objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `to
rch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't
 have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental featur
e.
  return torch.load(io.BytesIO(b))
2024-09-13 07:17:55.800 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 07:17:55.801 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 07:17:55.801 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
2024-09-13 07:17:55.930 | INFO     | __main__:main:1507 - right before barrier for data module
2024-09-13 07:17:55.931 | INFO     | __main__:main:1522 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 07:17:56.041 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 07:17:56.169 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 07:17:56.169 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 07:17:56.170 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
2024-09-13 07:17:56.182 | INFO     | __main__:load_fisher_information:503 - Fisher Information successfully loaded.
2024-09-13 07:17:56.183 | INFO     | retrieval.model:set_fisher_info:60 - Fisher Information has been updated in the mod
el.
2024-09-13 07:17:56.183 | INFO     | __main__:main:1454 - Fisher Information Matrix loaded.
2024-09-13 07:17:56.226 | INFO     | __main__:main:1507 - right before barrier for data module
2024-09-13 07:17:56.227 | INFO     | __main__:main:1522 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
2024-09-13 07:17:56.232 | INFO     | __main__:main:1507 - right before barrier for data module
2024-09-13 07:17:56.232 | INFO     | __main__:main:1522 - Data path: /data/yingzi_ma/lean_project/datasets_PT_single_rep
o_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: Futu
reWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprac
ted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github
.com/huggingface/transformers/issues/31884
  warnings.warn(
2024-09-13 07:17:56.325 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 07:17:56.327 | INFO     | common:__init__:212 - Building the corpus from /data/yingzi_ma/lean_project/dataset
s_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/corpus.jsonl
2024-09-13 07:18:06.673 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:18:06.686 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:18:06.698 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 07:18:06.698 | INFO     | __main__:main:1536 - Training dataset size after load: 149228
2024-09-13 07:18:06.699 | INFO     | __main__:main:1537 - Validation dataset size after load: 2087
2024-09-13 07:18:06.699 | INFO     | __main__:main:1538 - Testing dataset size after load: 2298
2024-09-13 07:18:06.699 | INFO     | __main__:main:1540 - Starting progressive training from epoch 1 to 2
2024-09-13 07:18:06.699 | INFO     | __main__:main:1543 - hit the barrier before training
[rank: 3] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
2024-09-13 07:18:07.080 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:18:07.093 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:18:07.105 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 07:18:07.106 | INFO     | __main__:main:1536 - Training dataset size after load: 149228
2024-09-13 07:18:07.106 | INFO     | __main__:main:1537 - Validation dataset size after load: 2087
2024-09-13 07:18:07.106 | INFO     | __main__:main:1538 - Testing dataset size after load: 2298
2024-09-13 07:18:07.106 | INFO     | __main__:main:1540 - Starting progressive training from epoch 1 to 2
2024-09-13 07:18:07.106 | INFO     | __main__:main:1543 - hit the barrier before training
[rank: 2] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
2024-09-13 07:18:07.368 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:18:07.379 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:18:07.391 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 07:18:07.391 | INFO     | __main__:main:1536 - Training dataset size after load: 149228
2024-09-13 07:18:07.391 | INFO     | __main__:main:1537 - Validation dataset size after load: 2087
2024-09-13 07:18:07.391 | INFO     | __main__:main:1538 - Testing dataset size after load: 2298
2024-09-13 07:18:07.391 | INFO     | __main__:main:1540 - Starting progressive training from epoch 1 to 2
2024-09-13 07:18:07.391 | INFO     | __main__:main:1543 - hit the barrier before training
[rank: 1] Seed set to 3407
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

NCCL version 2.20.5+cuda12.4
2024-09-13 07:18:09.477 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:18:09.580 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:18:09.599 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:65
3: Checkpoint directory /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_no_ewc exists and is not empty.
2024-09-13 07:18:10.649 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:18:10.730 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:18:10.745 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
2024-09-13 07:18:10.817 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
2024-09-13 07:18:10.863 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:18:10.909 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:18:10.925 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
Training dataset size: 149228
2024-09-13 07:18:10.951 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_val/cached_data.pkl
Validation dataset size: 2087
2024-09-13 07:18:10.966 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_pred/cached_data.pkl
Testing dataset size: 2298
Restoring states from the checkpoint path at /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_
new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_val=70.07.ckpt
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py:57: You are
 using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicit
ly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://g
ithub.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default val
ue for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arb
itrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user v
ia `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you
 don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental
feature.
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
2024-09-13 07:18:12.178 | INFO     | common:get_optimizers:449 - Optimizing with AdamW
2024-09-13 07:18:12.179 | INFO     | common:get_optimizers:449 - Optimizing with AdamW
2024-09-13 07:18:12.179 | INFO     | common:get_optimizers:449 - Optimizing with AdamW
2024-09-13 07:18:12.181 | INFO     | common:get_optimizers:449 - Optimizing with AdamW

  | Name    | Type           | Params
-------------------------------------------
0 | encoder | T5EncoderModel | 217 M
-------------------------------------------
217 M     Trainable params
0         Non-trainable params
217 M     Total params
870.630   Total estimated model params size (MB)
Restored all states from the checkpoint at /data/yingzi_ma/lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_ne
w_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_val=70.07.ckpt
`Trainer.fit` stopped: `max_epochs=2` reached.
2024-09-13 07:18:15.552 | INFO     | __main__:main:1546 - hit the barrier after training
2024-09-13 07:18:15.636 | INFO     | __main__:main:1546 - hit the barrier after training
2024-09-13 07:18:15.873 | INFO     | __main__:main:1546 - hit the barrier after training
2024-09-13 07:18:15.956 | INFO     | __main__:main:1546 - hit the barrier after training
2024-09-13 07:18:15.956 | INFO     | __main__:main:1552 - Finished progressive training at epoch 2
2024-09-13 07:18:15.957 | INFO     | __main__:main:1552 - Finished progressive training at epoch 2
2024-09-13 07:18:15.957 | INFO     | __main__:main:1552 - Finished progressive training at epoch 2
2024-09-13 07:18:15.957 | INFO     | __main__:main:1552 - Finished progressive training at epoch 2
2024-09-13 07:18:15.957 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:18:15.957 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:18:15.957 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:18:15.957 | INFO     | __main__:find_latest_checkpoint:517 - Using the latest checkpoint: /data/yingzi_ma/
lean_project/checkpoints_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0
.1_epoch=1-Recall@10_val=70.07.ckpt
2024-09-13 07:18:15.957 | INFO     | __main__:main:1559 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:18:15.957 | INFO     | __main__:main:1559 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:18:15.957 | INFO     | __main__:main:1559 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:18:15.958 | INFO     | __main__:main:1559 - Found latest checkpoint: /data/yingzi_ma/lean_project/checkpoi
nts_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744_lambda_0.1_epoch=1-Recall@10_
val=70.07.ckpt
2024-09-13 07:18:18.352 | INFO     | __main__:main:1625 - Calculating Fisher Information Matrix for EWC
2024-09-13 07:18:18.352 | INFO     | __main__:main:1629 - right before barrier fisher
2024-09-13 07:18:18.422 | INFO     | __main__:main:1625 - Calculating Fisher Information Matrix for EWC
2024-09-13 07:18:18.422 | INFO     | __main__:main:1629 - right before barrier fisher
2024-09-13 07:18:18.688 | INFO     | __main__:main:1625 - Calculating Fisher Information Matrix for EWC
2024-09-13 07:18:18.688 | INFO     | __main__:main:1629 - right before barrier fisher
2024-09-13 07:18:18.962 | INFO     | __main__:main:1625 - Calculating Fisher Information Matrix for EWC
2024-09-13 07:18:18.963 | INFO     | __main__:main:1629 - right before barrier fisher
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/lightning_fabric/plugins/environments/slurm.py:204
: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM,
prepend your python command with `srun` like so: srun python main.py ...
[rank: 2] Seed set to 3407
[rank: 0] Seed set to 3407
[rank: 3] Seed set to 3407
[rank: 1] Seed set to 3407
2024-09-13 07:18:22.367 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:18:23.592 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
2024-09-13 07:18:23.827 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
2024-09-13 07:18:23.890 | INFO     | retrieval.datamodule:load_or_cache_data:52 - Loaded data from cache /data/yingzi_ma
/lean_project/datasets_PT_single_repo_no_ewc/merged_with_new_SciLean_22d53b2f4e3db2a172e71da6eb9c916e62655744/random/cac
he_train/cached_data.pkl
Training dataset size: 149228
Training dataset size: 149228
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connecto
r.py:232: Using `DistributedSampler` with the dataloaders. During `trainer.test()`, it is recommended to use `Trainer(de
vices=1, num_nodes=1)` to ensure each sample/batch gets evaluated exactly once. Otherwise, multi-device settings use `Di
stributedSampler` that replicates some samples to make sure all devices have same batch size in case of uneven inputs.
2024-09-13 07:18:24.704 | INFO     | retrieval.model:on_test_start:398 - Fisher info cleared
2024-09-13 07:18:24.736 | INFO     | retrieval.model:on_test_start:400 - Previous params saved
2024-09-13 07:18:24.796 | INFO     | retrieval.model:on_test_start:398 - Fisher info cleared
2024-09-13 07:18:24.819 | INFO     | retrieval.model:on_test_start:400 - Previous params saved
2024-09-13 07:18:24.825 | INFO     | retrieval.model:test_step:406 - Inside test_step
2024-09-13 07:18:24.849 | INFO     | retrieval.model:on_test_start:398 - Fisher info cleared
2024-09-13 07:18:24.886 | INFO     | retrieval.model:on_test_start:400 - Previous params saved
2024-09-13 07:18:24.904 | INFO     | retrieval.model:test_step:406 - Inside test_step
Testing: |                                                                                        | 0/? [00:00<?, ?it/s]
2024-09-13 07:18:24.926 | INFO     | retrieval.model:on_test_start:398 - Fisher info cleared
2024-09-13 07:18:24.947 | INFO     | retrieval.model:on_test_start:400 - Previous params saved
2024-09-13 07:18:25.004 | INFO     | retrieval.model:test_step:406 - Inside test_step
Testing DataLoader 0:   0%|                                                                    | 0/9327 [00:00<?, ?it/s]
2024-09-13 07:18:25.053 | INFO     | retrieval.model:test_step:406 - Inside test_step
2024-09-13 07:18:25.437 | INFO     | retrieval.model:test_step:416 - Test loss before EWC: 0.0135
2024-09-13 07:18:25.555 | INFO     | retrieval.model:test_step:416 - Test loss before EWC: 0.0290
2024-09-13 07:18:25.556 | INFO     | retrieval.model:test_step:416 - Test loss before EWC: 0.0257
2024-09-13 07:18:25.777 | INFO     | retrieval.model:test_step:416 - Test loss before EWC: 0.0351
An error occurred during fisher: element 0 of tensors does not require grad and does not have a grad_fn
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1631, in main
    trainer.test(model, datamodule=data_module)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 754, in test
    return call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 4
3, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/sub
process_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 987, in _run
    results = self._run_stage()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 1026, in _run_stage
    return self._evaluation_loop.run()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", lin
e 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 3
09, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py",
 line 425, in test_step
    return self.lightning_module.test_step(*args, **kwargs)
  File "/data/yingzi_ma/lean_project/ReProver/retrieval/model.py", line 417, in test_step
    loss.backward()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/__init__.py", line 289, in
backward
    _engine_run_backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/graph.py", line 768, in _en
gine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

2024-09-13 07:18:26.186 | INFO     | __main__:main:1692 - Finished processing the repository
2024-09-13 07:18:26.186 | INFO     | __main__:main:1694 - current epoch: 2
2024-09-13 07:18:26.186 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:18:26.186 | INFO     | __main__:main:1369 - i: 1
2024-09-13 07:18:26.186 | INFO     | __main__:main:1696 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1370, in main
    repo = lean_git_repos[i]
IndexError: list index out of range
An error occurred during fisher: element 0 of tensors does not require grad and does not have a grad_fn
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1631, in main
    trainer.test(model, datamodule=data_module)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 754, in test
    return call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 4
3, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/sub
process_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 987, in _run
    results = self._run_stage()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 1026, in _run_stage
    return self._evaluation_loop.run()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", lin
e 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 3
09, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py",
 line 425, in test_step
    return self.lightning_module.test_step(*args, **kwargs)
  File "/data/yingzi_ma/lean_project/ReProver/retrieval/model.py", line 417, in test_step
    loss.backward()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/__init__.py", line 289, in
backward
    _engine_run_backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/graph.py", line 768, in _en
gine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

2024-09-13 07:18:26.372 | INFO     | __main__:main:1692 - Finished processing the repository
2024-09-13 07:18:26.372 | INFO     | __main__:main:1694 - current epoch: 2
2024-09-13 07:18:26.372 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:18:26.372 | INFO     | __main__:main:1369 - i: 1
2024-09-13 07:18:26.372 | INFO     | __main__:main:1696 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1370, in main
    repo = lean_git_repos[i]
IndexError: list index out of range
An error occurred during fisher: element 0 of tensors does not require grad and does not have a grad_fn
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1631, in main
    trainer.test(model, datamodule=data_module)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 754, in test
    return call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 4
3, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/sub
process_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 987, in _run
    results = self._run_stage()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 1026, in _run_stage
    return self._evaluation_loop.run()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", lin
e 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 3
09, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py",
 line 425, in test_step
    return self.lightning_module.test_step(*args, **kwargs)
  File "/data/yingzi_ma/lean_project/ReProver/retrieval/model.py", line 417, in test_step
    loss.backward()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/__init__.py", line 289, in
backward
    _engine_run_backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/graph.py", line 768, in _en
gine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

2024-09-13 07:18:26.405 | INFO     | __main__:main:1692 - Finished processing the repository
2024-09-13 07:18:26.405 | INFO     | __main__:main:1694 - current epoch: 2
2024-09-13 07:18:26.405 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:18:26.406 | INFO     | __main__:main:1369 - i: 1
2024-09-13 07:18:26.406 | INFO     | __main__:main:1696 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1370, in main
    repo = lean_git_repos[i]
IndexError: list index out of range
An error occurred during fisher: element 0 of tensors does not require grad and does not have a grad_fn
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1631, in main
    trainer.test(model, datamodule=data_module)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 754, in test
    return call._call_and_handle_interrupt(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 4
3, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/sub
process_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 987, in _run
    results = self._run_stage()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", lin
e 1026, in _run_stage
    return self._evaluation_loop.run()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", lin
e 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py
", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 3
09, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py",
 line 425, in test_step
    return self.lightning_module.test_step(*args, **kwargs)
  File "/data/yingzi_ma/lean_project/ReProver/retrieval/model.py", line 417, in test_step
    loss.backward()
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/__init__.py", line 289, in
backward
    _engine_run_backward(
  File "/data/yingzi_ma/miniconda3/envs/ReProver/lib/python3.10/site-packages/torch/autograd/graph.py", line 768, in _en
gine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

2024-09-13 07:18:26.687 | INFO     | __main__:main:1692 - Finished processing the repository
2024-09-13 07:18:26.687 | INFO     | __main__:main:1694 - current epoch: 2
2024-09-13 07:18:26.687 | INFO     | __main__:main:1368 - length of lean_git_repos: 1
2024-09-13 07:18:26.687 | INFO     | __main__:main:1369 - i: 1
2024-09-13 07:18:26.687 | INFO     | __main__:main:1696 - An error occurred: list index out of range
Traceback (most recent call last):
  File "/data/yingzi_ma/lean_project/ReProver/main.py", line 1370, in main
    repo = lean_git_repos[i]
IndexError: list index out of range
Testing DataLoader 0:   0%|                                                                    | 0/9327 [00:03<?, ?it/s]
[rank0]:[W913 07:18:30.837615183 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed befor
e we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that
 any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and bl
ock the progress of another member of the process group. This constraint has always been present,  but this warning has
only been added since PyTorch 2.4 (function operator())
(base) yingzi_ma@compute-permanent-node-352:~/lean_project/ReProver$
